In [1]:
import pandas as pd
import numpy as np


from util import *
from Model import Sequence_Generator
from Preprocessing import food_dict, nutrient_data, incidence_data,candidate_data, tf_dataset, tf_dataset_update, kwargs

import tensorflow as tf
import copy
import csv
import time
import pickle

args : <function get_params at 0x000001E9DBF09310>

100%|██████████| 261/261 [00:01<00:00, 192.41it/s]

0 diets are deleted as they have more than 3 empty slots

100%|██████████| 1195/1195 [00:06<00:00, 193.44it/s]

0 diets are deleted as they have more than 3 empty slots

In [26]:
list(tf_dataset)

[<tf.Tensor: shape=(261, 19), dtype=int32, numpy=
 array([[3716, 3108, 2922, ..., 1046,  973, 3715],
        [3716, 3246, 2961, ..., 2068,  973, 3715],
        [3716, 3317, 2957, ..., 1111,  968, 3715],
        ...,
        [3716, 3307, 2937, ..., 1103,  973, 3715],
        [3716, 2914, 2934, ..., 2381,  984, 3715],
        [3716, 3321, 2939, ..., 2434,  973, 3715]])>]

In [5]:
# Parameter (2) Constant Parameter Initialization
num_epochs = kwargs['num_epochs']
lr = kwargs['lr']
batch_size = kwargs['batch_size']
target_buffer_size = kwargs['buffer_size']
target_buffer_update = kwargs['buffer_update']
buffer_change_num = kwargs['buffer_change_number']

buffer_idx = 0
per_epoch_rewards = []
target_buffer = [ [[] for i in range(target_buffer_size)] for i in range(len(list(tf_dataset))) ]

In [6]:
kwargs

{'fully-connected_layer': 'GRU',
 'attention': True,
 'embed_dim': 128,
 'fc_dim': 64,
 'learning': 'off-policy',
 'policy': 'target',
 'use_beta': True,
 'use_buffer': True,
 'buffer_change_number': 20,
 'buffer_size': 60,
 'buffer_update': 10,
 'num_epochs': 30000,
 'lr': 0.0005,
 'num_tokens': 3718,
 'batch_size': 261}

In [8]:
# Make the directory that contains the results of training.
createFolder('./results')

'''
Teacher-Forced REINFORCE (TFR)
'''
# # Generate inital states for input, hidden, and concat state in Encoder and Decoder.
# ## --- (1) Define Encoder that embeds food sequences
# encoder = Encoder(len(food_dict), BATCH_SIZE, **kwargs)
# init_input = np.zeros([BATCH_SIZE, 1])
# init_hidden = encoder.initialize_hidden_state()
# init_output, _ = encoder(init_input, init_hidden)

# ## --- (2) Define Decoder that predicts food sequences
# decoder = Decoder(len(food_dict), **kwargs)
# decoder(init_input, init_hidden, init_output)

## --- (3) Define save_dir which represents the directory where Checkpoint is stored. The directory name consists of the parameters that controls the training of model.
root_dir = './training_log/'
save_dir = createDir(root_dir, kwargs)

## --- (4) Check and save the parameters.
print(kwargs)
saveParams(save_dir + 'params', kwargs, food_dict, nutrient_data, incidence_data.numpy())
## --- (5) Define Checkpoint object
# Define checkpoint_prefix which is the prefix part of save_dir.
checkpoint_prefix = os.path.join(save_dir + '/checkpoints', "ckpt")

## --- (6) Define Generator object
diet_generator = Sequence_Generator(food_dict, nutrient_data, incidence_data, candidate_data, **kwargs)


# Define checkpoint object in the variable 'checkpoint'.
# checkpoint = tf.train.Checkpoint(encoder = encoder, decoder = decoder, kwargs = kwargs)
checkpoint = tf.train.Checkpoint(generator = diet_generator, params = kwargs)
start = time.time() # start time

You have ./results directory already
./training_log/with_attention/GRU/
You have ./training_log/with_attention/GRU/ directory already
You have ./training_log/with_attention/GRU//checkpoints directory already
You have ./training_log/with_attention/GRU//params directory already
{'fully-connected_layer': 'GRU', 'attention': True, 'embed_dim': 128, 'fc_dim': 64, 'learning': 'off-policy', 'policy': 'target', 'use_beta': True, 'use_buffer': True, 'buffer_change_number': 20, 'buffer_size': 60, 'buffer_update': 10, 'num_epochs': 30000, 'lr': 0.0005, 'num_tokens': 3718, 'batch_size': 261}

In [9]:
import time
from tqdm import tqdm
import warnings
warnings.filterwarnings(action='ignore')

In [10]:
for epoch in tqdm(range(num_epochs)):

    # Initialize total cumulative loss
    full_batch_loss = 0

    # Initialize per batch mean reward.
    mean_rewards_per_batch = np.empty((0, 1))

    # Initialize the batch number.
    batch_num = 0

    # Do training
    for i in range(len(list(tf_dataset_update))):

        # Define i-th batch of original and (potential) update dataset.
        x = list(tf_dataset)[i]
        x_update = list(tf_dataset_update)[i]

        # Initialize (diet) sequences at every batch
        ## full_seq_len is the length of full sequence.
        full_seq_len = x.shape[1]
        real_seqs_all = np.empty((0, full_seq_len))
        pred_seqs_all = np.empty((0, full_seq_len))

        # Train Teacher-Forced REINFORCe (TFR)
        real_seqs, batch_loss, pred_seqs, _, _, synthetic_target, _ = diet_generator.train(x, x_update)
        real_seqs_all = np.append(real_seqs_all, real_seqs, axis = 0)  # stack real diet sequences from each batch
        pred_seqs_all = np.append(pred_seqs_all, pred_seqs, axis = 0)  # stack synthetic diet sequences generated based on each batch
        full_batch_loss += batch_loss

        # Fill it target_buffer with synthetic target at every batch and buffer according to batch_num and buffer_idx.
        target_buffer[batch_num][buffer_idx] = synthetic_target

        # Update batch_num
        batch_num += 1

        # (Full batch) Store nutrition scores and rewards of synthetic diets generated at each batch.
        scores = get_score_pandas(pred_seqs_all, food_dict, nutrient_data)
        rewards = np.apply_along_axis(get_reward_ver2, arr = scores, axis = 1, done = 0)[:, 0]

        # (Batch) Store nutrition scores and rewards of synthetic diets generated at each batch.
        # mean_rewards = np.mean(rewards)
        # mean_rewards_per_batch = np.append(mean_rewards_per_batch, mean_rewards)
    
    # Reset the value of buffer_idx as 0 when the buffer_idx gets eqaul to target_buffer_size.
    if (buffer_idx + 1) % target_buffer_size == 0:
        buffer_idx = 0

    # Move to the next buffer by increasing 'buffer_idx'.
    else:
        buffer_idx += 1

    # Update on-training dataset using target_buffer which is composed of synthetic diets.
    tf_dataset_update  = update_dataset(epoch, batch_size, target_buffer_update, target_buffer, tf_dataset_update, x, food_dict, nutrient_data)

    # Store the checkpoint.
    #if (epoch + 1) % 100 == 0:
    #    checkpoint.save(file_prefix = checkpoint_prefix)

    # (Full batch) Define per_epoch_rewards variable using rewards_matrix function.
    per_epoch_rewards = rewards_matrix(epoch, rewards)

    # (Batch) Define per_epoch_rewards variable using rewards_matrix function.
    # per_epoch_rewards = rewards_matrix(epoch, mean_rewards_per_batch)

    # Save the reward per epoch
    #reward_df = pd.DataFrame(per_epoch_rewards)
    #reward_df = reward_df.astype('float32')
    #reward_df.columns = ['epoch', 'reward', 'sample']
    #dir_file_name = save_reward_df(reward_df, "TFR", target_buffer_update, target_buffer_size, lr, num_epochs)

    # Compute loss per epoch
    epoch_loss = full_batch_loss / len(list(tf_dataset))

    if (epoch + 1) % 100 == 0:
        print('epoch : {}, epoch_loss : {}'.format(epoch, epoch_loss)) 
        print(' ')

        # 매 에포크 별 SL & RL 생성 결과 확인
        print('REAL 시퀀스 :', sequence_to_sentence(real_seqs_all, food_dict)[0])
        print('REAL 시퀀스의 영양수준:', get_reward_ver2(get_score_vector(real_seqs_all[0], nutrient_data), done = 0)[0])
        print(' ')
        print('생성 시퀀스 :', sequence_to_sentence(pred_seqs_all, food_dict)[0])
        print('생성 시퀀스의 영양수준:', get_reward_ver2(get_score_vector(pred_seqs_all[0], nutrient_data), done = 0)[0])
        print(' ')

        # Calculate the (nutrient) score of the real and generated diets.
        nutrient_real = np.apply_along_axis(get_score_vector, axis = 1, arr = np.array(real_seqs_all), nutrient_data = nutrient_data)
        nutrient_gen = np.apply_along_axis(get_score_vector, axis = 1, arr = pred_seqs_all, nutrient_data = nutrient_data)

        # Get reward-related information of true and generated diet sequences.
        reward_info_real = np.apply_along_axis(get_reward_ver2, axis = 1, arr = nutrient_real, done = 0)
        reward_info_gen = np.apply_along_axis(get_reward_ver2, axis = 1, arr = nutrient_gen, done = 0)

        # Calculate mean rewards of true and generated diet sequences.
        mean_true_reward = np.mean(reward_info_real[:, 0])
        mean_gen_reward = np.mean(reward_info_gen[:, 0])
        print('REAL 평균 보상 :', mean_true_reward)
        print('생성 평균 보상 :', mean_gen_reward)

        print(' ')
        print("total time :", time.time() - start)  # 현재시각 - 시작시간 = 실행 시간

  0%|          | 99/30000 [03:35<10:46:10,  1.30s/it]

epoch : 99, epoch_loss : 5.912436167399089

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', '종료', '종료', '호박감자수제비국', 'S(우유제외)토마토스파게티', '새우살미역국', 'S멜론(100g)', '매쉬드포테이토', 'B치즈스크램블에그', 'B복숭아호두스무디', 'S복숭아(백도)-60g', 'S복숭아(60g)', 'S보리차', '종료', '찹쌀현미밥(55)', 'S증편(40g)', 'S멜론(50g)', '옥수수채소튀김', '탕평채무침']
생성 시퀀스의 영양수준: 12

  0%|          | 100/30000 [03:47<37:39:49,  4.53s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 9.64367816091954

total time : 230.87926506996155

  1%|          | 199/30000 [07:17<10:11:49,  1.23s/it]

epoch : 199, epoch_loss : 5.769251081678602

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', '호박감자수제비국', '종료', 'B사과(75g)', 'S멜론(50g)', '오징어채소볶음', 'B고구마스프', '차조밥(55)', '버섯무국', '당근스틱', 'S멜론(50g)', '배추김치', 'S멜론(50g)', '연근햄버거스테이크', '고구마연근맛탕', '으깬두부채소전', '옥수수치즈전', '팽이장국', '땅콩우엉무침']
생성 시퀀스의 영양수준: 11

  1%|          | 200/30000 [07:28<35:36:00,  4.30s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 9.697318007662835

total time : 451.49357318878174

  1%|          | 299/30000 [10:51<10:05:53,  1.22s/it]

epoch : 299, epoch_loss : 5.175204806857639

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', '(저염·저당)우엉조림', 'S오이스틱', '검정콩밥(63)', 'B떠먹는요구르트(100ml)', 'S둥글레차', 'S매실젤리', 'S오미자차', '견과류고구마범벅', '간장닭강정', '열무물김치', 'B사과(35g)', 'B우엉채소볶음밥', '으깬두부채소전', '모듬과일샐러드', '새우카레볶음밥', 'B(우유제외)새우크림소스볶음', 'S사과(100g)', '종료']
생성 시퀀스의 영양수준: 12

  1%|          | 300/30000 [11:03<36:12:49,  4.39s/it]

REAL 평균 보상 : 13.67816091954023
생성 평균 보상 : 9.647509578544062

total time : 666.4877989292145

  1%|▏         | 399/30000 [14:28<10:18:12,  1.25s/it]

epoch : 399, epoch_loss : 4.62004894680447

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', '소고기양배추국', 'S둥글레차', 'S복숭아(60g)', '찹쌀밥(40)', 'S청포도(100g)', 'B(우유제외)수제바나나두유', '동태살무국', '온두부찜', '유부쑥갓맑은국', 'B고구마쉐이크', '비트초절이', 'S멜론(50g)', '새우크림스파게티', '(소고기제외)당면양배추국', '두부채소굴소스볶음', '양배추낙지볶음', '율무밥(63)', 'S보리차']
생성 시퀀스의 영양수준: 11

  1%|▏         | 400/30000 [14:40<36:32:19,  4.44s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 9.988505747126437

total time : 883.4898760318756

  2%|▏         | 499/30000 [18:08<10:07:07,  1.23s/it]

epoch : 499, epoch_loss : 3.7989014519585504

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B옥수수타락죽', 'S복숭아(천도)-60g', 'B배(50g)', '밤찹쌀팥밥(63)', 'S복숭아(백도)-60g', '찰현미밥(55)', '수수밥(63)', '당근스틱', '쌈채소', '비트초절이', 'S(우유제외)토마토스파게티', '감자당근채볶음', '검정콩밥(55)', 'B수제바나나우유', '매콤오징어볶음', 'B수제바나나우유', '단배추물김치', '종료']
생성 시퀀스의 영양수준: 10

  2%|▏         | 500/30000 [18:19<34:12:29,  4.17s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 10.099616858237548

total time : 1102.841603755951

  2%|▏         | 599/30000 [21:41<10:01:11,  1.23s/it]

epoch : 599, epoch_loss : 3.127452638414171

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B우유(100ml)', 'S사과(50g)', 'B사과(35g)', 'S복숭아(황도)-80g', 'S복숭아(60g)', '쌀밥(63)', '밤콩밥(55)', '라조기', '새우살호박볶음', '나박김치', '종료', 'B복숭아호두스무디', '새우크림스파게티', '팽이장국', '닭살간장조림', '무사과무침', '열무물김치', '종료']
생성 시퀀스의 영양수준: 12

  2%|▏         | 600/30000 [21:53<36:11:34,  4.43s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 10.440613026819923

total time : 1315.9069187641144

  2%|▏         | 699/30000 [25:26<10:47:40,  1.33s/it]

epoch : 699, epoch_loss : 2.5442801581488714

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B단호박떡케익', 'B요구르트', 'B사과(75g)', 'S사과(35g)', 'S오미자아이스크림', '찰현미밥(55)', '감자호박국', '두부톳무침', '마카로니채소샐러드(토마토소스)', '나박김치', '종료', 'S보리차', '김치햄볶음밥', '동태맑은국', '건파래자반', '도토리묵간장무침', '열무물김치', '종료']
생성 시퀀스의 영양수준: 9

  2%|▏         | 700/30000 [25:38<37:16:31,  4.58s/it]

REAL 평균 보상 : 13.720306513409962
생성 평균 보상 : 10.302681992337165

total time : 1541.8110625743866

  3%|▎         | 799/30000 [29:15<11:34:21,  1.43s/it]

epoch : 799, epoch_loss : 2.1245174407958984

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B단호박스프', '깍두기', 'B자두(50g)', 'S멜론(50g)', '우엉소고기볶음밥', '소고기볶음밥', '맑은바지락탕', '오징어불고기', '호박고지나물', '깍두기', 'S크림떡볶이', 'S둥글레차', '찹쌀보리밥(55)', '애호박맑은국', '소고기양배추조림', '닭다리살튀김', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

  3%|▎         | 800/30000 [29:28<39:57:58,  4.93s/it]

REAL 평균 보상 : 13.735632183908047
생성 평균 보상 : 10.490421455938698

total time : 1771.7176225185394

  3%|▎         | 899/30000 [33:20<10:27:00,  1.29s/it]

epoch : 899, epoch_loss : 1.8332845899793837

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B단호박스프', 'B복숭아호두스무디', 'B사과(75g)', 'S복숭아(황도)-80g', 'S복숭아(천도)-80g', '팥밥(63)', '당근황태국', '북어채소찜', '매쉬드포테이토', '배추김치', '종료', '종료', '밤찹쌀팥밥(63)', '맑은바지락탕', '소고기양배추조림', '오징어채무침', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

  3%|▎         | 900/30000 [33:32<36:44:29,  4.55s/it]

REAL 평균 보상 : 13.720306513409962
생성 평균 보상 : 10.727969348659004

total time : 2015.3641092777252

  3%|▎         | 999/30000 [37:05<10:40:11,  1.32s/it]

epoch : 999, epoch_loss : 1.584483676486545

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B단호박크림스프', 'B검은깨두유(200ml)', 'B자두(50g)', 'S복숭아(황도)-80g', 'S참외(50g)', '밤밥(55)', '애호박맑은국', '북어채소찜', '건취나물간장볶음', '나박김치', '종료', 'S보리차', '찹쌀보리밥(55)', '도라지무침', '소고기양배추조림', '오징어채무침', '석박지', '종료']
생성 시퀀스의 영양수준: 11

  3%|▎         | 1000/30000 [37:18<38:04:52,  4.73s/it]

REAL 평균 보상 : 13.67432950191571
생성 평균 보상 : 10.662835249042146

total time : 2241.4946348667145

  4%|▎         | 1099/30000 [40:53<10:19:35,  1.29s/it]

epoch : 1099, epoch_loss : 1.4097797605726454

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B크로와상', '배추김치', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '얼갈이맑은국', '북어채소찜', '건새우애호박볶음', '열무물김치', '종료', 'S떠먹는요구르트(100ml)', '찹쌀밥(40)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

  4%|▎         | 1100/30000 [41:04<34:24:37,  4.29s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 11.026819923371647

total time : 2467.77547621727

  4%|▍         | 1199/30000 [44:28<10:17:02,  1.29s/it]

epoch : 1199, epoch_loss : 1.2072568469577365

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B단호박꿀찜', 'B요구르트', 'B사과(75g)', '비트초절이', 'S복숭아(천도)-80g', '찹쌀보리밥(55)', '애호박맑은국', '북어채소찜', '애호박건새우볶음', '나박김치', '종료', 'S보리차', '참나물유부초밥', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

  4%|▍         | 1200/30000 [44:40<34:21:36,  4.30s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 10.735632183908047

total time : 2683.204443216324

  4%|▍         | 1299/30000 [48:06<10:10:53,  1.28s/it]

epoch : 1299, epoch_loss : 1.1740429136488173

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B참외샐러드', 'S복숭아(천도)-60g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '소고기곤약조림', '건새우애호박볶음', '비트초절이', '종료', 'S보리차', '보리밥(55)', '맑은바지락탕', '소고기양배추조림', '오징어채소볶음', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

  4%|▍         | 1300/30000 [48:17<35:02:53,  4.40s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 10.82375478927203

total time : 2900.7968513965607

  5%|▍         | 1399/30000 [51:50<10:14:36,  1.29s/it]

epoch : 1399, epoch_loss : 1.0180549621582031

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B새우크림소스볶음', '열무물김치', 'B사과(75g)', 'S복숭아(백도)-60g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '나박김치', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '밤찹쌀팥밥(63)', '연두부된장찌개', '소고기양배추조림', '파래자반', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

  5%|▍         | 1499/30000 [55:30<10:03:04,  1.27s/it]

REAL 평균 보상 : 13.68199233716475
생성 평균 보상 : 10.977011494252874

total time : 3124.7829065322876
epoch : 1499, epoch_loss : 0.9573319753011068

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B고구마스프', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '나박김치', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '보리밥(55)', '애호박맑은국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

  5%|▌         | 1500/30000 [55:41<33:47:40,  4.27s/it]

REAL 평균 보상 : 13.670498084291188
생성 평균 보상 : 11.118773946360154

total time : 3344.46737074852

  5%|▌         | 1599/30000 [59:08<9:56:48,  1.26s/it]

epoch : 1599, epoch_loss : 0.8421319325764974

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B밤설기(40g)', '깍두기', 'B사과(75g)', 'S사과(100g)', 'S복숭아(천도)-80g', '참나물유부초밥', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '얼갈이배추김치', 'S절편', 'S보리차', '율무밥(55)', '애호박맑은국', '소고기양배추조림', '맛살미역줄기볶음', '배추김치', '종료']
생성 시퀀스의 영양수준: 8

  5%|▌         | 1600/30000 [59:19<34:59:45,  4.44s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 11.042145593869732

total time : 3562.7732169628143

  6%|▌         | 1699/30000 [1:02:46<9:59:53,  1.27s/it]

epoch : 1699, epoch_loss : 0.7731131977505155

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B새우크림소스볶음', 'B고구마쉐이크', 'B자두(50g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '나박김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 8

  6%|▌         | 1700/30000 [1:02:57<33:42:42,  4.29s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 11.130268199233717

total time : 3780.8008143901825

  6%|▌         | 1799/30000 [1:06:24<10:24:29,  1.33s/it]

epoch : 1799, epoch_loss : 0.7376445664299859

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B새우크림소스볶음', 'B고구마쉐이크', 'B사과(75g)', 'S블루베리고구마샐러드', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '단배추물김치', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

  6%|▋         | 1899/30000 [1:10:01<9:50:30,  1.26s/it]

REAL 평균 보상 : 13.71647509578544
생성 평균 보상 : 11.25287356321839

total time : 3998.3373832702637
epoch : 1899, epoch_loss : 0.6849328676859537

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '매쉬드포테이토', '얼갈이배추김치', 'S크림떡볶이', 'S떠먹는요구르트(100ml)', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

  6%|▋         | 1900/30000 [1:10:12<33:01:37,  4.23s/it]

REAL 평균 보상 : 13.71647509578544
생성 평균 보상 : 11.210727969348659

total time : 4215.308125257492

  7%|▋         | 1999/30000 [1:13:37<9:46:54,  1.26s/it]

epoch : 1999, epoch_loss : 0.669715510474311

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '동초무침', '나박김치', 'S크림떡볶이', 'S보리차', '옥수수밥(63)', '연두부된장찌개', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

  7%|▋         | 2000/30000 [1:13:48<32:40:04,  4.20s/it]

REAL 평균 보상 : 13.701149425287356
생성 평균 보상 : 11.333333333333334

total time : 4431.781695842743

  7%|▋         | 2099/30000 [1:17:12<9:41:44,  1.25s/it]

epoch : 2099, epoch_loss : 0.616275946299235

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B치즈스틱', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '얼갈이배추김치', 'S멸치주먹밥', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

  7%|▋         | 2100/30000 [1:17:23<34:22:32,  4.44s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 11.28735632183908

total time : 4646.764634132385

  7%|▋         | 2199/30000 [1:20:47<9:41:14,  1.25s/it]

epoch : 2199, epoch_loss : 0.5901136928134494

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B단호박스프', 'B복숭아호두스무디', 'B사과(75g)', 'S블루베리고구마샐러드', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '콜라비나박김치', 'S으깬견과류고구마샐러드(요거트)', '밤찹쌀팥밥(55)', '팥밥(63)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

  8%|▊         | 2299/30000 [1:24:23<9:53:37,  1.29s/it]

REAL 평균 보상 : 13.701149425287356
생성 평균 보상 : 11.298850574712644

total time : 4861.099173545837
epoch : 2299, epoch_loss : 0.5232574674818251

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B크로와상', 'B고구마쉐이크', 'B복숭아(천도)-80g', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '소고기곤약조림', '건새우애호박볶음', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

  8%|▊         | 2300/30000 [1:24:34<32:56:56,  4.28s/it]

REAL 평균 보상 : 13.697318007662835
생성 평균 보상 : 11.360153256704981

total time : 5077.604544639587

  8%|▊         | 2399/30000 [1:27:59<9:38:36,  1.26s/it]

epoch : 2399, epoch_loss : 0.5242193010118272

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B감자죽', 'B고구마쉐이크', 'B자두(50g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '오징어불고기', '건새우애호박볶음', '깻잎김치', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

  8%|▊         | 2400/30000 [1:28:10<32:12:47,  4.20s/it]

REAL 평균 보상 : 13.689655172413794
생성 평균 보상 : 11.448275862068966

total time : 5293.135860204697

  8%|▊         | 2499/30000 [1:31:34<9:56:59,  1.30s/it]

epoch : 2499, epoch_loss : 0.5058402485317655

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B자두(50g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

  8%|▊         | 2500/30000 [1:31:45<32:15:56,  4.22s/it]

REAL 평균 보상 : 13.71647509578544
생성 평균 보상 : 11.647509578544062

total time : 5508.646433353424

  9%|▊         | 2599/30000 [1:35:10<9:39:22,  1.27s/it]

epoch : 2599, epoch_loss : 0.4822663731045193

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크림떡볶이', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

  9%|▊         | 2600/30000 [1:35:22<33:21:32,  4.38s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 11.432950191570882

total time : 5725.031964302063

  9%|▉         | 2700/30000 [1:38:57<32:00:10,  4.22s/it]

epoch : 2699, epoch_loss : 0.41259487469991046

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박나물', '배추김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '팽이버섯나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 13

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '밤밥(55)', '맑은바지락탕', '소고기곤약조림', '마카로니채소샐러드(토마토소스)', '배추김치', 'S으깬견과류고구마샐러드(요거트)', 'S검은깨두유(100ml)', '소고기볶음밥', '맑은바지락탕', '소고기양배추조림', '표고버섯당근볶음', '배추김치', '종료']
생성 시퀀스의 영양수준: 14

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 11.781609195402298

total time : 5940.570166826248

  9%|▉         | 2799/30000 [1:42:21<9:59:29,  1.32s/it]

epoch : 2799, epoch_loss : 0.4127817683749729

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B(우유제외)수제바나나두유', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

  9%|▉         | 2800/30000 [1:42:33<32:35:03,  4.31s/it]

REAL 평균 보상 : 13.697318007662835
생성 평균 보상 : 11.839080459770114

total time : 6155.9623346328735

 10%|▉         | 2899/30000 [1:45:57<9:39:16,  1.28s/it]

epoch : 2899, epoch_loss : 0.37971703211466473

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', 'B삶은감자', '건새우애호박볶음', '나박김치', 'S크림떡볶이', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 10%|▉         | 2900/30000 [1:46:08<31:58:49,  4.25s/it]

REAL 평균 보상 : 13.693486590038313
생성 평균 보상 : 11.727969348659004

total time : 6371.805865764618

 10%|▉         | 2999/30000 [1:49:33<9:28:48,  1.26s/it]

epoch : 2999, epoch_loss : 0.3935549789004856

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B크로와상', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '찹쌀보리밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '맑은장국', '종료']
생성 시퀀스의 영양수준: 12

 10%|█         | 3000/30000 [1:49:45<31:47:20,  4.24s/it]

REAL 평균 보상 : 13.720306513409962
생성 평균 보상 : 11.773946360153257

total time : 6588.019474983215

 10%|█         | 3099/30000 [1:53:09<9:43:25,  1.30s/it]

epoch : 3099, epoch_loss : 0.33623907301161027

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'S둥글레차', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '(우유제외)닭가슴살버터구이', '매쉬드포테이토', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 11%|█         | 3199/30000 [1:56:46<9:37:53,  1.29s/it]

REAL 평균 보상 : 13.685823754789272
생성 평균 보상 : 11.862068965517242

total time : 6804.318101644516
epoch : 3199, epoch_loss : 0.3115815321604411

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '열무물김치', '종료']
생성 시퀀스의 영양수준: 10

 11%|█         | 3200/30000 [1:56:57<31:21:30,  4.21s/it]

REAL 평균 보상 : 13.704980842911878
생성 평균 보상 : 11.934865900383143

total time : 7020.493082523346

 11%|█         | 3299/30000 [2:00:22<9:43:58,  1.31s/it]

epoch : 3299, epoch_loss : 0.3092447386847602

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B치즈스틱', 'B복숭아호두스무디', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S멸치주먹밥', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 11%|█         | 3300/30000 [2:00:33<31:37:31,  4.26s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 11.808429118773946

total time : 7236.6576628685

 11%|█▏        | 3399/30000 [2:03:58<9:24:26,  1.27s/it]

epoch : 3399, epoch_loss : 0.34943244192335343

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 11%|█▏        | 3400/30000 [2:04:09<31:10:41,  4.22s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 12.003831417624522

total time : 7452.764863014221

 12%|█▏        | 3499/30000 [2:07:34<9:34:26,  1.30s/it]

epoch : 3499, epoch_loss : 0.2843139171600342

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 12%|█▏        | 3500/30000 [2:07:45<31:12:50,  4.24s/it]

REAL 평균 보상 : 13.701149425287356
생성 평균 보상 : 12.091954022988507

total time : 7668.768892049789

 12%|█▏        | 3599/30000 [2:11:10<9:15:09,  1.26s/it]

epoch : 3599, epoch_loss : 0.3000734912024604

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 12%|█▏        | 3699/30000 [2:14:46<9:14:35,  1.27s/it]

REAL 평균 보상 : 13.720306513409962
생성 평균 보상 : 12.172413793103448

total time : 7884.924434185028
epoch : 3699, epoch_loss : 0.32951898045010036

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 12%|█▏        | 3700/30000 [2:14:57<30:43:03,  4.20s/it]

REAL 평균 보상 : 13.68199233716475
생성 평균 보상 : 12.210727969348659

total time : 8100.385176897049

 13%|█▎        | 3799/30000 [2:18:23<9:32:42,  1.31s/it]

epoch : 3799, epoch_loss : 0.40872399012247723

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 13%|█▎        | 3800/30000 [2:18:34<31:01:23,  4.26s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 12.015325670498084

total time : 8317.369965553284

 13%|█▎        | 3899/30000 [2:21:59<9:10:51,  1.27s/it]

epoch : 3899, epoch_loss : 0.29046760665045845

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 13%|█▎        | 3900/30000 [2:22:10<30:46:50,  4.25s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 12.245210727969349

total time : 8533.438814640045

 13%|█▎        | 3999/30000 [2:25:36<9:16:48,  1.28s/it]

epoch : 3999, epoch_loss : 0.29321471850077313

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 13%|█▎        | 4000/30000 [2:25:47<30:27:48,  4.22s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 12.298850574712644

total time : 8750.742291688919

 14%|█▎        | 4099/30000 [2:29:12<9:04:21,  1.26s/it]

epoch : 4099, epoch_loss : 0.29809533225165474

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 14%|█▎        | 4100/30000 [2:29:24<31:20:24,  4.36s/it]

REAL 평균 보상 : 13.727969348659004
생성 평균 보상 : 12.563218390804598

total time : 8967.389546394348

 14%|█▍        | 4199/30000 [2:32:49<9:04:20,  1.27s/it]

epoch : 4199, epoch_loss : 0.2763960626390245

REAL 시퀀스 : ['시작', 'B소고기브로콜리죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '숙주맑은국', '북어채소찜', '애호박새우젓볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 13

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '맑은바지락탕', '북어채소찜', '과일샐러드(요거트드레싱)', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 14%|█▍        | 4200/30000 [2:33:00<31:00:54,  4.33s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 12.306513409961687

total time : 9183.81915974617

 14%|█▍        | 4299/30000 [2:36:26<9:35:42,  1.34s/it]

epoch : 4299, epoch_loss : 0.27984923786587185

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '소고기볶음밥', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 8

 14%|█▍        | 4300/30000 [2:36:37<30:17:24,  4.24s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 12.164750957854405

total time : 9400.043771505356

 15%|█▍        | 4399/30000 [2:40:02<9:06:47,  1.28s/it]

epoch : 4399, epoch_loss : 0.22635036044650608

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S방울토마토(70g)', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '크래미채소볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '무채양파국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '무채양파국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 15%|█▍        | 4400/30000 [2:40:13<30:01:56,  4.22s/it]

REAL 평균 보상 : 13.71264367816092
생성 평균 보상 : 12.559386973180077

total time : 9616.298350334167

 15%|█▍        | 4499/30000 [2:43:39<9:01:06,  1.27s/it]

epoch : 4499, epoch_loss : 0.24004679256015354

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S멸치주먹밥', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 15%|█▌        | 4500/30000 [2:43:51<29:55:48,  4.23s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 12.521072796934867

total time : 9833.974660396576

 15%|█▌        | 4600/30000 [2:47:27<31:11:18,  4.42s/it]

epoch : 4599, epoch_loss : 0.2446106274922689

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 12.67816091954023

total time : 10050.447377681732

 16%|█▌        | 4699/30000 [2:50:52<8:54:31,  1.27s/it]

epoch : 4699, epoch_loss : 0.2055793735716078

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 16%|█▌        | 4700/30000 [2:51:03<29:42:07,  4.23s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 12.597701149425287

total time : 10266.233716249466

 16%|█▌        | 4799/30000 [2:54:29<8:54:32,  1.27s/it]

epoch : 4799, epoch_loss : 0.2395891613430447

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '수수밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 16%|█▌        | 4800/30000 [2:54:40<29:39:52,  4.24s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 12.808429118773946

total time : 10483.24650478363

 16%|█▋        | 4899/30000 [2:58:04<8:58:08,  1.29s/it]

epoch : 4899, epoch_loss : 0.22222558657328287

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 16%|█▋        | 4900/30000 [2:58:16<29:55:47,  4.29s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 12.697318007662835

total time : 10699.150530576706

 17%|█▋        | 4999/30000 [3:01:41<8:55:26,  1.28s/it]

epoch : 4999, epoch_loss : 0.22767154375712076

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S모닝빵', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 17%|█▋        | 5000/30000 [3:01:52<29:31:16,  4.25s/it]

REAL 평균 보상 : 13.727969348659004
생성 평균 보상 : 12.628352490421456

total time : 10915.726546525955

 17%|█▋        | 5099/30000 [3:05:18<9:50:44,  1.42s/it]

epoch : 5099, epoch_loss : 0.24542072084214953

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', '깍두기', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 17%|█▋        | 5100/30000 [3:05:30<30:16:10,  4.38s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 12.620689655172415

total time : 11132.942081928253

 17%|█▋        | 5199/30000 [3:08:55<8:54:56,  1.29s/it]

epoch : 5199, epoch_loss : 0.1927708519829644

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 18%|█▊        | 5299/30000 [3:12:32<8:44:12,  1.27s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 12.701149425287356

total time : 11349.684094429016
epoch : 5299, epoch_loss : 0.16583633422851562

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 18%|█▊        | 5300/30000 [3:12:44<29:08:51,  4.25s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 12.842911877394636

total time : 11566.937678575516

 18%|█▊        | 5399/30000 [3:16:09<8:40:20,  1.27s/it]

epoch : 5399, epoch_loss : 0.20113280084398058

REAL 시퀀스 : ['시작', 'B소고기브로콜리죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '배추김치', 'S크로와상', 'S매실차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B새우채소죽', 'B고구마쉐이크', 'S멸치주먹밥', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '배추김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 18%|█▊        | 5400/30000 [3:16:21<30:14:26,  4.43s/it]

REAL 평균 보상 : 13.71647509578544
생성 평균 보상 : 12.885057471264368

total time : 11784.187540054321

 18%|█▊        | 5499/30000 [3:19:46<8:43:17,  1.28s/it]

epoch : 5499, epoch_loss : 0.19270927376217312

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '열무물김치', 'S크로와상', 'S보리차', '율무밥(55)', '버섯무국', '소고기양배추조림', '깻잎나물', '깍두기', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '배추김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 18%|█▊        | 5500/30000 [3:19:57<28:48:22,  4.23s/it]

REAL 평균 보상 : 13.835249042145595
생성 평균 보상 : 13.022988505747126

total time : 12000.836303949356

 19%|█▊        | 5599/30000 [3:23:46<10:11:52,  1.50s/it]

epoch : 5599, epoch_loss : 0.1544155412250095

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '배추김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '배추된장무침', '석박지', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '배추김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 19%|█▊        | 5600/30000 [3:23:59<33:18:58,  4.92s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 12.946360153256705

total time : 12241.97402381897

 19%|█▉        | 5699/30000 [3:27:33<8:56:59,  1.33s/it]

epoch : 5699, epoch_loss : 0.1804424656762017

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 19%|█▉        | 5700/30000 [3:27:44<29:58:20,  4.44s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.007662835249041

total time : 12467.690793275833

 19%|█▉        | 5799/30000 [3:31:16<8:52:11,  1.32s/it]

epoch : 5799, epoch_loss : 0.19148630566067165

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기채소죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 19%|█▉        | 5800/30000 [3:31:28<30:17:02,  4.51s/it]

REAL 평균 보상 : 13.71647509578544
생성 평균 보상 : 12.904214559386974

total time : 12690.902806282043

 20%|█▉        | 5899/30000 [3:35:27<11:14:32,  1.68s/it]

epoch : 5899, epoch_loss : 0.18898321522606742

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 20%|█▉        | 5900/30000 [3:35:41<36:54:42,  5.51s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.045977011494253

total time : 12944.512212753296

 20%|█▉        | 5999/30000 [3:39:25<9:10:15,  1.38s/it]

epoch : 5999, epoch_loss : 0.3399649461110433

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B멜론(50g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '석박지', '종료']
생성 시퀀스의 영양수준: 10

 20%|██        | 6000/30000 [3:39:37<30:47:50,  4.62s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 12.49808429118774

total time : 13180.212576150894

 20%|██        | 6099/30000 [3:43:19<9:10:38,  1.38s/it]

epoch : 6099, epoch_loss : 0.19361386034223768

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(황도)-80g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 20%|██        | 6100/30000 [3:43:31<30:48:13,  4.64s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 13.0727969348659

total time : 13414.422840595245

 21%|██        | 6199/30000 [3:47:12<9:08:43,  1.38s/it]

epoch : 6199, epoch_loss : 0.21256413724687365

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 21%|██        | 6200/30000 [3:47:24<30:45:54,  4.65s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 12.957854406130268

total time : 13647.28513598442

 21%|██        | 6299/30000 [3:51:06<8:56:59,  1.36s/it]

epoch : 6299, epoch_loss : 0.22629144456651476

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '열무물김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기메란조림', '봄동나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 21%|██        | 6300/30000 [3:51:18<30:11:24,  4.59s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.065134099616857

total time : 13881.108299016953

 21%|██▏       | 6399/30000 [3:54:58<9:17:34,  1.42s/it]

epoch : 6399, epoch_loss : 0.20675497584872776

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 21%|██▏       | 6400/30000 [3:55:09<29:52:56,  4.56s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 13.068965517241379

total time : 14112.883880853653

 22%|██▏       | 6499/30000 [3:58:50<9:10:35,  1.41s/it]

epoch : 6499, epoch_loss : 0.16523178418477377

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '소고기볶음밥', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 8

 22%|██▏       | 6500/30000 [3:59:01<29:25:16,  4.51s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.068965517241379

total time : 14344.65587925911

 22%|██▏       | 6599/30000 [4:02:41<8:57:34,  1.38s/it]

epoch : 6599, epoch_loss : 0.1544518338309394

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 22%|██▏       | 6600/30000 [4:02:53<29:29:36,  4.54s/it]

REAL 평균 보상 : 13.727969348659004
생성 평균 보상 : 13.191570881226054

total time : 14575.917344093323

 22%|██▏       | 6699/30000 [4:06:31<8:50:04,  1.36s/it]

epoch : 6699, epoch_loss : 0.1882726483874851

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 22%|██▏       | 6700/30000 [4:06:43<29:21:37,  4.54s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 13.126436781609195

total time : 14805.980647802353

 23%|██▎       | 6799/30000 [4:10:20<8:38:33,  1.34s/it]

epoch : 6799, epoch_loss : 0.15493762493133545

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 23%|██▎       | 6800/30000 [4:10:32<29:27:18,  4.57s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.187739463601533

total time : 15035.822733402252

 23%|██▎       | 6899/30000 [4:14:10<8:45:07,  1.36s/it]

epoch : 6899, epoch_loss : 0.15418481826782227

REAL 시퀀스 : ['시작', 'B소고기주먹밥', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '조갯살된장찌개', '소고기양배추조림', '배추된장무침', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 23%|██▎       | 6900/30000 [4:14:22<29:16:02,  4.56s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.172413793103448

total time : 15265.81132888794

 23%|██▎       | 6999/30000 [4:18:00<8:42:10,  1.36s/it]

epoch : 6999, epoch_loss : 0.2055197556813558

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 23%|██▎       | 7000/30000 [4:18:12<28:38:04,  4.48s/it]

REAL 평균 보상 : 13.735632183908047
생성 평균 보상 : 13.203065134099617

total time : 15494.997381687164

 24%|██▎       | 7099/30000 [4:21:49<8:50:39,  1.39s/it]

epoch : 7099, epoch_loss : 0.16143785582648384

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B요구르트', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S검은깨두유(100ml)', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

 24%|██▎       | 7100/30000 [4:22:01<29:02:37,  4.57s/it]

REAL 평균 보상 : 13.735632183908047
생성 평균 보상 : 13.21455938697318

total time : 15724.245655536652

 24%|██▍       | 7199/30000 [4:25:40<8:36:11,  1.36s/it]

epoch : 7199, epoch_loss : 0.15364306502872044

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 24%|██▍       | 7200/30000 [4:25:52<28:43:14,  4.53s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.272030651340996

total time : 15954.975392341614

 24%|██▍       | 7299/30000 [4:29:31<8:37:51,  1.37s/it]

epoch : 7299, epoch_loss : 0.17956916491190592

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '소고기찹쌀구이', '해초볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기떡찜', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(황도)-80g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 24%|██▍       | 7300/30000 [4:29:43<28:40:16,  4.55s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.237547892720306

total time : 16185.96948814392

 25%|██▍       | 7399/30000 [4:33:21<8:46:55,  1.40s/it]

epoch : 7399, epoch_loss : 0.14874478181203207

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '수제비샐러드', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 25%|██▍       | 7400/30000 [4:33:34<29:04:11,  4.63s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 13.256704980842912

total time : 16417.001466035843

 25%|██▍       | 7499/30000 [4:37:12<8:28:27,  1.36s/it]

epoch : 7499, epoch_loss : 0.20828521251678467

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '맑은양배추국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 25%|██▌       | 7500/30000 [4:37:24<28:39:26,  4.59s/it]

REAL 평균 보상 : 13.724137931034482
생성 평균 보상 : 13.421455938697317

total time : 16647.565778255463

 25%|██▌       | 7599/30000 [4:41:02<8:21:36,  1.34s/it]

epoch : 7599, epoch_loss : 0.17607960436079237

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 25%|██▌       | 7600/30000 [4:41:13<27:52:13,  4.48s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.314176245210728

total time : 16876.85874390602

 26%|██▌       | 7699/30000 [4:44:51<8:17:51,  1.34s/it]

epoch : 7699, epoch_loss : 0.15150960286458334

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 26%|██▌       | 7700/30000 [4:45:03<28:22:07,  4.58s/it]

REAL 평균 보상 : 13.724137931034482
생성 평균 보상 : 13.264367816091953

total time : 17106.140233039856

 26%|██▌       | 7799/30000 [4:48:42<8:29:43,  1.38s/it]

epoch : 7799, epoch_loss : 0.12802610132429335

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '단호박수제비국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 26%|██▌       | 7800/30000 [4:48:53<27:42:55,  4.49s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.191570881226054

total time : 17336.718557834625

 26%|██▋       | 7899/30000 [4:52:30<8:37:23,  1.40s/it]

epoch : 7899, epoch_loss : 0.19552764627668592

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 26%|██▋       | 7900/30000 [4:52:43<28:12:22,  4.59s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 13.25287356321839

total time : 17565.925837039948

 27%|██▋       | 7999/30000 [4:56:20<8:12:38,  1.34s/it]

epoch : 7999, epoch_loss : 0.15197008185916477

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 27%|██▋       | 8000/30000 [4:56:32<27:45:25,  4.54s/it]

REAL 평균 보상 : 13.720306513409962
생성 평균 보상 : 13.310344827586206

total time : 17795.739887952805

 27%|██▋       | 8099/30000 [5:00:10<8:14:58,  1.36s/it]

epoch : 8099, epoch_loss : 0.12905683782365587

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 27%|██▋       | 8100/30000 [5:00:23<28:03:14,  4.61s/it]

REAL 평균 보상 : 13.71647509578544
생성 평균 보상 : 13.229885057471265

total time : 18025.99130797386

 27%|██▋       | 8199/30000 [5:04:01<8:28:56,  1.40s/it]

epoch : 8199, epoch_loss : 0.18313103251987034

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 27%|██▋       | 8200/30000 [5:04:13<27:40:11,  4.57s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.371647509578544

total time : 18256.759739160538

 28%|██▊       | 8299/30000 [5:07:52<8:05:32,  1.34s/it]

epoch : 8299, epoch_loss : 0.12939875655704075

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 28%|██▊       | 8300/30000 [5:08:04<27:22:09,  4.54s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 13.371647509578544

total time : 18486.94037795067

 28%|██▊       | 8399/30000 [5:11:43<7:58:41,  1.33s/it]

epoch : 8399, epoch_loss : 0.19246444437238905

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 28%|██▊       | 8400/30000 [5:11:54<26:31:13,  4.42s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.348659003831418

total time : 18717.667640924454

 28%|██▊       | 8499/30000 [5:15:34<8:24:43,  1.41s/it]

epoch : 8499, epoch_loss : 0.11186304357316759

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 28%|██▊       | 8500/30000 [5:15:46<27:09:05,  4.55s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.42911877394636

total time : 18948.916211366653

 29%|██▊       | 8599/30000 [5:19:25<8:03:55,  1.36s/it]

epoch : 8599, epoch_loss : 0.13926168282826742

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 29%|██▊       | 8600/30000 [5:19:37<27:10:23,  4.57s/it]

REAL 평균 보상 : 13.71647509578544
생성 평균 보상 : 13.421455938697317

total time : 19180.881287574768

 29%|██▉       | 8699/30000 [5:23:17<8:05:16,  1.37s/it]

epoch : 8699, epoch_loss : 0.12027397420671251

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 29%|██▉       | 8700/30000 [5:23:29<27:28:32,  4.64s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.371647509578544

total time : 19412.222454309464

 29%|██▉       | 8799/30000 [5:27:10<8:22:56,  1.42s/it]

epoch : 8799, epoch_loss : 0.1668008698357476

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 29%|██▉       | 8800/30000 [5:27:22<27:11:06,  4.62s/it]

REAL 평균 보상 : 13.816091954022989
생성 평균 보상 : 13.409961685823754

total time : 19645.0838868618

 30%|██▉       | 8899/30000 [5:31:01<8:03:38,  1.38s/it]

epoch : 8899, epoch_loss : 0.1885526047812568

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 30%|██▉       | 8900/30000 [5:31:13<26:46:04,  4.57s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 13.421455938697317

total time : 19876.123966693878

 30%|██▉       | 8999/30000 [5:34:53<8:01:56,  1.38s/it]

epoch : 8999, epoch_loss : 0.23243774308098686

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 30%|███       | 9000/30000 [5:35:05<26:40:44,  4.57s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.39463601532567

total time : 20107.926980018616

 30%|███       | 9099/30000 [5:38:44<7:58:23,  1.37s/it]

epoch : 9099, epoch_loss : 0.17158798376719156

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 30%|███       | 9100/30000 [5:38:56<26:06:52,  4.50s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.314176245210728

total time : 20339.571818113327

 31%|███       | 9200/30000 [5:42:48<26:55:04,  4.66s/it]

epoch : 9199, epoch_loss : 0.18610645665062797

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(50g)', 'S오이스틱', 'S복숭아(60g)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

REAL 평균 보상 : 13.812260536398467
생성 평균 보상 : 13.363984674329503

total time : 20571.39826154709

 31%|███       | 9299/30000 [5:46:27<7:55:13,  1.38s/it]

epoch : 9299, epoch_loss : 0.2014709711074829

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 31%|███       | 9300/30000 [5:46:39<25:53:31,  4.50s/it]

REAL 평균 보상 : 13.704980842911878
생성 평균 보상 : 13.475095785440613

total time : 20802.542055368423

 31%|███▏      | 9399/30000 [5:50:19<7:50:57,  1.37s/it]

epoch : 9399, epoch_loss : 0.13884831799401176

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 31%|███▏      | 9400/30000 [5:50:31<26:03:41,  4.55s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.42911877394636

total time : 21034.013927698135

 32%|███▏      | 9499/30000 [5:54:10<7:42:22,  1.35s/it]

epoch : 9499, epoch_loss : 0.2009093099170261

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 32%|███▏      | 9500/30000 [5:54:22<25:44:38,  4.52s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.406130268199234

total time : 21265.610456943512

 32%|███▏      | 9599/30000 [5:58:02<7:44:37,  1.37s/it]

epoch : 9599, epoch_loss : 0.15196635988023546

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 32%|███▏      | 9600/30000 [5:58:14<25:46:01,  4.55s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.42911877394636

total time : 21497.684767723083

 32%|███▏      | 9699/30000 [6:01:54<7:38:37,  1.36s/it]

epoch : 9699, epoch_loss : 0.11748062239752875

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '해초볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

 32%|███▏      | 9700/30000 [6:02:06<26:01:41,  4.62s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.448275862068966

total time : 21729.858924865723

 33%|███▎      | 9799/30000 [6:05:47<7:37:28,  1.36s/it]

epoch : 9799, epoch_loss : 0.1240379015604655

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 33%|███▎      | 9800/30000 [6:05:59<25:36:39,  4.56s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.413793103448276

total time : 21962.147312641144

 33%|███▎      | 9900/30000 [6:09:50<25:42:55,  4.61s/it]

epoch : 9899, epoch_loss : 0.1820044649971856

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

REAL 평균 보상 : 13.827586206896552
생성 평균 보상 : 13.452107279693486

total time : 22193.640895843506

 33%|███▎      | 9999/30000 [6:13:31<7:34:39,  1.36s/it]

epoch : 9999, epoch_loss : 0.12564991580115425

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 33%|███▎      | 10000/30000 [6:13:43<25:18:43,  4.56s/it]

REAL 평균 보상 : 13.724137931034482
생성 평균 보상 : 13.379310344827585

total time : 22425.969049930573

 34%|███▎      | 10099/30000 [6:17:33<7:39:05,  1.38s/it]

epoch : 10099, epoch_loss : 0.14620745182037354

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 34%|███▎      | 10100/30000 [6:17:45<25:15:22,  4.57s/it]

REAL 평균 보상 : 13.81992337164751
생성 평균 보상 : 13.478927203065133

total time : 22668.401203393936

 34%|███▍      | 10199/30000 [6:21:26<7:45:08,  1.41s/it]

epoch : 10199, epoch_loss : 0.15296876430511475

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 34%|███▍      | 10200/30000 [6:21:38<25:03:40,  4.56s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.471264367816092

total time : 22901.064890146255

 34%|███▍      | 10299/30000 [6:25:19<7:27:14,  1.36s/it]

epoch : 10299, epoch_loss : 0.18315438429514566

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '시금치맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S슈크림빵', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '양배추나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 9

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '콜라비나박김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '미역귀튀각', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 34%|███▍      | 10300/30000 [6:25:31<24:52:02,  4.54s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.39463601532567

total time : 23134.062036037445

 35%|███▍      | 10399/30000 [6:29:11<7:27:55,  1.37s/it]

epoch : 10399, epoch_loss : 0.11146306991577148

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 35%|███▍      | 10499/30000 [6:33:04<7:41:09,  1.42s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.406130268199234

total time : 23366.206254959106
epoch : 10499, epoch_loss : 0.1943272219763862

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S으깬견과류고구마샐러드(요거트)', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 35%|███▌      | 10500/30000 [6:33:16<24:45:30,  4.57s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.46360153256705

total time : 23599.436531066895

 35%|███▌      | 10599/30000 [6:36:56<7:38:38,  1.42s/it]

epoch : 10599, epoch_loss : 0.1270891163084242

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B수제바나나우유', 'B사과(75g)', 'S오이스틱', 'S복숭아(황도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크림빵', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 10

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B요구르트', 'B사과(75g)', 'S오이스틱', 'S블루베리고구마샐러드', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S식혜', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 35%|███▌      | 10600/30000 [6:37:09<25:31:27,  4.74s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.459770114942529

total time : 23832.30344581604

 36%|███▌      | 10699/30000 [6:40:49<7:20:09,  1.37s/it]

epoch : 10699, epoch_loss : 0.12237542205386692

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B수제바나나우유', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S멸치주먹밥', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 8

 36%|███▌      | 10700/30000 [6:41:01<24:42:28,  4.61s/it]

REAL 평균 보상 : 13.812260536398467
생성 평균 보상 : 13.50191570881226

total time : 24064.786906957626

 36%|███▌      | 10799/30000 [6:44:43<7:21:51,  1.38s/it]

epoch : 10799, epoch_loss : 0.18659689691331652

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B복숭아(60g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기떡찜', '깻잎나물', '열무물김치', '종료']
REAL 시퀀스의 영양수준: 9

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '닭곰탕', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '애호박맑은국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 36%|███▌      | 10800/30000 [6:44:55<24:40:56,  4.63s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 13.459770114942529

total time : 24298.380254507065

 36%|███▋      | 10899/30000 [6:48:37<7:23:50,  1.39s/it]

epoch : 10899, epoch_loss : 0.17510705524020725

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '깍두기', '종료']
생성 시퀀스의 영양수준: 11

 36%|███▋      | 10900/30000 [6:48:49<24:12:25,  4.56s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.547892720306514

total time : 24532.27264857292

 37%|███▋      | 10999/30000 [6:52:31<7:30:08,  1.42s/it]

epoch : 10999, epoch_loss : 0.14935032526652017

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 37%|███▋      | 11000/30000 [6:52:43<24:29:59,  4.64s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.455938697318008

total time : 24766.108492136

 37%|███▋      | 11099/30000 [6:56:25<7:17:37,  1.39s/it]

epoch : 11099, epoch_loss : 0.13046487172444662

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 37%|███▋      | 11100/30000 [6:56:38<24:48:00,  4.72s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.475095785440613

total time : 25001.002959012985

 37%|███▋      | 11199/30000 [7:00:21<7:19:38,  1.40s/it]

epoch : 11199, epoch_loss : 0.14754921860165066

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 37%|███▋      | 11200/30000 [7:00:34<24:29:01,  4.69s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.478927203065133

total time : 25236.938530921936

 38%|███▊      | 11299/30000 [7:04:18<7:14:40,  1.39s/it]

epoch : 11299, epoch_loss : 0.17766977681054008

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(백도)-80g', 'S복숭아(천도)-80g', '율무밥(55)', '시금치맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S단호박설기', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 8

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 38%|███▊      | 11300/30000 [7:04:30<24:22:45,  4.69s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.582375478927203

total time : 25473.588230371475

 38%|███▊      | 11399/30000 [7:08:14<7:11:48,  1.39s/it]

epoch : 11399, epoch_loss : 0.09622835450702244

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 38%|███▊      | 11400/30000 [7:08:27<24:29:59,  4.74s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.574712643678161

total time : 25710.150506973267

 38%|███▊      | 11499/30000 [7:12:10<7:21:19,  1.43s/it]

epoch : 11499, epoch_loss : 0.10421210527420044

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 38%|███▊      | 11500/30000 [7:12:23<23:52:47,  4.65s/it]

REAL 평균 보상 : 13.82375478927203
생성 평균 보상 : 13.521072796934867

total time : 25945.905107736588

 39%|███▊      | 11599/30000 [7:16:07<7:03:15,  1.38s/it]

epoch : 11599, epoch_loss : 0.1114757325914171

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 39%|███▊      | 11600/30000 [7:16:19<24:10:49,  4.73s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.547892720306514

total time : 26182.73865199089

 39%|███▉      | 11699/30000 [7:20:03<7:17:13,  1.43s/it]

epoch : 11699, epoch_loss : 0.1506874958674113

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 39%|███▉      | 11700/30000 [7:20:15<23:57:31,  4.71s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.613026819923371

total time : 26418.87290239334

 39%|███▉      | 11799/30000 [7:24:01<7:19:03,  1.45s/it]

epoch : 11799, epoch_loss : 0.1286628378762139

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 39%|███▉      | 11800/30000 [7:24:13<23:12:43,  4.59s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.601532567049809

total time : 26656.53015422821

 40%|███▉      | 11899/30000 [7:27:58<7:06:59,  1.42s/it]

epoch : 11899, epoch_loss : 0.12134790420532227

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B(우유제외)고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '파김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '오이소박이김치', '종료']
REAL 시퀀스의 영양수준: 10

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B우유(100ml)', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '열무물김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '상추오이무침', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 40%|███▉      | 11900/30000 [7:28:11<23:35:14,  4.69s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.517241379310345

total time : 26893.99161219597

 40%|███▉      | 11999/30000 [7:31:54<6:52:07,  1.37s/it]

epoch : 11999, epoch_loss : 0.17488443851470947

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 40%|████      | 12099/30000 [7:35:51<7:00:27,  1.41s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.521072796934867

total time : 27129.586675167084
epoch : 12099, epoch_loss : 0.1281537347369724

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 40%|████      | 12100/30000 [7:36:03<23:12:36,  4.67s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.53256704980843

total time : 27366.7683904171

 41%|████      | 12199/30000 [7:39:46<6:44:38,  1.36s/it]

epoch : 12199, epoch_loss : 0.17909793059031168

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 41%|████      | 12200/30000 [7:39:59<23:07:05,  4.68s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.563218390804598

total time : 27602.278215408325

 41%|████      | 12299/30000 [7:43:43<6:56:57,  1.41s/it]

epoch : 12299, epoch_loss : 0.1304688056310018

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 41%|████▏     | 12399/30000 [7:47:41<7:00:49,  1.43s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.586206896551724

total time : 27838.438084363937
epoch : 12399, epoch_loss : 0.09756143225563897

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 41%|████▏     | 12400/30000 [7:47:53<22:55:58,  4.69s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.544061302681992

total time : 28076.454349040985

 42%|████▏     | 12499/30000 [7:51:38<6:33:06,  1.35s/it]

epoch : 12499, epoch_loss : 0.13905786143408883

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', '종료', 'S보리차', '기장밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 42%|████▏     | 12500/30000 [7:51:50<21:30:08,  4.42s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.593869731800766

total time : 28312.911618947983

 42%|████▏     | 12599/30000 [7:55:34<6:50:27,  1.42s/it]

epoch : 12599, epoch_loss : 0.1328718662261963

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 42%|████▏     | 12600/30000 [7:55:46<22:05:01,  4.57s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.53639846743295

total time : 28549.648416757584

 42%|████▏     | 12699/30000 [7:59:32<6:41:26,  1.39s/it]

epoch : 12699, epoch_loss : 0.17319838205973306

REAL 시퀀스 : ['시작', 'B소고기주먹밥', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S단호박죽', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '양배추나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S모닝빵', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 42%|████▏     | 12700/30000 [7:59:44<22:17:14,  4.64s/it]

REAL 평균 보상 : 13.812260536398467
생성 평균 보상 : 13.60536398467433

total time : 28787.275400161743

 43%|████▎     | 12799/30000 [8:03:30<7:07:57,  1.49s/it]

epoch : 12799, epoch_loss : 0.10240901841057672

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 43%|████▎     | 12800/30000 [8:03:43<23:11:54,  4.86s/it]

REAL 평균 보상 : 13.812260536398467
생성 평균 보상 : 13.50191570881226

total time : 29025.957236766815

 43%|████▎     | 12899/30000 [8:07:28<6:45:42,  1.42s/it]

epoch : 12899, epoch_loss : 0.14333230919308132

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 43%|████▎     | 12900/30000 [8:07:41<22:21:45,  4.71s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.521072796934867

total time : 29264.060155153275

 43%|████▎     | 13000/30000 [8:11:39<22:02:45,  4.67s/it]

epoch : 12999, epoch_loss : 0.16292251480950248

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B호두두부쉐이크', 'B단감(50g)', 'S오이스틱', 'S복숭아(백도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', '율무밥(55)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

REAL 평균 보상 : 13.831417624521073
생성 평균 보상 : 13.409961685823754

total time : 29502.643446922302

 44%|████▎     | 13099/30000 [8:15:25<6:41:51,  1.43s/it]

epoch : 13099, epoch_loss : 0.184990922609965

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 44%|████▎     | 13100/30000 [8:15:37<22:05:43,  4.71s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.478927203065133

total time : 29740.31138253212

 44%|████▍     | 13199/30000 [8:19:24<6:26:03,  1.38s/it]

epoch : 13199, epoch_loss : 0.14049547248416477

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 44%|████▍     | 13200/30000 [8:19:36<22:04:00,  4.73s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 13.46360153256705

total time : 29979.52311897278

 44%|████▍     | 13299/30000 [8:23:24<6:53:51,  1.49s/it]

epoch : 13299, epoch_loss : 0.1715613736046685

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '유부맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 44%|████▍     | 13300/30000 [8:23:37<23:08:31,  4.99s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.509578544061302

total time : 30220.42734336853

 45%|████▍     | 13399/30000 [8:27:23<6:30:39,  1.41s/it]

epoch : 13399, epoch_loss : 0.11008381843566895

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 45%|████▍     | 13400/30000 [8:27:35<21:47:14,  4.72s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 13.475095785440613

total time : 30458.79587650299

 45%|████▍     | 13499/30000 [8:31:21<6:36:08,  1.44s/it]

epoch : 13499, epoch_loss : 0.15236544609069824

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 45%|████▌     | 13599/30000 [8:35:19<6:20:08,  1.39s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.578544061302683

total time : 30696.82233285904
epoch : 13599, epoch_loss : 0.1255398326449924

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 45%|████▌     | 13600/30000 [8:35:31<21:09:29,  4.64s/it]

REAL 평균 보상 : 13.697318007662835
생성 평균 보상 : 13.478927203065133

total time : 30934.760581493378

 46%|████▌     | 13699/30000 [8:39:17<6:26:27,  1.42s/it]

epoch : 13699, epoch_loss : 0.14782068464491102

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 46%|████▌     | 13700/30000 [8:39:29<20:52:20,  4.61s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.524904214559387

total time : 31172.78978204727

 46%|████▌     | 13799/30000 [8:43:15<6:36:41,  1.47s/it]

epoch : 13799, epoch_loss : 0.11156912644704182

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(황도)-80g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 46%|████▌     | 13800/30000 [8:43:28<21:39:01,  4.81s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.559386973180077

total time : 31411.240204811096

 46%|████▋     | 13899/30000 [8:47:14<6:24:51,  1.43s/it]

epoch : 13899, epoch_loss : 0.12055260605282253

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 46%|████▋     | 13900/30000 [8:47:27<21:16:19,  4.76s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.540229885057471

total time : 31650.25882601738

 47%|████▋     | 13999/30000 [8:51:13<6:21:47,  1.43s/it]

epoch : 13999, epoch_loss : 0.1377654340532091

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 47%|████▋     | 14000/30000 [8:51:25<21:15:15,  4.78s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.559386973180077

total time : 31888.55836391449

 47%|████▋     | 14099/30000 [8:55:12<6:28:52,  1.47s/it]

epoch : 14099, epoch_loss : 0.16946523719363743

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B치즈스틱', 'B고구마쉐이크', 'S크림떡볶이', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 47%|████▋     | 14100/30000 [8:55:25<21:39:36,  4.90s/it]

REAL 평균 보상 : 13.816091954022989
생성 평균 보상 : 13.632183908045977

total time : 32127.985737800598

 47%|████▋     | 14199/30000 [8:59:11<6:26:17,  1.47s/it]

epoch : 14199, epoch_loss : 0.11631570922003852

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 47%|████▋     | 14200/30000 [8:59:23<20:35:43,  4.69s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.517241379310345

total time : 32366.118466854095

 48%|████▊     | 14299/30000 [9:03:10<6:16:49,  1.44s/it]

epoch : 14299, epoch_loss : 0.14242551061842176

REAL 시퀀스 : ['시작', 'B소고기주먹밥', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S잔치국수', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '팽이버섯나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 10

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 48%|████▊     | 14300/30000 [9:03:22<20:28:44,  4.70s/it]

REAL 평균 보상 : 13.835249042145595
생성 평균 보상 : 13.494252873563218

total time : 32605.431609630585

 48%|████▊     | 14399/30000 [9:07:08<5:53:56,  1.36s/it]

epoch : 14399, epoch_loss : 0.10209000110626221

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 48%|████▊     | 14400/30000 [9:07:21<20:55:31,  4.83s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.567049808429118

total time : 32844.025131464005

 48%|████▊     | 14499/30000 [9:11:08<6:01:36,  1.40s/it]

epoch : 14499, epoch_loss : 0.13495798905690512

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B포도(100g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 48%|████▊     | 14500/30000 [9:11:20<20:04:41,  4.66s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.586206896551724

total time : 33083.56106495857

 49%|████▊     | 14599/30000 [9:15:06<6:18:03,  1.47s/it]

epoch : 14599, epoch_loss : 0.10968140761057536

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 49%|████▊     | 14600/30000 [9:15:19<20:16:32,  4.74s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.578544061302683

total time : 33322.12468075752

 49%|████▉     | 14699/30000 [9:19:06<6:00:33,  1.41s/it]

epoch : 14699, epoch_loss : 0.10084988673528035

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 49%|████▉     | 14700/30000 [9:19:18<20:04:18,  4.72s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.555555555555555

total time : 33561.35862851143

 49%|████▉     | 14799/30000 [9:23:05<5:57:06,  1.41s/it]

epoch : 14799, epoch_loss : 0.12520031134287515

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 49%|████▉     | 14800/30000 [9:23:18<19:45:44,  4.68s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.60536398467433

total time : 33801.17791676521

 50%|████▉     | 14899/30000 [9:27:07<5:55:09,  1.41s/it]

epoch : 14899, epoch_loss : 0.16869676113128662

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 50%|████▉     | 14900/30000 [9:27:19<19:55:14,  4.75s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.670498084291188

total time : 34042.68248319626

 50%|████▉     | 14999/30000 [9:31:06<5:59:08,  1.44s/it]

epoch : 14999, epoch_loss : 0.10846024751663208

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 50%|█████     | 15000/30000 [9:31:19<19:46:59,  4.75s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.574712643678161

total time : 34282.16923928261

 50%|█████     | 15099/30000 [9:35:06<5:54:18,  1.43s/it]

epoch : 15099, epoch_loss : 0.1396885183122423

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 50%|█████     | 15100/30000 [9:35:18<19:51:47,  4.80s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.540229885057471

total time : 34521.74983668327

 51%|█████     | 15199/30000 [9:39:07<6:04:13,  1.48s/it]

epoch : 15199, epoch_loss : 0.16765830251905653

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 51%|█████     | 15200/30000 [9:39:19<19:45:39,  4.81s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 13.578544061302683

total time : 34762.66262602806

 51%|█████     | 15299/30000 [9:43:07<5:44:08,  1.40s/it]

epoch : 15299, epoch_loss : 0.12187525961134169

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 51%|█████     | 15300/30000 [9:43:20<19:24:01,  4.75s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.597701149425287

total time : 35003.092928647995

 51%|█████▏    | 15399/30000 [9:47:09<5:41:59,  1.41s/it]

epoch : 15399, epoch_loss : 0.17020603020985922

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 51%|█████▏    | 15400/30000 [9:47:21<19:06:16,  4.71s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.440613026819923

total time : 35244.61381292343

 52%|█████▏    | 15499/30000 [9:51:10<5:50:25,  1.45s/it]

epoch : 15499, epoch_loss : 0.15093334515889487

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 52%|█████▏    | 15599/30000 [9:55:11<5:42:16,  1.43s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.613026819923371

total time : 35486.23428726196
epoch : 15599, epoch_loss : 0.13296000162760416

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 52%|█████▏    | 15600/30000 [9:55:24<19:09:44,  4.79s/it]

REAL 평균 보상 : 13.812260536398467
생성 평균 보상 : 13.574712643678161

total time : 35727.154571294785

 52%|█████▏    | 15699/30000 [9:59:12<5:38:49,  1.42s/it]

epoch : 15699, epoch_loss : 0.12902653217315674

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 52%|█████▏    | 15700/30000 [9:59:25<19:00:15,  4.78s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.567049808429118

total time : 35968.077718019485

 53%|█████▎    | 15799/30000 [10:03:14<5:35:30,  1.42s/it]

epoch : 15799, epoch_loss : 0.1279376745223999

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 53%|█████▎    | 15800/30000 [10:03:27<19:32:18,  4.95s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.616858237547893

total time : 36210.73798394203

 53%|█████▎    | 15899/30000 [10:07:18<5:59:31,  1.53s/it]

epoch : 15899, epoch_loss : 0.18886886702643502

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '동태살국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 53%|█████▎    | 15900/30000 [10:07:30<19:01:19,  4.86s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.578544061302683

total time : 36453.53712725639

 53%|█████▎    | 15999/30000 [10:11:19<5:40:54,  1.46s/it]

epoch : 15999, epoch_loss : 0.12739159001244438

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B(우유제외)바나나쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박새우젓볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기등심버섯불고기', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 53%|█████▎    | 16000/30000 [10:11:32<19:00:54,  4.89s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.632183908045977

total time : 36695.08845806122

 54%|█████▎    | 16099/30000 [10:15:21<5:31:45,  1.43s/it]

epoch : 16099, epoch_loss : 0.11707227759891087

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '양배추맑은국', '북어채소찜', '애호박볶음', '깻잎김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '열무물김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 54%|█████▎    | 16100/30000 [10:15:34<18:35:24,  4.81s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.509578544061302

total time : 36937.30769944191

 54%|█████▍    | 16199/30000 [10:19:23<5:24:56,  1.41s/it]

epoch : 16199, epoch_loss : 0.14664583735995823

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B단감(50g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박건새우볶음', '백김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박건새우볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 54%|█████▍    | 16200/30000 [10:19:36<18:32:16,  4.84s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.685823754789272

total time : 37179.19119977951

 54%|█████▍    | 16299/30000 [10:23:25<5:36:46,  1.47s/it]

epoch : 16299, epoch_loss : 0.13241313563452828

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 54%|█████▍    | 16300/30000 [10:23:38<18:58:54,  4.99s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.662835249042146

total time : 37421.70593905449

 55%|█████▍    | 16399/30000 [10:27:28<5:29:56,  1.46s/it]

epoch : 16399, epoch_loss : 0.09135063489278157

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 55%|█████▍    | 16400/30000 [10:27:40<18:20:05,  4.85s/it]

REAL 평균 보상 : 13.827586206896552
생성 평균 보상 : 13.74712643678161

total time : 37663.859098911285

 55%|█████▍    | 16499/30000 [10:31:29<5:19:47,  1.42s/it]

epoch : 16499, epoch_loss : 0.1856951978471544

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B밤설기(40g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 55%|█████▌    | 16500/30000 [10:31:41<17:48:09,  4.75s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.574712643678161

total time : 37904.64903354645

 55%|█████▌    | 16599/30000 [10:35:30<5:16:02,  1.42s/it]

epoch : 16599, epoch_loss : 0.1378173828125

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 55%|█████▌    | 16600/30000 [10:35:42<17:26:44,  4.69s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.708812260536398

total time : 38145.40583705902

 56%|█████▌    | 16699/30000 [10:39:31<5:22:50,  1.46s/it]

epoch : 16699, epoch_loss : 0.14879722065395778

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 56%|█████▌    | 16700/30000 [10:39:44<17:31:48,  4.74s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.555555555555555

total time : 38387.029682159424

 56%|█████▌    | 16799/30000 [10:43:34<5:29:28,  1.50s/it]

epoch : 16799, epoch_loss : 0.12155298391977946

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '갈치구이', '애호박새우젓볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '무채양파국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 14

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B두유(200ml)', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '브로콜리무침', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '애호박맑은국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

 56%|█████▌    | 16800/30000 [10:43:47<17:58:29,  4.90s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.597701149425287

total time : 38630.59633755684

 56%|█████▋    | 16899/30000 [10:47:37<5:14:34,  1.44s/it]

epoch : 16899, epoch_loss : 0.13758855395846897

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 56%|█████▋    | 16900/30000 [10:47:50<17:27:32,  4.80s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 13.563218390804598

total time : 38873.212934970856

 57%|█████▋    | 16999/30000 [10:51:41<5:13:45,  1.45s/it]

epoch : 16999, epoch_loss : 0.1699165768093533

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 57%|█████▋    | 17000/30000 [10:51:54<17:47:02,  4.92s/it]

REAL 평균 보상 : 13.727969348659004
생성 평균 보상 : 13.632183908045977

total time : 39117.611697912216

 57%|█████▋    | 17099/30000 [10:55:45<5:07:09,  1.43s/it]

epoch : 17099, epoch_loss : 0.12785342004564074

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 57%|█████▋    | 17100/30000 [10:55:58<17:21:41,  4.85s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 13.551724137931034

total time : 39361.24265551567

 57%|█████▋    | 17199/30000 [10:59:49<5:04:40,  1.43s/it]

epoch : 17199, epoch_loss : 0.11492473549313015

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 57%|█████▋    | 17200/30000 [11:00:01<16:31:17,  4.65s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.586206896551724

total time : 39604.1332719326

 58%|█████▊    | 17299/30000 [11:03:49<4:54:29,  1.39s/it]

epoch : 17299, epoch_loss : 0.16939420170254177

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B브로콜리크림스프', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 58%|█████▊    | 17300/30000 [11:04:02<16:41:10,  4.73s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.574712643678161

total time : 39845.17384696007

 58%|█████▊    | 17399/30000 [11:07:52<5:04:12,  1.45s/it]

epoch : 17399, epoch_loss : 0.11539553271399604

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 58%|█████▊    | 17400/30000 [11:08:05<16:49:37,  4.81s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.639846743295019

total time : 40088.386890888214

 58%|█████▊    | 17499/30000 [11:11:54<4:55:29,  1.42s/it]

epoch : 17499, epoch_loss : 0.13824722501966688

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 58%|█████▊    | 17500/30000 [11:12:07<16:17:58,  4.69s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.636015325670497

total time : 40330.040657520294

 59%|█████▊    | 17599/30000 [11:15:55<4:54:10,  1.42s/it]

epoch : 17599, epoch_loss : 0.15204714404212105

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 59%|█████▊    | 17600/30000 [11:16:08<16:19:30,  4.74s/it]

REAL 평균 보상 : 13.735632183908047
생성 평균 보상 : 13.551724137931034

total time : 40571.02045702934

 59%|█████▉    | 17699/30000 [11:19:56<4:55:01,  1.44s/it]

epoch : 17699, epoch_loss : 0.16488760047488743

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 59%|█████▉    | 17700/30000 [11:20:08<16:16:12,  4.76s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.452107279693486

total time : 40811.8811006546

 59%|█████▉    | 17799/30000 [11:23:58<5:00:27,  1.48s/it]

epoch : 17799, epoch_loss : 0.11013996601104736

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 59%|█████▉    | 17800/30000 [11:24:10<16:23:48,  4.84s/it]

REAL 평균 보상 : 13.816091954022989
생성 평균 보상 : 13.666666666666666

total time : 41053.61459684372

 60%|█████▉    | 17899/30000 [11:28:00<4:48:43,  1.43s/it]

epoch : 17899, epoch_loss : 0.10709390375349256

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 60%|█████▉    | 17900/30000 [11:28:12<15:57:09,  4.75s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.597701149425287

total time : 41295.801762104034

 60%|█████▉    | 17999/30000 [11:32:01<4:47:07,  1.44s/it]

epoch : 17999, epoch_loss : 0.16774581538306343

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 60%|██████    | 18000/30000 [11:32:13<15:32:47,  4.66s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.639846743295019

total time : 41536.591383218765

 60%|██████    | 18100/30000 [11:36:15<15:39:34,  4.74s/it]

epoch : 18099, epoch_loss : 0.14722590976291233

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.639846743295019

total time : 41778.26270747185

 61%|██████    | 18199/30000 [11:40:04<4:41:51,  1.43s/it]

epoch : 18199, epoch_loss : 0.09569534990522596

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 61%|██████    | 18299/30000 [11:44:07<4:39:54,  1.44s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.578544061302683

total time : 42020.23353624344
epoch : 18299, epoch_loss : 0.17055371072557238

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 61%|██████    | 18300/30000 [11:44:19<15:32:37,  4.78s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.540229885057471

total time : 42262.5908768177

 61%|██████▏   | 18399/30000 [11:48:09<4:24:21,  1.37s/it]

epoch : 18399, epoch_loss : 0.16359804736243355

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 61%|██████▏   | 18400/30000 [11:48:22<15:28:39,  4.80s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.578544061302683

total time : 42504.90215730667

 62%|██████▏   | 18499/30000 [11:52:11<4:41:11,  1.47s/it]

epoch : 18499, epoch_loss : 0.13030530346764457

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 62%|██████▏   | 18500/30000 [11:52:23<15:22:25,  4.81s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 13.597701149425287

total time : 42746.883238077164

 62%|██████▏   | 18599/30000 [11:56:14<4:46:17,  1.51s/it]

epoch : 18599, epoch_loss : 0.11534730593363444

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 62%|██████▏   | 18600/30000 [11:56:26<15:01:41,  4.75s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.685823754789272

total time : 42989.302334308624

 62%|██████▏   | 18699/30000 [12:00:15<4:38:09,  1.48s/it]

epoch : 18699, epoch_loss : 0.11926739745669895

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 62%|██████▏   | 18700/30000 [12:00:28<15:02:45,  4.79s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.636015325670497

total time : 43231.3460521698

 63%|██████▎   | 18799/30000 [12:04:18<4:24:53,  1.42s/it]

epoch : 18799, epoch_loss : 0.09981305069393581

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 63%|██████▎   | 18800/30000 [12:04:31<15:10:59,  4.88s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 13.624521072796934

total time : 43474.302891254425

 63%|██████▎   | 18899/30000 [12:08:21<4:27:29,  1.45s/it]

epoch : 18899, epoch_loss : 0.15704581472608778

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 63%|██████▎   | 18900/30000 [12:08:34<15:04:28,  4.89s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.616858237547893

total time : 43716.94357943535

 63%|██████▎   | 18999/30000 [12:12:23<4:21:18,  1.43s/it]

epoch : 18999, epoch_loss : 0.1653050051795112

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 63%|██████▎   | 19000/30000 [12:12:35<14:11:52,  4.65s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.71647509578544

total time : 43958.64778971672

 64%|██████▎   | 19099/30000 [12:16:26<4:29:50,  1.49s/it]

epoch : 19099, epoch_loss : 0.12669656011793348

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '대구구이', '애호박건새우볶음', '파김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', '단배추물김치', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박양파볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 64%|██████▎   | 19100/30000 [12:16:38<14:08:33,  4.67s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.666666666666666

total time : 44201.35733437538

 64%|██████▍   | 19199/30000 [12:20:27<4:24:46,  1.47s/it]

epoch : 19199, epoch_loss : 0.12593485249413383

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 64%|██████▍   | 19200/30000 [12:20:40<14:16:00,  4.76s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.64367816091954

total time : 44443.094584703445

 64%|██████▍   | 19299/30000 [12:24:30<4:21:37,  1.47s/it]

epoch : 19299, epoch_loss : 0.12474628289540608

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 64%|██████▍   | 19300/30000 [12:24:43<14:23:18,  4.84s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.616858237547893

total time : 44686.42702937126

 65%|██████▍   | 19399/30000 [12:28:34<4:13:32,  1.43s/it]

epoch : 19399, epoch_loss : 0.15107444922129312

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 65%|██████▍   | 19400/30000 [12:28:47<14:09:05,  4.81s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.509578544061302

total time : 44930.3731174469

 65%|██████▍   | 19499/30000 [12:32:37<4:05:47,  1.40s/it]

epoch : 19499, epoch_loss : 0.15677801767985025

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 65%|██████▌   | 19500/30000 [12:32:50<13:50:18,  4.74s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 13.64367816091954

total time : 45173.37288355827

 65%|██████▌   | 19599/30000 [12:36:42<4:20:18,  1.50s/it]

epoch : 19599, epoch_loss : 0.08413818809721205

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 65%|██████▌   | 19600/30000 [12:36:54<13:53:28,  4.81s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.559386973180077

total time : 45417.41202235222

 66%|██████▌   | 19699/30000 [12:40:46<4:21:41,  1.52s/it]

epoch : 19699, epoch_loss : 0.11344226201375325

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 66%|██████▌   | 19700/30000 [12:40:59<13:36:22,  4.76s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.601532567049809

total time : 45662.07452297211

 66%|██████▌   | 19799/30000 [12:44:50<4:04:44,  1.44s/it]

epoch : 19799, epoch_loss : 0.13118331962161595

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 66%|██████▌   | 19800/30000 [12:45:02<13:28:37,  4.76s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.620689655172415

total time : 45905.69409060478

 66%|██████▋   | 19899/30000 [12:48:53<4:05:10,  1.46s/it]

epoch : 19899, epoch_loss : 0.1716691388024224

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(백도)-80g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 66%|██████▋   | 19900/30000 [12:49:06<13:52:29,  4.95s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.616858237547893

total time : 46149.85605573654

 67%|██████▋   | 19999/30000 [12:52:59<4:13:13,  1.52s/it]

epoch : 19999, epoch_loss : 0.1335949500401815

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(백도)-60g', 'S복숭아(천도)-80g', '율무밥(55)', '달래맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S단호박설기', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 8

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S멸치주먹밥', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', 'S크로와상']
생성 시퀀스의 영양수준: 9

 67%|██████▋   | 20000/30000 [12:53:12<13:33:28,  4.88s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.666666666666666

total time : 46395.0103623867

 67%|██████▋   | 20099/30000 [12:57:05<3:54:52,  1.42s/it]

epoch : 20099, epoch_loss : 0.10270680983861287

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '맛살양상추샐러드', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 67%|██████▋   | 20100/30000 [12:57:18<13:16:33,  4.83s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.601532567049809

total time : 46641.075303316116

 67%|██████▋   | 20199/30000 [13:01:12<4:00:36,  1.47s/it]

epoch : 20199, epoch_loss : 0.10308592187033759

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 67%|██████▋   | 20200/30000 [13:01:25<13:25:03,  4.93s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.662835249042146

total time : 46888.45752167702

 68%|██████▊   | 20299/30000 [13:05:18<4:00:04,  1.48s/it]

epoch : 20299, epoch_loss : 0.08890628814697266

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 68%|██████▊   | 20300/30000 [13:05:31<12:57:24,  4.81s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.662835249042146

total time : 47134.22250556946

 68%|██████▊   | 20399/30000 [13:09:25<3:50:39,  1.44s/it]

epoch : 20399, epoch_loss : 0.10478274689780341

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 68%|██████▊   | 20400/30000 [13:09:38<13:06:52,  4.92s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.659003831417625

total time : 47381.804232120514

 68%|██████▊   | 20499/30000 [13:13:31<3:58:14,  1.50s/it]

epoch : 20499, epoch_loss : 0.10382107893625896

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 68%|██████▊   | 20500/30000 [13:13:44<13:12:18,  5.00s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.71264367816092

total time : 47627.621290922165

 69%|██████▊   | 20599/30000 [13:17:38<3:55:48,  1.50s/it]

epoch : 20599, epoch_loss : 0.08835109737184313

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 69%|██████▊   | 20600/30000 [13:17:50<12:36:35,  4.83s/it]

REAL 평균 보상 : 13.754789272030651
생성 평균 보상 : 13.67816091954023

total time : 47873.48900151253

 69%|██████▉   | 20699/30000 [13:21:42<3:46:17,  1.46s/it]

epoch : 20699, epoch_loss : 0.16681694984436035

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 69%|██████▉   | 20700/30000 [13:21:55<12:38:42,  4.89s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.613026819923371

total time : 48118.68840718269

 69%|██████▉   | 20799/30000 [13:25:50<3:42:57,  1.45s/it]

epoch : 20799, epoch_loss : 0.11599977811177571

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '오징어채소볶음', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

 69%|██████▉   | 20800/30000 [13:26:03<12:28:50,  4.88s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.724137931034482

total time : 48366.66626524925

 70%|██████▉   | 20899/30000 [13:29:56<3:41:24,  1.46s/it]

epoch : 20899, epoch_loss : 0.1708842913309733

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 70%|██████▉   | 20900/30000 [13:30:08<12:08:38,  4.80s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 13.693486590038313

total time : 48611.61520600319

 70%|██████▉   | 20999/30000 [13:34:00<3:30:54,  1.41s/it]

epoch : 20999, epoch_loss : 0.13377879725562203

REAL 시퀀스 : ['시작', 'B소고기타락죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '조갯살된장찌개', '소고기양배추조림', '양배추나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 14

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(천도)-60g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 70%|███████   | 21000/30000 [13:34:13<11:49:32,  4.73s/it]

REAL 평균 보상 : 13.720306513409962
생성 평균 보상 : 13.71647509578544

total time : 48856.14003634453

 70%|███████   | 21099/30000 [13:38:05<3:37:09,  1.46s/it]

epoch : 21099, epoch_loss : 0.09844408432642619

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 70%|███████   | 21100/30000 [13:38:18<11:46:49,  4.77s/it]

REAL 평균 보상 : 13.71264367816092
생성 평균 보상 : 13.620689655172415

total time : 49101.22822999954

 71%|███████   | 21199/30000 [13:42:10<3:38:16,  1.49s/it]

epoch : 21199, epoch_loss : 0.1600445376502143

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 71%|███████   | 21299/30000 [13:46:20<4:55:39,  2.04s/it]

REAL 평균 보상 : 13.735632183908047
생성 평균 보상 : 13.53639846743295

total time : 49345.481539011
epoch : 21299, epoch_loss : 0.09919029474258423

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 71%|███████   | 21300/30000 [13:46:34<13:45:46,  5.69s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.662835249042146

total time : 49597.88033246994

 71%|███████▏  | 21399/30000 [13:50:51<3:47:23,  1.59s/it]

epoch : 21399, epoch_loss : 0.09446572595172459

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 71%|███████▏  | 21400/30000 [13:51:04<12:31:49,  5.25s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.655172413793103

total time : 49867.704641103745

 72%|███████▏  | 21499/30000 [13:55:22<3:35:22,  1.52s/it]

epoch : 21499, epoch_loss : 0.13154122564527723

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 72%|███████▏  | 21500/30000 [13:55:36<12:33:34,  5.32s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.57088122605364

total time : 50139.861857652664

 72%|███████▏  | 21599/30000 [13:59:45<3:44:15,  1.60s/it]

epoch : 21599, epoch_loss : 0.10852938228183323

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '청경채맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S단호박꿀찜', 'S보리차', '율무밥(55)', '유부대파국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '실파달걀국', '북어채소찜', '건새우애호박볶음', '비트초절이', '종료', 'S보리차', '율무밥(55)', '감자채맑은국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 72%|███████▏  | 21600/30000 [13:59:58<12:06:49,  5.19s/it]

REAL 평균 보상 : 13.831417624521073
생성 평균 보상 : 13.651340996168582

total time : 50401.81369614601

 72%|███████▏  | 21699/30000 [14:04:08<3:33:42,  1.54s/it]

epoch : 21699, epoch_loss : 0.13294560379452175

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 72%|███████▏  | 21700/30000 [14:04:21<11:40:56,  5.07s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.666666666666666

total time : 50664.23064303398

 73%|███████▎  | 21799/30000 [14:08:45<3:51:16,  1.69s/it]

epoch : 21799, epoch_loss : 0.13261707623799643

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 73%|███████▎  | 21800/30000 [14:09:00<12:55:04,  5.67s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.670498084291188

total time : 50943.17921113968

 73%|███████▎  | 21899/30000 [14:13:07<3:28:32,  1.54s/it]

epoch : 21899, epoch_loss : 0.13839830292595756

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '배추김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '청경채된장무침', '석박지', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 73%|███████▎  | 21999/30000 [14:17:29<3:29:17,  1.57s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.666666666666666

total time : 51204.27765202522
epoch : 21999, epoch_loss : 0.14006845156351724

REAL 시퀀스 : ['시작', 'B소고기스프', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '청경채맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '무채양파국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '열무물김치', 'S크로와상', 'S보리차', '율무밥(55)', '배추맑은국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 73%|███████▎  | 22000/30000 [14:17:41<10:58:19,  4.94s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.639846743295019

total time : 51464.87292051315

 74%|███████▎  | 22099/30000 [14:21:46<3:18:20,  1.51s/it]

epoch : 22099, epoch_loss : 0.12488557232750787

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 74%|███████▎  | 22100/30000 [14:21:59<10:59:06,  5.01s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.68199233716475

total time : 51722.07818412781

 74%|███████▍  | 22199/30000 [14:25:58<3:17:37,  1.52s/it]

epoch : 22199, epoch_loss : 0.10449404848946466

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 74%|███████▍  | 22200/30000 [14:26:11<10:37:34,  4.90s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.597701149425287

total time : 51974.43305230141

 74%|███████▍  | 22299/30000 [14:30:11<3:13:24,  1.51s/it]

epoch : 22299, epoch_loss : 0.07556317912207709

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 74%|███████▍  | 22300/30000 [14:30:24<10:36:41,  4.96s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.666666666666666

total time : 52227.404366493225

 75%|███████▍  | 22399/30000 [14:34:23<3:07:13,  1.48s/it]

epoch : 22399, epoch_loss : 0.15133123927646214

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 75%|███████▍  | 22400/30000 [14:34:36<10:11:24,  4.83s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.662835249042146

total time : 52479.49478125572

 75%|███████▍  | 22499/30000 [14:38:33<3:12:28,  1.54s/it]

epoch : 22499, epoch_loss : 0.16476427184210884

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 75%|███████▌  | 22500/30000 [14:38:46<10:30:53,  5.05s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 13.666666666666666

total time : 52729.857060194016

 75%|███████▌  | 22599/30000 [14:42:42<3:03:37,  1.49s/it]

epoch : 22599, epoch_loss : 0.16427387131585014

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 75%|███████▌  | 22600/30000 [14:42:55<9:52:50,  4.81s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.636015325670497

total time : 52978.35318803787

 76%|███████▌  | 22699/30000 [14:46:52<2:58:03,  1.46s/it]

epoch : 22699, epoch_loss : 0.13029003143310547

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S치즈머핀', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 76%|███████▌  | 22700/30000 [14:47:06<10:26:25,  5.15s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.60536398467433

total time : 53229.53369855881

 76%|███████▌  | 22799/30000 [14:51:05<3:02:54,  1.52s/it]

epoch : 22799, epoch_loss : 0.16484344005584717

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 76%|███████▌  | 22800/30000 [14:51:18<10:00:05,  5.00s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.586206896551724

total time : 53481.37351322174

 76%|███████▋  | 22899/30000 [14:55:19<3:07:34,  1.58s/it]

epoch : 22899, epoch_loss : 0.08204260137346056

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '참치애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 76%|███████▋  | 22900/30000 [14:55:32<9:55:08,  5.03s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.628352490421456

total time : 53734.97592329979

 77%|███████▋  | 22999/30000 [14:59:46<2:57:41,  1.52s/it]

epoch : 22999, epoch_loss : 0.09148005644480388

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '나박김치', '종료']
생성 시퀀스의 영양수준: 12

 77%|███████▋  | 23000/30000 [15:00:01<10:28:59,  5.39s/it]

REAL 평균 보상 : 13.720306513409962
생성 평균 보상 : 13.632183908045977

total time : 54004.16068267822

 77%|███████▋  | 23099/30000 [15:04:08<3:01:08,  1.57s/it]

epoch : 23099, epoch_loss : 0.1612282461590237

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 77%|███████▋  | 23100/30000 [15:04:21<9:34:57,  5.00s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.567049808429118

total time : 54264.419004917145

 77%|███████▋  | 23199/30000 [15:08:30<2:59:32,  1.58s/it]

epoch : 23199, epoch_loss : 0.1127996842066447

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 77%|███████▋  | 23200/30000 [15:08:46<10:53:46,  5.77s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.555555555555555

total time : 54528.97498583794

 78%|███████▊  | 23299/30000 [15:13:19<3:01:27,  1.62s/it]

epoch : 23299, epoch_loss : 0.108257704310947

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 78%|███████▊  | 23300/30000 [15:13:34<10:46:11,  5.79s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.651340996168582

total time : 54817.54005527496

 78%|███████▊  | 23399/30000 [15:18:04<3:04:28,  1.68s/it]

epoch : 23399, epoch_loss : 0.07814431852764553

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 78%|███████▊  | 23400/30000 [15:18:19<10:12:49,  5.57s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.64367816091954

total time : 55102.419919252396

 78%|███████▊  | 23499/30000 [15:22:54<3:12:38,  1.78s/it]

epoch : 23499, epoch_loss : 0.1375574933158027

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 78%|███████▊  | 23500/30000 [15:23:10<10:41:38,  5.92s/it]

REAL 평균 보상 : 13.735632183908047
생성 평균 보상 : 13.590038314176246

total time : 55393.13345313072

 79%|███████▊  | 23599/30000 [15:27:49<3:09:36,  1.78s/it]

epoch : 23599, epoch_loss : 0.07912594742245144

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 79%|███████▊  | 23600/30000 [15:28:04<10:29:17,  5.90s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.64367816091954

total time : 55687.63414311409

 79%|███████▉  | 23699/30000 [15:32:42<2:52:51,  1.65s/it]

epoch : 23699, epoch_loss : 0.14218486679924858

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 79%|███████▉  | 23700/30000 [15:32:57<9:48:47,  5.61s/it]

REAL 평균 보상 : 13.731800766283525
생성 평균 보상 : 13.71264367816092

total time : 55980.19152903557

 79%|███████▉  | 23799/30000 [15:37:30<2:45:31,  1.60s/it]

epoch : 23799, epoch_loss : 0.08724992805057102

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 79%|███████▉  | 23800/30000 [15:37:46<10:06:47,  5.87s/it]

REAL 평균 보상 : 13.71264367816092
생성 평균 보상 : 13.586206896551724

total time : 56268.93348360062

 80%|███████▉  | 23899/30000 [15:42:14<2:45:12,  1.62s/it]

epoch : 23899, epoch_loss : 0.07475848330391778

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-60g', '율무밥(55)', '애호박맑은국', '북어채소찜', '해초볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '총각김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '해초볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '나박김치', '종료']
생성 시퀀스의 영양수준: 12

 80%|███████▉  | 23900/30000 [15:42:29<9:33:00,  5.64s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.67432950191571

total time : 56552.53891205788

 80%|███████▉  | 23999/30000 [15:46:46<2:34:42,  1.55s/it]

epoch : 23999, epoch_loss : 0.15091224511464438

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 80%|████████  | 24000/30000 [15:47:00<8:48:35,  5.29s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.758620689655173

total time : 56823.302359580994

 80%|████████  | 24099/30000 [15:51:22<2:41:36,  1.64s/it]

epoch : 24099, epoch_loss : 0.10862698819902208

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B호두두부쉐이크', 'B방울토마토(35g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '시금치맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 9

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'S단호박설기', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 80%|████████  | 24100/30000 [15:51:36<8:35:27,  5.24s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.67432950191571

total time : 57098.97955369949

 81%|████████  | 24199/30000 [15:55:57<2:39:30,  1.65s/it]

epoch : 24199, epoch_loss : 0.1497692664464315

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 81%|████████  | 24200/30000 [15:56:11<8:46:41,  5.45s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.689655172413794

total time : 57374.781141757965

 81%|████████  | 24299/30000 [16:00:31<2:39:04,  1.67s/it]

epoch : 24299, epoch_loss : 0.15150512589348686

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 81%|████████  | 24300/30000 [16:00:46<8:43:52,  5.51s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.670498084291188

total time : 57649.034829854965

 81%|████████▏ | 24399/30000 [16:05:15<2:29:58,  1.61s/it]

epoch : 24399, epoch_loss : 0.10146258274714152

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '석박지', '종료']
생성 시퀀스의 영양수준: 11

 81%|████████▏ | 24400/30000 [16:05:30<8:44:05,  5.62s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.659003831417625

total time : 57932.93892240524

 82%|████████▏ | 24499/30000 [16:10:01<2:42:20,  1.77s/it]

epoch : 24499, epoch_loss : 0.15526792738172743

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 82%|████████▏ | 24500/30000 [16:10:18<9:30:53,  6.23s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.689655172413794

total time : 58221.45256996155

 82%|████████▏ | 24599/30000 [16:15:04<2:30:57,  1.68s/it]

epoch : 24599, epoch_loss : 0.13271560933854845

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 82%|████████▏ | 24600/30000 [16:15:24<10:36:08,  7.07s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.693486590038313

total time : 58527.10844516754

 82%|████████▏ | 24699/30000 [16:20:15<2:32:56,  1.73s/it]

epoch : 24699, epoch_loss : 0.15397402975294325

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B배(50g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박나물', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '청경채된장무침', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 82%|████████▏ | 24700/30000 [16:20:32<9:14:27,  6.28s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.701149425287356

total time : 58835.18142294884

 83%|████████▎ | 24799/30000 [16:25:18<2:24:53,  1.67s/it]

epoch : 24799, epoch_loss : 0.14992709954579672

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 83%|████████▎ | 24800/30000 [16:25:33<8:10:16,  5.66s/it]

REAL 평균 보상 : 13.839080459770114
생성 평균 보상 : 13.628352490421456

total time : 59136.174894571304

 83%|████████▎ | 24899/30000 [16:29:58<2:22:40,  1.68s/it]

epoch : 24899, epoch_loss : 0.13224122259351942

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 83%|████████▎ | 24900/30000 [16:30:11<7:22:56,  5.21s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.727969348659004

total time : 59414.485587358475

 83%|████████▎ | 24999/30000 [16:34:26<2:18:07,  1.66s/it]

epoch : 24999, epoch_loss : 0.09409361415439182

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 83%|████████▎ | 25000/30000 [16:34:40<7:28:56,  5.39s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.689655172413794

total time : 59683.57606124878

 84%|████████▎ | 25099/30000 [16:38:56<2:09:31,  1.59s/it]

epoch : 25099, epoch_loss : 0.10600562890370686

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 84%|████████▎ | 25100/30000 [16:39:11<7:32:58,  5.55s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.689655172413794

total time : 59954.34170293808

 84%|████████▍ | 25199/30000 [16:43:36<2:12:50,  1.66s/it]

epoch : 25199, epoch_loss : 0.16904273298051622

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 84%|████████▍ | 25200/30000 [16:43:51<7:14:24,  5.43s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.616858237547893

total time : 60233.90258407593

 84%|████████▍ | 25299/30000 [16:48:21<2:15:07,  1.72s/it]

epoch : 25299, epoch_loss : 0.16058821148342556

REAL 시퀀스 : ['시작', 'B소고기양파죽', 'B고구마쉐이크', 'B방울토마토(70g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '해초볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 13

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(백도)-80g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 84%|████████▍ | 25300/30000 [16:48:36<7:22:01,  5.64s/it]

REAL 평균 보상 : 13.762452107279694
생성 평균 보상 : 13.632183908045977

total time : 60518.92474889755

 85%|████████▍ | 25399/30000 [16:52:55<2:08:44,  1.68s/it]

epoch : 25399, epoch_loss : 0.10032929314507379

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 85%|████████▍ | 25400/30000 [16:53:10<7:12:04,  5.64s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.639846743295019

total time : 60793.11412525177

 85%|████████▍ | 25499/30000 [16:57:28<1:54:29,  1.53s/it]

epoch : 25499, epoch_loss : 0.13757067256503636

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 85%|████████▌ | 25500/30000 [16:57:41<6:22:24,  5.10s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.666666666666666

total time : 61064.874365091324

 85%|████████▌ | 25599/30000 [17:01:53<1:58:30,  1.62s/it]

epoch : 25599, epoch_loss : 0.12585625383589003

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S아몬드', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박건새우볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '호박양파국', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 10

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '해초볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

 85%|████████▌ | 25600/30000 [17:02:06<6:26:42,  5.27s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.659003831417625

total time : 61329.69979977608

 86%|████████▌ | 25699/30000 [17:06:32<2:18:56,  1.94s/it]

epoch : 25699, epoch_loss : 0.15615491072336832

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '해초볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

 86%|████████▌ | 25700/30000 [17:06:50<8:03:03,  6.74s/it]

REAL 평균 보상 : 13.74712643678161
생성 평균 보상 : 13.636015325670497

total time : 61613.25554513931

 86%|████████▌ | 25799/30000 [17:11:39<1:56:59,  1.67s/it]

epoch : 25799, epoch_loss : 0.12728562619951037

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S사과(75g)', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '쑥갓나물', '총각김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S복숭아(천도)-60g', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 10

 86%|████████▌ | 25800/30000 [17:11:54<6:35:06,  5.64s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.693486590038313

total time : 61917.27672600746

 86%|████████▋ | 25899/30000 [17:16:20<1:55:18,  1.69s/it]

epoch : 25899, epoch_loss : 0.15213600794474283

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 86%|████████▋ | 25900/30000 [17:16:36<6:39:51,  5.85s/it]

REAL 평균 보상 : 13.827586206896552
생성 평균 보상 : 13.68199233716475

total time : 62198.997764110565

 87%|████████▋ | 25999/30000 [17:21:01<1:48:45,  1.63s/it]

epoch : 25999, epoch_loss : 0.14539186159769693

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B요구르트', 'B사과(75g)', 'S아몬드', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '오이소박이김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 87%|████████▋ | 26000/30000 [17:21:15<6:10:39,  5.56s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.64367816091954

total time : 62478.69420480728

 87%|████████▋ | 26099/30000 [17:25:54<1:48:55,  1.68s/it]

epoch : 26099, epoch_loss : 0.10983784331215753

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'S크림떡볶이', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 87%|████████▋ | 26100/30000 [17:26:09<5:56:57,  5.49s/it]

REAL 평균 보상 : 13.816091954022989
생성 평균 보상 : 13.670498084291188

total time : 62772.27478027344

 87%|████████▋ | 26199/30000 [17:30:49<1:49:31,  1.73s/it]

epoch : 26199, epoch_loss : 0.08524719211790296

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 87%|████████▋ | 26200/30000 [17:31:03<5:38:52,  5.35s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.670498084291188

total time : 63066.180958509445

 88%|████████▊ | 26299/30000 [17:35:36<1:47:22,  1.74s/it]

epoch : 26299, epoch_loss : 0.09605513678656684

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 88%|████████▊ | 26300/30000 [17:35:51<5:51:53,  5.71s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.655172413793103

total time : 63353.89490365982

 88%|████████▊ | 26399/30000 [17:40:02<1:30:43,  1.51s/it]

epoch : 26399, epoch_loss : 0.0894814862145318

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 88%|████████▊ | 26400/30000 [17:40:15<5:06:19,  5.11s/it]

REAL 평균 보상 : 13.793103448275861
생성 평균 보상 : 13.685823754789272

total time : 63618.83670568466

 88%|████████▊ | 26499/30000 [17:44:22<1:35:11,  1.63s/it]

epoch : 26499, epoch_loss : 0.08345138364368015

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 88%|████████▊ | 26500/30000 [17:44:34<4:50:10,  4.97s/it]

REAL 평균 보상 : 13.800766283524904
생성 평균 보상 : 13.601532567049809

total time : 63877.72211050987

 89%|████████▊ | 26599/30000 [17:48:56<1:35:53,  1.69s/it]

epoch : 26599, epoch_loss : 0.16030832131703696

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 89%|████████▊ | 26600/30000 [17:49:10<5:13:15,  5.53s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.68199233716475

total time : 64153.76967692375

 89%|████████▉ | 26700/30000 [17:53:13<4:12:35,  4.59s/it]

epoch : 26699, epoch_loss : 0.10171092881096734

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(80g)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.685823754789272

total time : 64396.70893406868

 89%|████████▉ | 26799/30000 [17:56:58<1:14:06,  1.39s/it]

epoch : 26799, epoch_loss : 0.1279794242646959

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 89%|████████▉ | 26800/30000 [17:57:09<3:59:18,  4.49s/it]

REAL 평균 보상 : 13.743295019157088
생성 평균 보상 : 13.639846743295019

total time : 64632.839581012726

 90%|████████▉ | 26899/30000 [18:00:59<1:13:46,  1.43s/it]

epoch : 26899, epoch_loss : 0.09545121590296428

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 90%|████████▉ | 26900/30000 [18:01:12<4:00:37,  4.66s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.68199233716475

total time : 64874.92646360397

 90%|████████▉ | 26999/30000 [18:05:07<1:07:58,  1.36s/it]

epoch : 26999, epoch_loss : 0.13768426577250162

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 90%|█████████ | 27000/30000 [18:05:19<3:55:26,  4.71s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.620689655172415

total time : 65122.781443595886

 90%|█████████ | 27099/30000 [18:09:09<1:06:23,  1.37s/it]

epoch : 27099, epoch_loss : 0.1532289054658678

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 90%|█████████ | 27100/30000 [18:09:21<3:40:35,  4.56s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.632183908045977

total time : 65363.99656748772

 91%|█████████ | 27199/30000 [18:13:02<1:04:58,  1.39s/it]

epoch : 27199, epoch_loss : 0.15260032812754312

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 91%|█████████ | 27200/30000 [18:13:14<3:35:42,  4.62s/it]

REAL 평균 보상 : 13.770114942528735
생성 평균 보상 : 13.578544061302683

total time : 65597.63216900826

 91%|█████████ | 27299/30000 [18:16:56<1:01:11,  1.36s/it]

epoch : 27299, epoch_loss : 0.08071383502748278

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 91%|█████████ | 27300/30000 [18:17:07<3:19:20,  4.43s/it]

REAL 평균 보상 : 13.812260536398467
생성 평균 보상 : 13.616858237547893

total time : 65830.49255347252

 91%|█████████▏| 27399/30000 [18:20:52<59:22,  1.37s/it]

epoch : 27399, epoch_loss : 0.1486455069647895

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 92%|█████████▏| 27499/30000 [18:24:46<58:24,  1.40s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.697318007662835

total time : 66067.33654952049
epoch : 27499, epoch_loss : 0.11507132318284777

REAL 시퀀스 : ['시작', 'B소고기감자죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '파김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '오이소박이김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '열무물김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '유부쑥갓맑은국', '종료']
생성 시퀀스의 영양수준: 10

 92%|█████████▏| 27500/30000 [18:24:57<3:03:04,  4.39s/it]

REAL 평균 보상 : 13.812260536398467
생성 평균 보상 : 13.693486590038313

total time : 66300.3136920929

 92%|█████████▏| 27599/30000 [18:28:39<55:08,  1.38s/it]

epoch : 27599, epoch_loss : 0.08995271391338772

REAL 시퀀스 : ['시작', 'B소고기타락죽', 'B요구르트', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '석박지', '종료']
REAL 시퀀스의 영양수준: 12

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '석박지', '종료']
생성 시퀀스의 영양수준: 11

 92%|█████████▏| 27600/30000 [18:28:51<3:02:59,  4.57s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.67432950191571

total time : 66534.87047815323

 92%|█████████▏| 27699/30000 [18:33:02<59:45,  1.56s/it]

epoch : 27699, epoch_loss : 0.11180178324381511

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 92%|█████████▏| 27700/30000 [18:33:14<3:04:14,  4.81s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.632183908045977

total time : 66797.84998321533

 93%|█████████▎| 27799/30000 [18:37:12<52:42,  1.44s/it]

epoch : 27799, epoch_loss : 0.16830407248602974

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S아몬드', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '오이소박이김치', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기메란조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 9

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 93%|█████████▎| 27800/30000 [18:37:24<2:53:20,  4.73s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.697318007662835

total time : 67047.68679070473

 93%|█████████▎| 27899/30000 [18:41:20<51:35,  1.47s/it]

epoch : 27899, epoch_loss : 0.12222516536712646

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 93%|█████████▎| 27900/30000 [18:41:34<3:01:15,  5.18s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.659003831417625

total time : 67297.5361495018

 93%|█████████▎| 27999/30000 [18:45:26<55:29,  1.66s/it]

epoch : 27999, epoch_loss : 0.094326118628184

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 93%|█████████▎| 28000/30000 [18:45:38<2:44:38,  4.94s/it]

REAL 평균 보상 : 13.81992337164751
생성 평균 보상 : 13.71647509578544

total time : 67541.5952398777

 94%|█████████▎| 28099/30000 [18:49:31<49:22,  1.56s/it]

epoch : 28099, epoch_loss : 0.15528326564364964

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 94%|█████████▎| 28100/30000 [18:49:43<2:23:31,  4.53s/it]

REAL 평균 보상 : 13.773946360153257
생성 평균 보상 : 13.697318007662835

total time : 67786.24781012535

 94%|█████████▍| 28199/30000 [18:53:30<51:36,  1.72s/it]

epoch : 28199, epoch_loss : 0.1446366442574395

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 94%|█████████▍| 28200/30000 [18:53:42<2:24:54,  4.83s/it]

REAL 평균 보상 : 13.766283524904214
생성 평균 보상 : 13.613026819923371

total time : 68025.04749679565

 94%|█████████▍| 28299/30000 [18:57:34<45:21,  1.60s/it]

epoch : 28299, epoch_loss : 0.13089938958485922

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 94%|█████████▍| 28300/30000 [18:57:46<2:14:28,  4.75s/it]

REAL 평균 보상 : 13.796934865900383
생성 평균 보상 : 13.67432950191571

total time : 68269.00921392441

 95%|█████████▍| 28399/30000 [19:01:36<37:39,  1.41s/it]

epoch : 28399, epoch_loss : 0.06265994575288561

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '채소샐러드', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 13

 95%|█████████▍| 28400/30000 [19:01:48<1:59:51,  4.49s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.670498084291188

total time : 68511.27449154854

 95%|█████████▍| 28499/30000 [19:05:29<38:05,  1.52s/it]

epoch : 28499, epoch_loss : 0.12091539965735541

REAL 시퀀스 : ['시작', 'B소고기주먹밥', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기떡조림', '깻잎나물', '총각김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 95%|█████████▌| 28500/30000 [19:05:41<1:51:02,  4.44s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.704980842911878

total time : 68744.12283992767

 95%|█████████▌| 28599/30000 [19:09:20<32:42,  1.40s/it]

epoch : 28599, epoch_loss : 0.15829145908355713

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 95%|█████████▌| 28600/30000 [19:09:33<1:52:39,  4.83s/it]

REAL 평균 보상 : 13.781609195402298
생성 평균 보상 : 13.697318007662835

total time : 68976.46556305885

 96%|█████████▌| 28699/30000 [19:13:13<29:29,  1.36s/it]

epoch : 28699, epoch_loss : 0.12308781676822239

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S과일샐러드(요거트드레싱)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 96%|█████████▌| 28700/30000 [19:13:26<1:44:07,  4.81s/it]

REAL 평균 보상 : 13.758620689655173
생성 평균 보상 : 13.71264367816092

total time : 69209.39540195465

 96%|█████████▌| 28799/30000 [19:17:10<28:26,  1.42s/it]

epoch : 28799, epoch_loss : 0.0871427853902181

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 96%|█████████▌| 28800/30000 [19:17:23<1:36:48,  4.84s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.685823754789272

total time : 69446.12320303917

 96%|█████████▋| 28899/30000 [19:21:12<26:24,  1.44s/it]

epoch : 28899, epoch_loss : 0.10193341308169895

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', '석박지', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 9

 96%|█████████▋| 28900/30000 [19:21:25<1:30:36,  4.94s/it]

REAL 평균 보상 : 13.777777777777779
생성 평균 보상 : 13.704980842911878

total time : 69688.77889943123

 97%|█████████▋| 28999/30000 [19:25:18<23:53,  1.43s/it]

epoch : 28999, epoch_loss : 0.09960674577289158

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 97%|█████████▋| 29000/30000 [19:25:31<1:23:59,  5.04s/it]

REAL 평균 보상 : 13.739463601532567
생성 평균 보상 : 13.601532567049809

total time : 69934.73420500755

 97%|█████████▋| 29099/30000 [19:29:33<21:54,  1.46s/it]

epoch : 29099, epoch_loss : 0.09687088595496283

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(50g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '애호박건새우볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기메란조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 10

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(50g)', 'S오이스틱', 'S참외(50g)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 97%|█████████▋| 29100/30000 [19:29:46<1:10:06,  4.67s/it]

REAL 평균 보상 : 13.75095785440613
생성 평균 보상 : 13.743295019157088

total time : 70188.90662789345

 97%|█████████▋| 29199/30000 [19:33:26<18:35,  1.39s/it]

epoch : 29199, epoch_loss : 0.14530720975663927

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 97%|█████████▋| 29200/30000 [19:33:37<59:04,  4.43s/it]

REAL 평균 보상 : 13.789272030651341
생성 평균 보상 : 13.735632183908047

total time : 70420.6334643364

 98%|█████████▊| 29299/30000 [19:37:11<15:09,  1.30s/it]

epoch : 29299, epoch_loss : 0.08603963587019178

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 98%|█████████▊| 29300/30000 [19:37:23<51:08,  4.38s/it]

REAL 평균 보상 : 13.835249042145595
생성 평균 보상 : 13.67432950191571

total time : 70646.03856134415

 98%|█████████▊| 29399/30000 [19:41:03<14:36,  1.46s/it]

epoch : 29399, epoch_loss : 0.1456782023111979

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 98%|█████████▊| 29400/30000 [19:41:15<45:56,  4.59s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.685823754789272

total time : 70878.32378602028

 98%|█████████▊| 29500/30000 [19:45:04<36:44,  4.41s/it]

epoch : 29499, epoch_loss : 0.11978756056891547

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S사과(35g)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '호박양파국', '소고기양배추조림', '청경채된장무침', '배추김치', '종료']
REAL 시퀀스의 영양수준: 14

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S사과(35g)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

REAL 평균 보상 : 13.831417624521073
생성 평균 보상 : 13.720306513409962

total time : 71107.68305373192

 99%|█████████▊| 29599/30000 [19:48:51<09:16,  1.39s/it]

epoch : 29599, epoch_loss : 0.09175439675649007

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S사과(35g)', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 12

 99%|█████████▊| 29600/30000 [19:49:02<29:37,  4.44s/it]

REAL 평균 보상 : 13.827586206896552
생성 평균 보상 : 13.793103448275861

total time : 71345.86384367943

 99%|█████████▉| 29699/30000 [19:52:43<07:02,  1.40s/it]

epoch : 29699, epoch_loss : 0.11978382534450954

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

 99%|█████████▉| 29700/30000 [19:52:55<22:42,  4.54s/it]

REAL 평균 보상 : 13.808429118773946
생성 평균 보상 : 13.735632183908047

total time : 71578.34109330177

 99%|█████████▉| 29799/30000 [19:56:37<04:48,  1.44s/it]

epoch : 29799, epoch_loss : 0.10751420921749538

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

100%|█████████▉| 29899/30000 [20:00:34<02:24,  1.43s/it]

REAL 평균 보상 : 13.804597701149426
생성 평균 보상 : 13.659003831417625

total time : 71812.48691010475
epoch : 29899, epoch_loss : 0.16172573301527235

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B삶은감자', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

100%|█████████▉| 29900/30000 [20:00:45<07:33,  4.54s/it]

REAL 평균 보상 : 13.816091954022989
생성 평균 보상 : 13.670498084291188

total time : 72048.75891804695

100%|█████████▉| 29999/30000 [20:04:20<00:01,  1.34s/it]

epoch : 29999, epoch_loss : 0.10052896870507134

REAL 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
REAL 시퀀스의 영양수준: 11

생성 시퀀스 : ['시작', 'B소고기미역죽', 'B고구마쉐이크', 'B사과(75g)', 'S오이스틱', 'S복숭아(천도)-80g', '율무밥(55)', '애호박맑은국', '북어채소찜', '건새우애호박볶음', '비트초절이', 'S크로와상', 'S보리차', '율무밥(55)', '맑은바지락탕', '소고기양배추조림', '깻잎나물', '배추김치', '종료']
생성 시퀀스의 영양수준: 11

100%|██████████| 30000/30000 [20:04:32<00:00,  2.41s/it]

REAL 평균 보상 : 13.78544061302682
생성 평균 보상 : 13.651340996168582

total time : 72275.61706662178

In [11]:
generated_diets = sequence_to_sentence(pred_seqs_all, food_dict)

In [12]:
#diet_data = pd.read_csv('./data/diet_data/diet68_boy_morning.csv', encoding = 'cp949')
new_df = pd.DataFrame(0, columns = range(0,19), index = range(len(generated_diets)))
for i in tqdm(range(len(generated_diets))):
    new_df.iloc[i] = generated_diets[i]

new_df

100%|██████████| 261/261 [00:00<00:00, 1789.06it/s]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,시작,B소고기미역죽,B고구마쉐이크,B사과(75g),S오이스틱,S복숭아(천도)-80g,율무밥(55),애호박맑은국,북어채소찜,건새우애호박볶음,비트초절이,S크로와상,S보리차,율무밥(55),맑은바지락탕,소고기양배추조림,깻잎나물,배추김치,종료
1,시작,B흰죽,B두유(100ml),B과일샐러드,S자두(50g),S사과(35g),찰현미밥(55),얼갈이맑은국,소고기파채볶음,브로콜리초무침,단무지무침,S개피떡(40g),S(우유제외)수제블루베리우유,해물굴소스볶음밥,안매운닭개장,고등어구이,(우유제외)단호박두유찜,배추김치,종료
2,시작,B찹쌀도너츠,B검은콩두유(100ml),B복숭아(60g),S바나나(100g),S복숭아(황도)-80g,해물버섯덮밥,동태살무국,오징어불고기,사과미나리무침,나박김치,S증편(40g),S오미자아이스크림,밤밥(55),다슬기된장국,가자미살구이,모듬과일샐러드,나박김치,종료
3,시작,B으깬견과류고구마샐러드(요거트),B(우유제외)수제바나나두유,B참외(50g),S복숭아(황도)-80g,S멜론(50g),현미밥(55),팽이장국,수제비샐러드,상추배생채,석박지,S쌀과자,S오미자아이스크림,현미밥(55),건새우시금치국,고구마연근맛탕,무사과무침,깍두기,종료
4,시작,B소고기타락죽,B(우유제외)수제바나나두유,B사과(75g),S참외(50g),S멜론(50g),옥수수밥(63),온청포묵국,오리훈제구이,땅콩우엉무침,배추김치,S단호박샐러드,S복숭아호두스무디,옥수수밥(63),쑥갓어묵탕,칠리새우,상추배생채,비트초절이,종료
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,시작,B해물죽,B고구마쉐이크,B블루베리고구마샐러드,S사과(35g),S사과샐러드(마요네즈),잡곡밥(55),대구지리,새우살채소볶음,건취나물간장볶음,열무물김치,S멸치주먹밥,S매실쥬스,잡곡밥(63),팽이장국,주꾸미채소간장볶음,진미채초무침,비트초절이,종료
257,시작,B시금치견과류주먹밥,B복숭아호두스무디,B복숭아(80g),S멜론(50g),S참외(50g),옥수수밥(63),쑥갓어묵국,수제비샐러드,애호박건새우볶음,배추김치,S시금치견과류주먹밥,S보리차,알리오올리오스파게티,애호박두부젓국찌개,토마토치즈범벅,진미채초무침,배추김치,종료
258,시작,B약과,B수제블루베리우유,B과일샐러드(요거트드레싱),S사과(35g),S블루베리고구마샐러드,검정콩밥(55),얼갈이배추국,매콤낙지채소볶음,건취나물간장볶음,오이소박이김치,S(우유제외)토마토스파게티,S보리차,검정콩밥(55),유부쑥갓맑은국,삼치구이+양념장,매쉬드포테이토,배추김치,종료
259,시작,B으깬견과류고구마샐러드(요거트),B(우유제외)수제바나나두유,B블루베리고구마샐러드,S복숭아(60g),S사과(100g),현미밥(55),동태살무국,닭가슴살고구마볶음,머위나물,오이소박이김치,S(우유제외)토마토스파게티,S코코아,현미밥(55),오징어숙주국,소고기파인애플볶음,건취나물간장볶음,파김치,종료
260,시작,B크로와상,B요구르트,B복숭아(80g),S수박화채,S멜론(100g),보리밥(55),애호박두부젓국,오징어채소볶음,해초볶음,배추김치,S찐고구마,S보리차,보리밥(55),다슬기된장국,닭가슴살고구마볶음,미역줄기채소볶음,배추김치,종료

In [13]:
nutrient_reward = reward_info_gen[:, 0]
new_df['nutrient_score'] = nutrient_reward
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,nutrient_score
0,시작,B소고기미역죽,B고구마쉐이크,B사과(75g),S오이스틱,S복숭아(천도)-80g,율무밥(55),애호박맑은국,북어채소찜,건새우애호박볶음,비트초절이,S크로와상,S보리차,율무밥(55),맑은바지락탕,소고기양배추조림,깻잎나물,배추김치,종료,11
1,시작,B흰죽,B두유(100ml),B과일샐러드,S자두(50g),S사과(35g),찰현미밥(55),얼갈이맑은국,소고기파채볶음,브로콜리초무침,단무지무침,S개피떡(40g),S(우유제외)수제블루베리우유,해물굴소스볶음밥,안매운닭개장,고등어구이,(우유제외)단호박두유찜,배추김치,종료,15
2,시작,B찹쌀도너츠,B검은콩두유(100ml),B복숭아(60g),S바나나(100g),S복숭아(황도)-80g,해물버섯덮밥,동태살무국,오징어불고기,사과미나리무침,나박김치,S증편(40g),S오미자아이스크림,밤밥(55),다슬기된장국,가자미살구이,모듬과일샐러드,나박김치,종료,15
3,시작,B으깬견과류고구마샐러드(요거트),B(우유제외)수제바나나두유,B참외(50g),S복숭아(황도)-80g,S멜론(50g),현미밥(55),팽이장국,수제비샐러드,상추배생채,석박지,S쌀과자,S오미자아이스크림,현미밥(55),건새우시금치국,고구마연근맛탕,무사과무침,깍두기,종료,15
4,시작,B소고기타락죽,B(우유제외)수제바나나두유,B사과(75g),S참외(50g),S멜론(50g),옥수수밥(63),온청포묵국,오리훈제구이,땅콩우엉무침,배추김치,S단호박샐러드,S복숭아호두스무디,옥수수밥(63),쑥갓어묵탕,칠리새우,상추배생채,비트초절이,종료,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,시작,B해물죽,B고구마쉐이크,B블루베리고구마샐러드,S사과(35g),S사과샐러드(마요네즈),잡곡밥(55),대구지리,새우살채소볶음,건취나물간장볶음,열무물김치,S멸치주먹밥,S매실쥬스,잡곡밥(63),팽이장국,주꾸미채소간장볶음,진미채초무침,비트초절이,종료,15
257,시작,B시금치견과류주먹밥,B복숭아호두스무디,B복숭아(80g),S멜론(50g),S참외(50g),옥수수밥(63),쑥갓어묵국,수제비샐러드,애호박건새우볶음,배추김치,S시금치견과류주먹밥,S보리차,알리오올리오스파게티,애호박두부젓국찌개,토마토치즈범벅,진미채초무침,배추김치,종료,14
258,시작,B약과,B수제블루베리우유,B과일샐러드(요거트드레싱),S사과(35g),S블루베리고구마샐러드,검정콩밥(55),얼갈이배추국,매콤낙지채소볶음,건취나물간장볶음,오이소박이김치,S(우유제외)토마토스파게티,S보리차,검정콩밥(55),유부쑥갓맑은국,삼치구이+양념장,매쉬드포테이토,배추김치,종료,14
259,시작,B으깬견과류고구마샐러드(요거트),B(우유제외)수제바나나두유,B블루베리고구마샐러드,S복숭아(60g),S사과(100g),현미밥(55),동태살무국,닭가슴살고구마볶음,머위나물,오이소박이김치,S(우유제외)토마토스파게티,S코코아,현미밥(55),오징어숙주국,소고기파인애플볶음,건취나물간장볶음,파김치,종료,14
260,시작,B크로와상,B요구르트,B복숭아(80g),S수박화채,S멜론(100g),보리밥(55),애호박두부젓국,오징어채소볶음,해초볶음,배추김치,S찐고구마,S보리차,보리밥(55),다슬기된장국,닭가슴살고구마볶음,미역줄기채소볶음,배추김치,종료,13

In [15]:
real_df = pd.DataFrame(0, columns =range(0,19), index = range(len(generated_diets)))

for i in tqdm(range(len(generated_diets))):
    real_df.iloc[i] = sequence_to_sentence(real_seqs_all, food_dict)[i]

#real_df

100%|██████████| 261/261 [00:00<00:00, 531.20it/s]

In [16]:
real_reward = reward_info_real[:, 0]
real_df['nutrient_score'] = real_reward
real_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,nutrient_score
0,시작,B소고기미역죽,B고구마쉐이크,B사과(75g),S오이스틱,S복숭아(천도)-80g,율무밥(55),애호박맑은국,북어채소찜,건새우애호박볶음,비트초절이,S크로와상,S보리차,율무밥(55),맑은바지락탕,소고기양배추조림,깻잎나물,배추김치,종료,11
1,시작,B가지죽,B두유(100ml),B복숭아(60g),S자두(50g),S사과(35g),찰현미밥(55),얼갈이맑은국,소고기파채볶음,브로콜리초무침,단무지무침,S개피떡(40g),S(우유제외)수제블루베리우유,해물굴소스볶음밥,안매운닭개장,고등어구이,(우유제외)단호박두유찜,배추김치,종료,13
2,시작,B찹쌀도너츠,B검은콩두유(100ml),B복숭아(60g),S바나나(100g),S복숭아(황도)-80g,해물버섯덮밥,다진소고기콩나물국,오징어간장조림,사과미나리무침,나박김치,S증편(40g),S오미자아이스크림,밤밥(55),다슬기된장국,삼치살두부감자조림,모듬과일샐러드,나박김치,종료,14
3,시작,B으깬견과류고구마샐러드(요거트),B(우유제외)수제바나나두유,B참외(50g),S복숭아(황도)-80g,S멜론(50g),현미밥(55),팽이장국,수제비샐러드,상추배생채,석박지,S쌀과자,S오미자아이스크림,현미밥(55),건새우시금치국,고구마연근맛탕,무사과무침,깍두기,종료,15
4,시작,B채소전,B(우유제외)수제바나나두유,B사과(75g),S참외(50g),S멜론(50g),옥수수밥(63),온청포묵국,오리훈제구이,땅콩우엉무침,배추김치,S단호박샐러드,S복숭아호두스무디,옥수수밥(63),쑥갓어묵탕,칠리새우,상추배생채,비트초절이,종료,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,시작,B해물죽,B고구마쉐이크,B블루베리고구마샐러드,S사과(35g),S사과샐러드(마요네즈),잡곡밥(55),대구지리,새우살채소볶음,건취나물간장볶음,열무물김치,S멸치주먹밥,S매실쥬스,잡곡밥(63),팽이장국,주꾸미채소간장볶음,진미채초무침,비트초절이,종료,15
257,시작,B시금치견과류주먹밥,B복숭아호두스무디,B복숭아(80g),S멜론(50g),S참외(50g),옥수수밥(63),동태살무국,수제비샐러드,애호박건새우볶음,배추김치,S시금치견과류주먹밥,S보리차,알리오올리오스파게티,애호박두부젓국찌개,토마토치즈범벅,진미채초무침,배추김치,종료,14
258,시작,B약과,B수제블루베리우유,B과일샐러드(요거트드레싱),S사과(35g),S블루베리고구마샐러드,검정콩밥(55),얼갈이배추국,매콤낙지채소볶음,건취나물간장볶음,오이소박이김치,S(우유제외)토마토스파게티,S보리차,검정콩밥(55),유부쑥갓맑은국,삼치구이+양념장,매쉬드포테이토,배추김치,종료,14
259,시작,B으깬견과류고구마샐러드(요거트),B(우유제외)수제바나나두유,B블루베리고구마샐러드,S복숭아(60g),S사과(100g),현미밥(55),동태살무국,닭가슴살고구마볶음,머위나물,오이소박이김치,S(우유제외)토마토스파게티,S코코아,현미밥(55),오징어숙주국,소고기파인애플볶음,건취나물간장볶음,파김치,종료,14
260,시작,B크로와상,B요구르트,B복숭아(80g),S수박화채,S멜론(100g),보리밥(55),애호박두부젓국,오징어채소볶음,해초볶음,배추김치,S찐고구마,S보리차,보리밥(55),다슬기된장국,닭가슴살고구마볶음,미역줄기채소볶음,배추김치,종료,13

In [23]:
np.mean(new_df.nutrient_score), np.mean(real_df.nutrient_score)

(13.651340996168582, 13.78544061302682)

In [19]:
variance_score = 0


new = new_df[new_df.columns[1:18]]
real = real_df[real_df.columns[1:18]]

for i in range(len(new)):
    for j in new.columns:
        
        if new.iloc[i][j] != real.iloc[i][j]:
            variance_score += 1
            
            
variance_score = variance_score/(len(new)*len(new.columns))

In [20]:
variance_score

0.028397565922920892

In [21]:
new_df.to_excel('6~8세, 남, 간편식_buffer60_change20_epoch=30000_lr=0.0005_beta14_syn15.xlsx')

In [22]:
real_df.to_excel('6~8세, 남, 간편식_buffer60_change20_epoch=30000_lr=0.0005_beta14_syn15_target.xlsx')