In [188]:
import pandas as pd 
import numpy as np

In [189]:
db_35 = pd.read_csv('updated_nutrition_db(3~5)_생성_231017.csv', encoding = 'cp949')
db_35

,name,weight,Energy,Protein,Fat,Carbohydrate,TotalDietaryFiber,Calcium,Iron,Sodium,...,rice_type15,rice_type16,rice_type17,rice_type18,rice_type19,rice_type20,rice_type21,rice_type22,rice_type23,rice_type24
0,B찐고구마(70g),70.0,118.30,0.7490,0.10500,28.6440,2.94,11.900,0.29400,4.900,...,0,0,0,0,0,0,0,0,0,0
1,B군고구마(70g),70.0,132.30,0.7070,0.11200,32.1720,3.29,11.900,0.39200,7.000,...,0,0,0,0,0,0,0,0,0,0
2,B삶은고구마(70g),70.0,118.30,0.7490,0.10500,28.6440,2.94,11.900,0.29400,4.900,...,0,0,0,0,0,0,0,0,0,0
3,B찐감자(140g),140.0,112.00,2.9540,0.12600,25.4380,2.24,14.000,0.67200,2.800,...,0,0,0,0,0,0,0,0,0,0
4,B삶은감자(140g),140.0,107.80,2.8980,0.11200,24.3460,2.24,11.200,0.91000,1.400,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,총각김치,20.0,8.20,0.4040,0.04000,1.5780,0.62,8.400,0.13400,138.400,...,0,0,0,0,0,0,0,0,0,0
3184,콜라비나박김치,20.0,2.90,0.1500,0.01200,0.6430,0.36,5.400,0.03700,42.800,...,0,0,0,0,0,0,0,0,0,0
3185,파김치,20.0,9.80,0.5000,0.11600,1.7020,0.92,12.000,0.14600,131.000,...,0,0,0,0,0,0,0,0,0,0
3186,파프리카피클,21.2,6.94,0.1681,0.02505,1.7385,0.29,1.415,0.06805,67.204,...,0,0,0,0,0,0,0,0,0,0
3187,Empty,0.0,0.00,0.0000,0.00000,0.0000,0.00,0.000,0.00000,0.000,...,0,0,0,0,0,0,0,0,0,0

In [205]:
diet_35_mor_s = pd.read_csv('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(업데이트, 0925)/어린이ABC_3-5세DB/gen_diet_35_아침간편식_밥+일품(4000).csv', encoding = 'cp949', header = None).T
diet_35_mor = pd.read_csv('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(업데이트, 0925)/어린이ABC_3-5세DB/gen_diet_35_아침간편식_밥2(4000).csv', encoding = 'cp949', header = None).T
diet_35_s_r = pd.read_csv('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(업데이트, 0925)/어린이ABC_3-5세DB/gen_diet_35_아침일반식_밥2+일품밥(2000).csv', encoding = 'cp949', header = None).T
diet_35_s_n = pd.read_csv('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(업데이트, 0925)/어린이ABC_3-5세DB/gen_diet_35_아침일반식_밥2+일품국(4000).csv', encoding = 'cp949', header = None).T
diet_35 = pd.read_csv('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(업데이트, 0925)/어린이ABC_3-5세DB/gen_diet_35_아침일반식_밥3(2000).csv', encoding = 'cp949', header = None).T

In [191]:
diet_35_mor

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,x[462],x[927],x[3239],x[2461],x[3237],x[422],x[185],x[2733],x[862],x[926],x[1366],x[390],x[719],x[1480],x[446],x[2221],x[2205]
1,x[174],x[409],x[1623],x[3247],x[663],x[893],x[400],x[2012],x[1492],x[2856],x[1861],x[462],x[2090],x[872],x[442],x[1038],x[3243]
2,x[905],x[1464],x[283],x[462],x[2746],x[3237],x[422],x[2854],x[1768],x[380],x[1958],x[719],x[3235],x[446],x[837],x[2230],x[1049]
3,x[434],x[3239],x[185],x[409],x[1623],x[3247],x[992],x[804],x[743],x[1649],x[2002],x[2274],x[920],x[2423],x[2527],x[462],x[363]
4,x[422],x[3243],x[3195],x[385],x[862],x[1768],x[174],x[3235],x[446],x[663],x[2221],x[1067],x[1454],x[1861],x[2036],x[462],x[995]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,x[1768],x[380],x[3235],x[446],x[837],x[663],x[986],x[2848],x[1058],x[2221],x[2634],x[2036],x[462],x[1510],x[3237],x[422],x[185]
3996,x[3247],x[1592],x[21],x[1047],x[2782],x[3027],x[462],x[975],x[2459],x[3239],x[442],x[862],x[1366],x[409],x[2732],x[390],x[719]
3997,x[2221],x[2054],x[462],x[1510],x[1526],x[2461],x[422],x[185],x[3243],x[2579],x[380],x[977],x[907],x[446],x[837],x[663],x[3242]
3998,x[1799],x[382],x[1477],x[462],x[998],x[3239],x[1070],x[2746],x[2854],x[442],x[421],x[862],x[1366],x[174],x[2732],x[719],x[3247]
3999,x[3237],x[422],x[872],x[2789],x[1768],x[173],x[3235],x[446],x[2524],x[1592],x[663],x[377],x[2221],x[1047],x[2054],x[462],x[975]

In [206]:
def change_int(df):

    import re

    for i in range(len(df.columns)):
        df[i] = df[i].apply(lambda x: re.findall('\d+', x)[0])

    return df

In [207]:
diet_35_mor_s = change_int(diet_35_mor_s)
diet_35_mor = change_int(diet_35_mor)
diet_35_s_r = change_int(diet_35_s_r)
diet_35_s_n = change_int(diet_35_s_n)
diet_35 = change_int(diet_35)

In [156]:
diet_35_s_n = change_int(diet_35_s_n)

In [146]:
diet_35_mor

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,462,927,3239,2461,3237,422,185,2733,862,926,1366,390,719,1480,446,2221,2205
1,174,409,1623,3247,663,893,400,2012,1492,2856,1861,462,2090,872,442,1038,3243
2,905,1464,283,462,2746,3237,422,2854,1768,380,1958,719,3235,446,837,2230,1049
3,434,3239,185,409,1623,3247,992,804,743,1649,2002,2274,920,2423,2527,462,363
4,422,3243,3195,385,862,1768,174,3235,446,663,2221,1067,1454,1861,2036,462,995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1768,380,3235,446,837,663,986,2848,1058,2221,2634,2036,462,1510,3237,422,185
3996,3247,1592,21,1047,2782,3027,462,975,2459,3239,442,862,1366,409,2732,390,719
3997,2221,2054,462,1510,1526,2461,422,185,3243,2579,380,977,907,446,837,663,3242
3998,1799,382,1477,462,998,3239,1070,2746,2854,442,421,862,1366,174,2732,719,3247
3999,3237,422,872,2789,1768,173,3235,446,2524,1592,663,377,2221,1047,2054,462,975

In [139]:
#아침간편식_밥2

# index 정리: 

#breakfast1_cal = 0
#breakfast2_liq = 1
#breakfast3_sal = 2

#snack1_mor_fru = 3
#snack2_mor_milk = 4

#rice = 5,12 
#soup = 6,13 # 
#side_dish1 = 7,14
#side_dish2 = 8,15
# #kimchi = 9,16

#snack3_noon_cal = 10
#snack4_noon_liq = 11

In [147]:
def index_to_food_mor(db, df):

    new_df = []

    for j in range(len(df)):
        l = [None]*17
        
        for i in range(len(l)):
            if db['rice'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[5] is None:
                    l[5] = db['name'][db.index == int(df[i][j])-1].values[0]
                else:
                    l[12] = db['name'][db.index == int(df[i][j])-1].values[0]

            elif db['soup'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[6] is None:
                    l[6] = db['name'][db.index == int(df[i][j])-1].values[0]
                else:
                    l[13] = db['name'][db.index == int(df[i][j])-1].values[0]

            elif db['kimchi'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[9] is None:
                    l[9] = db['name'][db.index == int(df[i][j])-1].values[0]
                else: 
                    l[16] = db['name'][db.index == int(df[i][j])-1].values[0]

            elif db['breakfast1_cal'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[0] is None:
                    l[0] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['breakfast2_liq'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[1] is None:
                    l[1] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['breakfast3_sal'][db.index == int(df[i][j])-1].values[0] == 1:        
                if l[2] is None:
                    l[2] = db['name'][db.index == int(df[i][j])-1].values[0]

            elif db['side_dish1'][db.index == int(df[i][j])-1].values[0] == 1: # side_dish1
                if l[7] is None:
                    l[7] = db['name'][db.index == int(df[i][j])-1].values[0]
                else: 
                    l[14] = db['name'][db.index == int(df[i][j])-1].values[0]

            
            elif db['side_dish2'][db.index == int(df[i][j])-1].values[0] == 1: # side_dish2
                if l[8] is None:
                    l[8] = db['name'][db.index == int(df[i][j])-1].values[0]
                else:
                    l[15] = db['name'][db.index == int(df[i][j])-1].values[0]


            elif db['snack1_mor_fru'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[3] is None:
                    l[3] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['snack2_mor_milk'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[4] is None:
                    l[4] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['snack3_noon_cal'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[10] is None:
                    l[10] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['snack4_noon_liq'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[11] is None:
                    l[11] = db['name'][db.index == int(df[i][j])-1].values[0]
        
        new_df.append(l)

    return pd.DataFrame(new_df)

In [148]:
diet_35_mor  = index_to_food_mor(db_35, diet_35_mor)
diet_35_mor

IndexError: index 0 is out of bounds for axis 0 with size 0

In [18]:
diet_35_mor.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
dtype: int64

In [35]:
diet_35_mor.to_excel('가식단_유아(3~5세)_아침간편식(일품X)_4000개.xlsx', encoding = 'utf-8-sig')

In [11]:
#아침간편식_밥+일품

# index 정리: 

#breakfast1_cal = 0
#breakfast2_liq = 1
#breakfast3_sal = 2

#snack1_mor_fru = 3
#snack2_mor_milk = 4

#special = 5
# if special_soup_needed = 1:
    # possible_with_speical = 6

# else:
    # empty = 6
    
#rice = 12
#soup = 13 # 
#side_dish1 = 7,14
#side_dish2 = 8,15
# #kimchi = 9,16

#snack3_noon_cal = 10
#snack4_noon_liq = 11

In [149]:
def index_to_food_mor_s(db, df):

    new_df = []

    for j in range(len(df)):
        l = [None]*17
        special_soup_needed = 0
        
        for i in range(len(l)):
            
            if db['rice'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[12] is None:
                    l[12] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif (db['special'][db.index == int(df[i][j])-1].values[0] == 1):
                l[5] = db['name'][db.index == int(df[i][j])-1].values[0]
            
            elif db['soup'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[6] is None:
                    if (db['possible_with_special'][db.index == int(df[i][j])-1].values[0] == 1):
                        l[6] = db['name'][db.index == int(df[i][j])-1].values[0]
                    else:
                        l[13] = db['name'][db.index == int(df[i][j])-1].values[0]
                        
                else:
                    l[13] = db['name'][db.index == int(df[i][j])-1].values[0]

            elif db['kimchi'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[9] is None:
                    l[9] = db['name'][db.index == int(df[i][j])-1].values[0]
                else: 
                    l[16] = db['name'][db.index == int(df[i][j])-1].values[0]

            elif db['breakfast1_cal'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[0] is None:
                    l[0] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['breakfast2_liq'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[1] is None:
                    l[1] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['breakfast3_sal'][db.index == int(df[i][j])-1].values[0] == 1:        
                if l[2] is None:
                    l[2] = db['name'][db.index == int(df[i][j])-1].values[0]

            elif db['side_dish1'][db.index == int(df[i][j])-1].values[0] == 1: # side_dish1
                if l[7] is None:
                    l[7] = db['name'][db.index == int(df[i][j])-1].values[0]
                else: 
                    l[14] = db['name'][db.index == int(df[i][j])-1].values[0]
            
            elif db['side_dish2'][db.index == int(df[i][j])-1].values[0] == 1: # side_dish2
                if l[8] is None:
                    l[8] = db['name'][db.index == int(df[i][j])-1].values[0]
                else:
                    l[15] = db['name'][db.index == int(df[i][j])-1].values[0]


            elif db['snack1_mor_fru'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[3] is None:
                    l[3] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['snack2_mor_milk'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[4] is None:
                    l[4] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['snack3_noon_cal'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[10] is None:
                    l[10] = db['name'][db.index == int(df[i][j])-1].values[0]
                    
            elif db['snack4_noon_liq'][db.index == int(df[i][j])-1].values[0] == 1:
                if l[11] is None:
                    l[11] = db['name'][db.index == int(df[i][j])-1].values[0]
        
        new_df.append(l)

    return pd.DataFrame(new_df)

In [150]:
diet_35_mor_s  = index_to_food_mor_s(db_35, diet_35_mor_s)
diet_35_mor_s

IndexError: index 0 is out of bounds for axis 0 with size 0

In [21]:
diet_35_mor_s.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
dtype: int64

In [40]:
diet_35_mor_s.to_excel('가식단_유아(3~5세)_아침간편식(일품밥)_4000.xlsx', encoding = 'utf-8-sig')

In [15]:
db_35.columns

Index(['name', 'weight', 'Energy', 'Protein', 'Fat', 'Carbohydrate',
       'TotalDietaryFiber', 'Calcium', 'Iron', 'Sodium', 'Retinol',
       'β-Carotene', 'VitaminA', 'Thiamin', 'Riboflavin', 'VitaminC',
       'VitaminD', 'Linoleic', 'alinolenic', 'breakfast1_cal',
       'breakfast2_liq', 'breakfast3_sal', 'snack1_mor_fru', 'snack2_mor_milk',
       'snack3_noon_cal', 'snack4_noon_liq', 'rice', 'special', 'soup',
       'kimchi', 'special_soup_needed', 'special_soup_notneeded',
       'vegitable_soup', 'nonvegitable_soup', 'possible_with_special',
       'morning_soup_comb1', 'morning_soup_comb2', 'morning_soup_comb3',
       'side_dish1', 'side_dish2', 'empty', 'rice_type1', 'rice_type2',
       'rice_type3', 'rice_type4', 'rice_type5', 'rice_type6', 'rice_type7',
       'rice_type8', 'rice_type9', 'rice_type10', 'rice_type11', 'rice_type12',
       'rice_type13', 'rice_type14', 'rice_type15', 'rice_type16',
       'rice_type17', 'rice_type18', 'rice_type19', 'rice_type20',
       'rice_type21', 'rice_type22', 'rice_type23', 'rice_type24'],
      dtype='object')

In [53]:
diet_35

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,446,663,1351,2222,986,1058,1572,1853,1931,3218,462,3239,3237,1668,862,475,987
1,934,1539,743,2747,1659,462,2746,844,2213,2564,3069,1366,456,1078,932,3247,3235
2,1514,2623,1961,819,462,3237,1055,983,1922,569,911,2859,1592,457,1885,1538,3236
3,3232,1623,2321,3247,446,663,904,1477,1931,2423,974,462,805,2461,1366,2366,1048
4,961,1811,2222,2462,1104,3234,3218,1667,1032,462,3239,454,1668,2213,826,1357,719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3239,2553,456,3132,3232,2946,849,1649,1047,1689,1477,1853,2953,784,974,462,975
3996,846,925,724,462,443,2609,2061,2461,3237,1527,2025,1623,1511,3235,1069,997,2221
3997,1024,1577,3048,1724,1852,1096,446,1477,2953,3234,2527,462,3239,872,2708,952,591
3998,2321,3247,663,1479,1573,2051,1003,3218,462,805,2461,3240,1366,931,456,929,2366
3999,1638,2952,1697,1048,3070,3235,446,849,1351,2221,904,1931,496,724,974,462,3239

In [70]:
a = diet_35.iloc[0]
b= [i for i in list(diet_35.iloc[0]) if db_35['snack4_noon_liq'][db_35.index == int(i)-1].values[0] == 1]
b

['862']

In [ ]:
[ '987']

In [72]:
db_35[db_35.index == int('475')-1].values[0]

array(['S두유(200ml)2', 200.0, 124.0, 6.02, 7.84, 6.84, 1.4, 160.0, 1.12,
       144.0, 0.0, 0.0, 0.0, 0.116, 0.116, 19.58, 3.16, 3552.36, 525.24,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=object)

In [33]:
list(diet_35.iloc[0])

['446',
 '663',
 '1351',
 '2222',
 '986',
 '1058',
 '1572',
 '1853',
 '1931',
 '3218',
 '462',
 '3239',
 '3237',
 '1668',
 '862',
 '475',
 '987']

In [284]:
def index_to_food(db, df):
    
    new_df = []
    
    for j in range(len(df)):
        print(j)
        l = [None]*17
        
        side_dish1 = [i for i in list(df.iloc[j]) if db['side_dish1'][db.index == int(i)-1].values[0] == 1]
        side_dish2 = [i for i in list(df.iloc[j]) if db['side_dish2'][db.index == int(i)-1].values[0] == 1]
        vegitable_soup = [i for i in list(df.iloc[j]) if db['vegitable_soup'][db.index == int(i)-1].values[0] == 1]
        soup = [i for i in list(df.iloc[j]) if db_35['soup'][db.index == int(i)-1].values[0] == 1]
        non_vegi_soup = [i for i in soup if i not in vegitable_soup]
    
        vegi_label = []
        dish_label = []

        for i in soup:
            if db['vegitable_soup'][db.index == int(i)-1].values[0] == 1:
                vegi_label.append(1)
            else: 
                vegi_label.append(0)

        if len(side_dish1) > len(side_dish2):
            
            for i in side_dish1:
                if db['morning_soup_comb1'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(1)
                elif db['morning_soup_comb2'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(2)
                else:
                    dish_label.append(3)
                    
            if len([i for i in vegi_label if i == 1]) == 0: # vegi가 없는 경우
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]
                
            else:
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                
                if db['vegitable_soup'][db.index == int(soup[0])-1].values[0] == 1: #vegi 인 경우
                    
                    if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                        if len([i for i in dish_label if i == 2]) == 3: ## morning_side2만 있는 경우
                            
                            #국 재배치
                            
                            l[1] = db['name'][db.index == int(soup[vegi_label.index(0)])-1].values[0]
                            
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]
                        
                        else:
                    
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(3)])-1].values[0]
                    else:
                        l[2] = db['name'][db.index == int(side_dish1[dish_label.index(1)])-1].values[0]
                
                else: # vegi가 아닌 경우
                    
                    if len([i for i in dish_label if i == 2]) == 0: #morning_side2가 없는 경우
                        
                        #국부터 재배치 vegi인걸로
                        
                        l[1] = db_35['name'][db.index == int(soup[vegi_label.index(1)])-1].values[0]
                        
                        if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(3)])-1].values[0] 
                        else:
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(1)])-1].values[0]
                    
                    else:
                            
                        l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]
                    
                            
            rest_foods = [i for i in list(df.iloc[j]) if (i != str(db[db.name == l[1]].index[0]+1)) and (i != str(db[db.name == l[2]].index[0]+1))]
                    
                    
        else: 
            
            for i in side_dish2:
                if db['morning_soup_comb1'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(1)
                elif db['morning_soup_comb2'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(2)
                elif db['morning_soup_comb3'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(3)
            
            
            if len([i for i in vegi_label if i == 1]) == 0: # vegi가 없는 경우
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0]
                
            else:
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                
                if db['vegitable_soup'][db.index == int(soup[0])-1].values[0] == 1: #vegi 인 경우
                    
                    if len([i for i in dish_label if i == 1]) == 0: #morning_side1이 없는 경우
                    
                        if len([i for i in dish_label if i == 2]) == 3: ## morning_side2만 있는 경우
                            
                            #국 재배치
                            
                            l[1] = db['name'][db.index == int(soup[vegi_label.index(0)])-1].values[0]
                            
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0]
                        
                        else:
                    
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(3)])-1].values[0]#여기
                    else:
                        l[2] = db['name'][db.index == int(side_dish2[dish_label.index(1)])-1].values[0]
                
                else: # vegi가 아닌 경우
                    
                    if len([i for i in dish_label if i == 2]) == 0: #morning_side2가 없는 경우
                        
                        #국부터 재배치 vegi인걸로
                        
                        l[1] = db_35['name'][db.index == int(soup[vegi_label.index(1)])-1].values[0]
                        
                        if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(3)])-1].values[0] 
                        else:
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(1)])-1].values[0]
                    
                    else:
                            
                        l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0] 
                    
            rest_foods = [i for i in list(df.iloc[j]) if (i != str(db[db.name == l[1]].index[0]+1)) and (i != str(db[db.name == l[2]].index[0]+1))]
                    
        for i in range(len(rest_foods)):
            if db['rice'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[0] is None:
                    l[0] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                elif l[5] is None:
                    l[5] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else:
                    l[12] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            if db['soup'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[6] is None:
                    l[6] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else:
                    l[13] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif db['kimchi'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[9] is None:
                    l[9] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else: 
                    l[16] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif db['side_dish1'][db.index == int(rest_foods[i])-1].values[0] == 1: # side_dish1
                if l[7] is None:
                    l[7] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else: 
                    l[14] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif db['side_dish2'][db.index == int(rest_foods[i])-1].values[0] == 1: # side_dish2
                if l[8] is None:
                    l[8] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else:
                    l[15] = db['name'][db.index == int(rest_foods[i])-1].values[0] 
                        
                
            elif db['snack1_mor_fru'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[3] is None:
                    l[3] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack2_mor_milk'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[4] is None:
                    l[4] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack3_noon_cal'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[10] is None:
                    l[10] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack4_noon_liq'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[11] is None:
                    l[11] = db['name'][db.index == int(rest_foods[i])-1].values[0]
        
        new_df.append(l)
                
    return pd.DataFrame(new_df)

In [285]:
diet_35_rice3 = index_to_food(db_35, diet_35)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999

In [286]:
diet_35_rice3

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,밤콩밥,새우살애호박국,팽이버섯볶음,S오이스틱,S우유(200ml)2,밤콩밥,오징어숙주국,양배추맛살나물,파래무채무침,비트초절이,S로제스파게티,S(우유제외)호두두부쉐이크(150ml),밤콩밥,만두국,찐만두,가지구이무침,배추김치
1,감자밥(40),떡만두국,아욱나물무침,S자두(50g),S우유(200ml)2,감자밥,미소된장국,사각어묵볶음,양념가지찜,콜라비나박김치,S(우유제외)알리오올리오스파게티,S(우유제외)블루베리바나나쉐이크(200ml),감자밥,미소장국,오리훈제구이,애호박나물,단배추물김치
2,쌀밥(추가),만두국,동초무침,S오이스틱,S우유(200ml)2,쌀밥,새우살무국,찐만두,건새우애호박볶음,동치미,S샌드위치(40g),S둥글레차(200ml),쌀밥(추가),두부감자국,참치볶음,과일샐러드(요거트드레싱),배추김치
3,율무밥(30),양파당면국,브로콜리오징어무침,S포도(50g),S우유(200ml)2,율무밥(30),떡만두국,어묵맛살볶음,양배추무침,비트초절이,S김가루주먹밥,S고구마쉐이크(100ml),율무밥(30),숙주당면국,으깬두부채소전,콘샐러드,열무김치
4,옥수수밥,두부젓국찌개,양념가지찜,S복숭아(백도)-50g,S우유(200ml)2,옥수수밥(30),오징어숙주국,마카로니콘샐러드,과일샐러드(요거트드레싱),배추김치,S밥새우주먹밥,S블루베리바나나쉐이크(200ml),옥수수밥(30),감자다시마국,두부케첩조림,콩조림,단배추물김치
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,검정콩밥(40),떡만두국,양배추맛살나물,S오이스틱,S우유(200ml)2,검정콩밥,감자다시마국,소고기브로콜리볶음,팽이버섯볶음,콜라비나박김치,S로제스파게티,S토마토주스(100ml),검정콩밥,새우살무국,찐만두,건취나물간장볶음,백김치
1996,찰현미밥(30),팽이장국,사각어묵볶음,S자두(50g),S우유(200ml)2,찰현미밥(30),오징어숙주국,옥수수치즈전,양념가지찜,비트초절이,S미트볼스파게티,S(우유제외)호두두부쉐이크(150ml),찰현미밥,(우유제외)옥수수스프,채소옥수수튀김,치즈감자조림,배추김치
1997,찹쌀보리밥(40),감자다시마국,소고기브로콜리볶음,S오이스틱,S우유(200ml)2,찹쌀보리밥(40),사골파국,찐만두,감자어묵볶음,콜라비나박김치,S로제스파게티,S둥글레차(200ml),찹쌀보리밥(40),닭살당면국,으깬두부채소전,팽이버섯볶음,백김치
1998,잡곡밥,미소된장국,과일샐러드(요거트드레싱),S자두(50g),S우유(200ml)2,잡곡밥,만두국,주꾸미채소간장볶음,콩나물무침,비트초절이,S크랜베리찹쌀케이크,S오렌지주스(무가당)(200ml),잡곡밥(30),떡만두국,두부케첩조림,배무생채,단배추물김치
1999,찹쌀현미밥(30),새우살무국,고구마엿장조림,S포도(50g),S우유(200ml)2,찹쌀현미밥(30),감자다시마국,찐만두,동초무침,열무물김치,S(우유제외)알리오올리오스파게티,S(우유제외)호두두부쉐이크(150ml),찹쌀현미밥(30),오징어숙주국,브로콜리오징어무침,감자어묵볶음,콜라비나박김치

In [288]:
diet_35_rice3.to_excel('가식단_유아(3~5세)_아침일반식(밥3)_2000개.xlsx', encoding = 'utf-8-sig')

In [ ]:
#아침일반식_밥3

# index 정리: 

#snack1_mor_fru = 3
#snack2_mor_milk = 4

#rice = 0,5,12 
#soup = 1,6,13 
#morning_side = 2

#vegitable_soup == morning_soup_comb1

#side_dish1 = 7,14
#side_dish2 = 8,15
#kimchi = 9,16

#snack3_noon_cal = 10
#snack4_noon_liq = 11

In [292]:
db_35.columns

Index(['name', 'weight', 'Energy', 'Protein', 'Fat', 'Carbohydrate',
       'TotalDietaryFiber', 'Calcium', 'Iron', 'Sodium', 'Retinol',
       'β-Carotene', 'VitaminA', 'Thiamin', 'Riboflavin', 'VitaminC',
       'VitaminD', 'Linoleic', 'alinolenic', 'breakfast1_cal',
       'breakfast2_liq', 'breakfast3_sal', 'snack1_mor_fru', 'snack2_mor_milk',
       'snack3_noon_cal', 'snack4_noon_liq', 'rice', 'special', 'soup',
       'kimchi', 'special_soup_needed', 'special_soup_notneeded',
       'vegitable_soup', 'nonvegitable_soup', 'possible_with_special',
       'morning_soup_comb1', 'morning_soup_comb2', 'morning_soup_comb3',
       'side_dish1', 'side_dish2', 'empty', 'rice_type1', 'rice_type2',
       'rice_type3', 'rice_type4', 'rice_type5', 'rice_type6', 'rice_type7',
       'rice_type8', 'rice_type9', 'rice_type10', 'rice_type11', 'rice_type12',
       'rice_type13', 'rice_type14', 'rice_type15', 'rice_type16',
       'rice_type17', 'rice_type18', 'rice_type19', 'rice_type20',
       'rice_type21', 'rice_type22', 'rice_type23', 'rice_type24'],
      dtype='object')

In [289]:
def index_to_food2(db, df):
    
    new_df = []
    
    for j in range(1):#len(d)f):
        l = [None]*17
        
        side_dish1 = [i for i in list(df.iloc[j]) if db['side_dish1'][db.index == int(i)-1].values[0] == 1]
        side_dish2 = [i for i in list(df.iloc[j]) if db['side_dish2'][db.index == int(i)-1].values[0] == 1]
        vegitable_soup = [i for i in list(df.iloc[j]) if db['vegitable_soup'][db.index == int(i)-1].values[0] == 1]
        soup = [i for i in list(df.iloc[j]) if (db_35['soup'][db.index == int(i)-1].values[0] == 1) and (db_35['possible_with_special'][db.index == int(i)-1].values[0] == 0)]
        non_vegi_soup = [i for i in soup if i not in vegitable_soup]
    
        vegi_label = []
        dish_label = []

        for i in soup:
            if db['vegitable_soup'][db.index == int(i)-1].values[0] == 1:
                vegi_label.append(1)
            else: 
                vegi_label.append(0)

        if len(side_dish1) > len(side_dish2):
            
            for i in side_dish1:
                if db['morning_soup_comb1'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(1)
                elif db['morning_soup_comb2'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(2)
                else:
                    dish_label.append(3)
                    
            if len([i for i in vegi_label if i == 1]) == 0: # vegi가 없는 경우
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0] 
                
                if len([i for i in side_dish1 if db['morning_soup_comb2'][db.index==int(i)-1]==1]) > 0: 
                    l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]  #여기
                else:
                    l[1] = db['name'][db.index == int(soup[1])-1].values[0]
                
            else:
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                
                if db['vegitable_soup'][db.index == int(soup[0])-1].values[0] == 1: #vegi 인 경우
                    
                    if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                        if len([i for i in dish_label if i == 2]) == 3: ## morning_side2만 있는 경우
                            
                            #국 재배치
                            
                            l[1] = db['name'][db.index == int(soup[vegi_label.index(0)])-1].values[0]
                            
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]
                        
                        else:
                    
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(3)])-1].values[0]
                    else:
                        l[2] = db['name'][db.index == int(side_dish1[dish_label.index(1)])-1].values[0]
                
                else: # vegi가 아닌 경우
                    
                    if len([i for i in dish_label if i == 2]) == 0: #morning_side2가 없는 경우
                        
                        #국부터 재배치 vegi인걸로
                        
                        l[1] = db_35['name'][db.index == int(soup[vegi_label.index(1)])-1].values[0]
                        
                        if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(3)])-1].values[0]
                        else:
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(1)])-1].values[0]
                    
                    else:
                            
                        l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]
                    
                            
            rest_foods = [i for i in list(df.iloc[j]) if (i != str(db[db.name == l[1]].index[0]+1)) and (i != str(db[db.name == l[2]].index[0]+1))]
                    
                    
        else: 
            
            for i in side_dish2:
                if db['morning_soup_comb1'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(1)
                elif db['morning_soup_comb2'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(2)
                else:
                    dish_label.append(3)
            
            
            if len([i for i in vegi_label if i == 1]) == 0: # vegi가 없는 경우
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0]
                
            else:
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                
                if db['vegitable_soup'][db.index == int(soup[0])-1].values[0] == 1: #vegi 인 경우
                    
                    if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                        if len([i for i in dish_label if i == 2]) == 3: ## morning_side2만 있는 경우
                            
                            #국 재배치
                            
                            l[1] = db['name'][db.index == int(soup[vegi_label.index(0)])-1].values[0]
                            
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0]
                        
                        else:
                    
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(3)])-1].values[0]
                    else:
                        l[2] = db['name'][db.index == int(side_dish2[dish_label.index(1)])-1].values[0]
                
                else: # vegi가 아닌 경우
                    
                    if len([i for i in dish_label if i == 2]) == 0: #morning_side2가 없는 경우
                        
                        #국부터 재배치 vegi인걸로
                        
                        l[1] = db_35['name'][db.index == int(soup[vegi_label.index(1)])-1].values[0]
                        
                        if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(3)])-1].values[0]
                        else:
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(1)])-1].values[0]
                    
                    else:
                            
                        l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0] 
                    
            rest_foods = [i for i in list(df.iloc[j]) if (i != str(db[db.name == l[1]].index[0]+1)) and (i != str(db[db.name == l[2]].index[0]+1))]
            
        print(rest_foods)
        print(l)
                    
        for i in range(len(rest_foods)):
            if db['rice'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[0] is None:
                    l[0] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else:
                    l[12] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif (db['special'][db.index == int(rest_foods[i])-1].values[0] == 1):
                l[5] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                
            elif (db['possible_with_special'][db.index == int(rest_foods[i])-1].values[0] == 1):
                l[6] = db['name'][db.index == int(rest_foods[i])-1].values[0]
            
            elif (db['soup'][db.index == int(rest_foods[i])-1].values[0] == 1) and (db['possible_with_special'][db.index == int(rest_foods[i])-1].values[0] == 0):
            #    if l[6] is None:
            #        if (db['possible_with_special'][db.index == int(rest_foods[i])-1].values[0] == 1):
            #            l[6] = db['name'][db.index == int(rest_foods[i])-1].values[0]
            #        else:
            #            l[13] = db['name'][db.index == int(rest_foods[i])-1].values[0]    
            #    else: 
                l[13] = db['name'][db.index == int(rest_foods[i])-1].values[0]       
                    
            elif db['kimchi'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[9] is None:
                    l[9] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else: 
                    l[16] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif db['side_dish1'][db.index == int(rest_foods[i])-1].values[0] == 1: # side_dish1
                if l[7] is None:
                    l[7] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else: 
                    l[14] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif db['side_dish2'][db.index == int(rest_foods[i])-1].values[0] == 1: # side_dish2
                if l[8] is None:
                    l[8] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else:
                    l[15] = db['name'][db.index == int(rest_foods[i])-1].values[0] 
                        
                
            elif db['snack1_mor_fru'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[3] is None:
                    l[3] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack2_mor_milk'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[4] is None:
                    l[4] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack3_noon_cal'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[10] is None:
                    l[10] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack4_noon_liq'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[11] is None:
                    l[11] = db['name'][db.index == int(rest_foods[i])-1].values[0]
        
        new_df.append(l)
                
    return pd.DataFrame(new_df)

In [258]:
diet_35_s_r.iloc[0]

0     2165
1     1432
2     3177
3     1045
4      456
5     3175
6     1511
7     1608
8     1793
9      683
10     793
11     458
12     900
13    3030
14    1156
15    2399
16    3128
Name: 0, dtype: object

In [259]:
[i for i in list(diet_35_s_r.iloc[0]) if db_35['possible_with_special'][db_35.index == int(i)-1].values[0] == 1]

['1432']

In [277]:
db_35[db_35.index == 1431]

,name,weight,Energy,Protein,Fat,Carbohydrate,TotalDietaryFiber,Calcium,Iron,Sodium,...,rice_type15,rice_type16,rice_type17,rice_type18,rice_type19,rice_type20,rice_type21,rice_type22,rice_type23,rice_type24
1431,맑은장국,10.5,1.465,0.1051,0.00705,0.2968,0.057,3.805,0.15345,30.64,...,0,0,0,0,0,0,0,0,0,0

In [290]:
diet_35_rice2 = index_to_food2(db_35, diet_35_s_r)

ValueError: 2 is not in list

In [276]:
diet_35_rice2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,흑미밥(40),맑은장국,온두부+양념장,S오이스틱,S우유(200ml)2,두부베이컨볶음밥,None,두부떡간장조림,도라지나물(간장),비트초절이,S(우유제외)알리오올리오스파게티,S매실차(100ml),흑미밥(30),어묵국수,검은깨고구마맛탕,건취나물간장볶음,배추김치

In [257]:
diet_35_rice2.isnull().sum()

0       0
1       0
2       0
3       0
4       0
5       0
6     936
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
dtype: int64

In [204]:
diet_35_rice2.to_excel('가식단_유아(3~5세)_아침일반식(밥2+일품밥)_2000개.xlsx', encoding = 'utf-8-sig')

In [238]:
# [밥,국,부찬,간식3,간식3,밥,국,주찬1,부찬1,김치,간식1,간식2,밥,국,주찬2,부찬2,김치]
# index 정리: 
# 간식3: 3, 4
# 간식1: 10
# 간식2: 11
# 밥: 0, 5, 12
# 국: 1, 6, 13
# 주찬: 7, 14
# 부찬: 2, 8, 15
# 김치: 9, 16

In [237]:
def index_to_food3(db, df):
    
    new_df = []
    
    for j in range(len(df)):
        print(j)
        l = [None]*17
        
        side_dish1 = [i for i in list(df.iloc[j]) if db['side_dish1'][db.index == int(i)-1].values[0] == 1]
        side_dish2 = [i for i in list(df.iloc[j]) if db['side_dish2'][db.index == int(i)-1].values[0] == 1]
        vegitable_soup = [i for i in list(df.iloc[j]) if db['vegitable_soup'][db.index == int(i)-1].values[0] == 1]
        soup = [i for i in list(df.iloc[j]) if db_35['soup'][db.index == int(i)-1].values[0] == 1]
        non_vegi_soup = [i for i in soup if i not in vegitable_soup]
    
        vegi_label = []
        dish_label = []

        for i in soup:
            if db['vegitable_soup'][db.index == int(i)-1].values[0] == 1:
                vegi_label.append(1)
            else: 
                vegi_label.append(0)

        if len(side_dish1) > len(side_dish2):
            
            for i in side_dish1:
                if db['morning_soup_comb1'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(1)
                elif db['morning_soup_comb2'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(2)
                else:
                    dish_label.append(3)
                    
            if len([i for i in vegi_label if i == 1]) == 0: # vegi가 없는 경우
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                
                if len([i for i in dish_label if i == 2]) != 0:
                    
                    l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0] #여기
                elif len([i for i in dish_label if i == 3]) != 0:
                    l[2] = db['name'][db.index == int(side_dish1[dish_label.index(3)])-1].values[0]
                else:
                    l[2] = db['name'][db.index == int(side_dish1[dish_label.index(1)])-1].values[0]
                
            else:
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                
                if db['vegitable_soup'][db.index == int(soup[0])-1].values[0] == 1: #vegi 인 경우
                    
                    if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                        if len([i for i in dish_label if i == 2]) == 3: ## morning_side2만 있는 경우
                            
                            #국 재배치
                            
                            l[1] = db['name'][db.index == int(soup[vegi_label.index(0)])-1].values[0] 
                            
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]
                        
                        else:
                    
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(3)])-1].values[0]
                    else:
                        l[2] = db['name'][db.index == int(side_dish1[dish_label.index(1)])-1].values[0]
                
                else: # vegi가 아닌 경우
                    
                    if len([i for i in dish_label if i == 2]) == 0: #morning_side2가 없는 경우
                        
                        #국부터 재배치 vegi인걸로
                        
                        l[1] = db_35['name'][db.index == int(soup[vegi_label.index(1)])-1].values[0]
                        
                        if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(3)])-1].values[0] 
                        else:
                            l[2] = db['name'][db.index == int(side_dish1[dish_label.index(1)])-1].values[0]
                    
                    else:
                            
                        l[2] = db['name'][db.index == int(side_dish1[dish_label.index(2)])-1].values[0]
                    
                            
            rest_foods = [i for i in list(df.iloc[j]) if (i != str(db[db.name == l[1]].index[0]+1)) and (i != str(db[db.name == l[2]].index[0]+1))]
                    
                    
        else: 
            
            for i in side_dish2:
                if db['morning_soup_comb1'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(1)
                elif db['morning_soup_comb2'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(2)
                elif db['morning_soup_comb3'][db.index == int(i)-1].values[0] == 1:
                    dish_label.append(3)
            
            
            if len([i for i in vegi_label if i == 1]) == 0: # vegi가 없는 경우
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0]
                
            else:
                
                l[1] = db['name'][db.index == int(soup[0])-1].values[0]
                
                if db['vegitable_soup'][db.index == int(soup[0])-1].values[0] == 1: #vegi 인 경우
                    
                    if len([i for i in dish_label if i == 1]) == 0: #morning_side1이 없는 경우
                    
                        if len([i for i in dish_label if i == 2]) == 3: ## morning_side2만 있는 경우
                            
                            #국 재배치
                            
                            if len([i for i in vegi_label if i == 0]) != 0:
                            
                                l[1] = db['name'][db.index == int(soup[vegi_label.index(0)])-1].values[0] #여기
                            
                            else: 
                                l[1] = db['name'][db.index == int(soup[vegi_label.index(1)])-1].values[0] #여기
                            
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0]
                        
                        else:
                    
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(3)])-1].values[0]
                    else:
                        l[2] = db['name'][db.index == int(side_dish2[dish_label.index(1)])-1].values[0]
                
                else: # vegi가 아닌 경우
                    
                    if len([i for i in dish_label if i == 2]) == 0: #morning_side2가 없는 경우
                        
                        #국부터 재배치 vegi인걸로
                        
                        l[1] = db_35['name'][db.index == int(soup[vegi_label.index(1)])-1].values[0]
                        
                        if len([i for i in dish_label if i == 1]) == 0: #morning_side 1이 없는 경우
                    
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(3)])-1].values[0] 
                        else:
                            l[2] = db['name'][db.index == int(side_dish2[dish_label.index(1)])-1].values[0]
                    
                    else:
                            
                        l[2] = db['name'][db.index == int(side_dish2[dish_label.index(2)])-1].values[0] 
                    
            rest_foods = [i for i in list(df.iloc[j]) if (i != str(db[db.name == l[1]].index[0]+1)) and (i != str(db[db.name == l[2]].index[0]+1))]
    
                    
        for i in range(len(rest_foods)):
            if db['rice'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[0] is None:
                    l[0] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else:
                    l[12] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif (db['empty'][db.index == int(rest_foods[i])-1].values[0] == 1):
                l[6] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                
            elif (db['special'][db.index == int(rest_foods[i])-1].values[0] == 1):
                l[5] = db['name'][db.index == int(rest_foods[i])-1].values[0]
            
            elif db['soup'][db.index == int(rest_foods[i])-1].values[0] == 1:
                l[13] = db['name'][db.index == int(rest_foods[i])-1].values[0]      
                      
                    
            elif db['kimchi'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[9] is None:
                    l[9] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else: 
                    l[16] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif db['side_dish1'][db.index == int(rest_foods[i])-1].values[0] == 1: # side_dish1
                if l[7] is None:
                    l[7] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else: 
                    l[14] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                    
            elif db['side_dish2'][db.index == int(rest_foods[i])-1].values[0] == 1: # side_dish2
                if l[8] is None:
                    l[8] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                else:
                    l[15] = db['name'][db.index == int(rest_foods[i])-1].values[0] 
                        
                
            elif db['snack1_mor_fru'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[3] is None:
                    l[3] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack2_mor_milk'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[4] is None:
                    l[4] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack3_noon_cal'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[10] is None:
                    l[10] = db['name'][db.index == int(rest_foods[i])-1].values[0]
                                
            elif db['snack4_noon_liq'][db.index == int(rest_foods[i])-1].values[0] == 1:
                if l[11] is None:
                    l[11] = db['name'][db.index == int(rest_foods[i])-1].values[0]
        
        new_df.append(l)
                
    return pd.DataFrame(new_df)

In [238]:
diet_35_rice2_n = index_to_food3(db_35, diet_35_s_n)
diet_35_rice2_n

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265
3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
3483
3484
3485
3486
3487
3488
3489
3490
3491
3492
3493
3494
3495
3496
3497
3498
3499
3500
3501
3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
3783
3784
3785
3786
3787
3788
3789
3790
3791
3792
3793
3794
3795
3796
3797
3798
3799
3800
3801
3802
3803
3804
3805
3806
3807
3808
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3821
3822
3823
3824
3825
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3838
3839
3840
3841
3842
3843
3844
3845
3846
3847
3848
3849
3850
3851
3852
3853
3854
3855
3856
3857
3858
3859
3860
3861
3862
3863
3864
3865
3866
3867
3868
3869
3870
3871
3872
3873
3874
3875
3876
3877
3878
3879
3880
3881
3882
3883
3884
3885
3886
3887
3888
3889
3890
3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966
3967
3968
3969
3970
3971
3972
3973
3974
3975
3976
3977
3978
3979
3980
3981
3982
3983
3984
3985
3986
3987
3988
3989
3990
3991
3992
3993
3994
3995
3996
3997
3998
3999

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,수수밥(30),만두국,고구마닭간장조림,S복숭아(백도)-50g,S우유(200ml)2,맛살우동,Empty,크래미유자샐러드,고구마조림,비트초절이,S로제스파게티,S쌀음료(100ml),수수밥(30),오징어무국,마카로니콘샐러드,고구마엿장조림,콜라비나박김치
1,고구마밥(40),수제비아욱국,양념가지찜,S자두(50g),S우유(200ml)2,수제비,Empty,두부채소전,건취나물간장볶음,나박김치,S크랜베리찹쌀케이크,S매실차(100ml),고구마밥(40),떡만두국,찐만두,콩나물무침,배추김치
2,고구마밥(30),미소장국,어묵고구마조림,S포도(50g),S우유(200ml)2,새우튀김우동,Empty,검은깨고구마맛탕,고구마엿장조림,동치미,S(우유제외)알리오올리오스파게티,S쌀음료(100ml),고구마밥(30),만두국,사각어묵볶음,동초무침,비트초절이
3,밤밥(40),오징어무국,두부버섯스테이크,S자두(50g),S우유(200ml)2,맛살우동,Empty,두부채소전,건취나물간장볶음,콜라비나박김치,S미트볼스파게티,S둥글레차(200ml),밤밥(40),떡만두국,애호박생선살찜,오이부추생채,백김치
4,수수밥(30),미소된장국,으깬견과류고구마샐러드(요거트),S포도(50g),S우유(200ml)2,새우튀김우동,Empty,검은깨고구마맛탕,콩나물무침,파프리카피클,S(우유제외)알리오올리오스파게티,S미숫가루,수수밥(30),만두국,볼어묵조림,단호박조림,배추김치
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,고구마밥(30),떡국,크래미유자샐러드,S자두(50g),S우유(200ml)2,새우튀김우동,Empty,찐만두,감자어묵볶음,배추김치,S(우유제외)알리오올리오스파게티,S쌀음료(100ml),고구마밥(30),오징어숙주국,두부채소전,콩나물무침,비트초절이
3996,찹쌀현미밥(30),두부감자국,문어조림,S포도(50g),S우유(200ml)2,맛살우동,Empty,깐쇼새우,건취나물간장볶음,단무지무침,S흑임자떡(40g),S블루베리바나나쉐이크(200ml),찹쌀현미밥(30),만두국,두부버섯스테이크,양념가지찜,백김치
3997,밤밥(30),(우유제외)옥수수스프,볼어묵채소조림,S거봉(50g),S우유(200ml)2,새우튀김우동,Empty,크래미유자샐러드,찐단호박,콜라비나박김치,S(우유제외)알리오올리오스파게티,S매실차(100ml),밤밥(30),오징어무국,마카로니콘샐러드,고구마엿장조림,비트초절이
3998,찹쌀밥,냉이국,견과두부조림,S자두(50g),S우유(200ml)2,맛살우동,Empty,해산물부추전,감자어묵볶음,백김치,S로제스파게티,S포도주스(200ml),찹쌀밥(30),새우살시금치국,찐만두,건새우애호박볶음,배추김치
3999,찹쌀보리밥(30),오징어무국,감자채전,S오이스틱,S우유(200ml)2,새우튀김우동,Empty,소고기브로콜리볶음,건취나물간장볶음,콜라비나박김치,S미트볼스파게티,S오렌지주스(무가당)(200ml),찹쌀보리밥(30),떡만두국,새우깐풍기,도라지나물(간장),비트초절이

In [239]:
diet_35_rice2_n.to_excel('가식단_유아(3~5세)_아침일반식(밥2+일품국).xlsx', encoding = 'utf-8-sig')

In [437]:
import os

file_path='C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(캠프)/Allergy Free식단 0621/6to8/boy/'

files = os.listdir(file_path)
files

['new_diet_6to8_boy_아침간편식_2312.xlsx',
 'new_diet_6to8_boy_아침간편식_2322.xlsx',
 'new_diet_6to8_boy_아침간편식_2329.xlsx',
 'new_diet_6to8_boy_아침간편식_2331.xlsx',
 'new_diet_6to8_boy_아침간편식_2334.xlsx',
 'new_diet_6to8_boy_아침간편식_2338.xlsx',
 'new_diet_6to8_boy_아침일반식_2312.xlsx',
 'new_diet_6to8_boy_아침일반식_2322.xlsx',
 'new_diet_6to8_boy_아침일반식_2329.xlsx',
 'new_diet_6to8_boy_아침일반식_2331.xlsx',
 'new_diet_6to8_boy_아침일반식_2334.xlsx',
 'new_diet_6to8_boy_아침일반식_2338.xlsx']

In [444]:
diets = []
for i in files:
    diets.append(pd.read_excel(file_path+i, index_col = 0))

In [439]:
### 영양소 계산하기 ###

import warnings
warnings.filterwarnings( 'ignore' )

In [456]:
def nutrition_calculte_68_boy(db, df):   
    total_sum = pd.DataFrame()

    cat = ['Energy', 'Protein', 'Fat', 'Carbohydrate', 'Total Dietary', 'Calcium',
       'Iron', 'Sodium', 'Vitamin A', 'Vitamin B1 (Thiamine)',
       'Vitamin B2 (Rivoflavin)', 'Vitamin C', 'Linoleic Acid',
       'Alpha-Linolenic Acid']

    for j in range(len(df)):

        menu_sum = pd.DataFrame(columns = cat)
        count = 0

        for i in range(len(df.columns)):
            menu_sum = menu_sum.append(db[db.name == df[i][j]][cat].iloc[0])

        menu_sum = pd.DataFrame([menu_sum.sum(axis = 0)], columns = cat)
        menu_sum['Carbohydrate_ratio'] = menu_sum['Carbohydrate'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Protein_ratio'] = menu_sum['Protein'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Fat_ratio'] = menu_sum['Fat'].values[0]*9/menu_sum['Energy'].values[0]

        if menu_sum['Energy'][0] >= 1530 and menu_sum['Energy'][0] <= 1870:  # Energy
            menu_sum['Energy_'] = True
            count += 1
        else: 
            menu_sum['Energy_'] = False

        if menu_sum['Protein'][0] >= 26.25:  # Protein
            menu_sum['Protein_'] = True
            count += 1
        else: 
            menu_sum['Protein_'] = False

        if menu_sum['Total Dietary'][0] >= 13 and menu_sum['Total Dietary'][0] <= 25:  # 식이섬유
            menu_sum['Total Dietary_'] = True
            count += 1
        else: 
            menu_sum['Total Dietary_'] = False

        if menu_sum['Vitamin A'][0] >= 337.5 and menu_sum['Vitamin A'][0] <= 562.5: # 비타민 A
            menu_sum['Vitamin A_'] = True
            count += 1
        else: 
            menu_sum['Vitamin A_'] = False

        if menu_sum['Vitamin C'][0] >= 37.5 and menu_sum['Vitamin C'][0] <= 62.5: # 비타민 C
            menu_sum['Vitamin C_'] = True
            count += 1
        else: 
            menu_sum['Vitamin C_'] = False

        if menu_sum['Vitamin B1 (Thiamine)'][0] >= 0.525 and menu_sum['Vitamin B1 (Thiamine)'][0] <= 0.875: # 비타민 B1
            menu_sum['Vitamin B1 (Thiamine)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B1 (Thiamine)_'] = False

        if menu_sum['Vitamin B2 (Rivoflavin)'][0] >= 0.675 and menu_sum['Vitamin B2 (Rivoflavin)'][0] <= 1.125: # 비타민 B2
            menu_sum['Vitamin B2 (Rivoflavin)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B2 (Rivoflavin)_'] = False

        if menu_sum['Calcium'][0] >= 525 and menu_sum['Calcium'][0] <= 875: # 칼슘
            menu_sum['Calcium_'] = True
            count += 1
        else: 
            menu_sum['Calcium_'] = False

        if menu_sum['Iron'][0] >= 6.75 and menu_sum['Iron'][0] <= 11.16: # 철
            menu_sum['Iron_'] = True
            count += 1
        else: 
            menu_sum['Iron_'] = False

        if menu_sum['Sodium'][0] < 1900: # 나트륨
            menu_sum['Sodium_'] = True
            count += 1
        else: 
            menu_sum['Sodium_'] = False

        if menu_sum['Linoleic Acid'][0] <= 11250: # 리놀레산
            menu_sum['Linoleic Acid_'] = True
            count += 1
        else: 
            menu_sum['Linoleic Acid_'] = False

        if  menu_sum['Alpha-Linolenic Acid'][0] <= 1375: # 알파 리놀레산
            menu_sum['Alpha-Linolenic Acid_'] = True
            count += 1
        else: 
            menu_sum['Alpha-Linolenic Acid_'] = False

        if menu_sum['Carbohydrate_ratio'][0] >= 0.55 and menu_sum['Carbohydrate_ratio'][0] <= 0.65: # Carbohydrate ratio
            menu_sum['Carbohydrate_ratio_'] = True
            count += 1
        else: 
            menu_sum['Carbohydrate_ratio_'] = False

        if menu_sum['Protein_ratio'][0] >= 0.07 and menu_sum['Protein_ratio'][0] <= 0.20: # Protein ratio
            menu_sum['Protein_ratio_'] = True
            count += 1
        else: 
            menu_sum['Protein_ratio_'] = False

        if menu_sum['Fat_ratio'][0] >= 0.15 and menu_sum['Fat_ratio'][0] <= 0.30: # Fat ratio
            menu_sum['Fat_ratio_'] = True
            count += 1
        else: 
            menu_sum['Fat_ratio_'] = False
        

        menu_sum['Total_sum'] = count


        total_sum = total_sum.append(menu_sum)
        
    total_sum = total_sum.reset_index(drop = True)

    return pd.concat([df, total_sum], axis = 1)

In [446]:
new_diet = nutrition_calculte_68_boy(db_68, diets[0])
new_diet

,0,1,2,3,4,5,6,7,8,9,...,Vitamin B2 (Rivoflavin)_,Calcium_,Iron_,Sodium_,Linoleic Acid_,Alpha-Linolenic Acid_,Carbohydrate_ratio_,Protein_ratio_,Fat_ratio_,Total_sum
0,B고구마스프,B요구르트,B블루베리고구마샐러드,S복숭아(60g),S멜론(50g),잡곡밥(63),실파장국,라조기,상추초무침,배추김치,...,True,True,True,True,True,True,True,True,True,15
1,B크로와상,B(우유제외)수제바나나두유,B오이스틱,S사과(50g),S멜론(50g),잡곡밥(55),찹쌀옹심이국,매콤오징어볶음,쌈채소,배추김치,...,True,False,True,True,True,True,True,True,True,13
2,B핫케이크,B수제바나나우유,B사과(50g),S과일샐러드(마요네즈),S사과(35g),찹쌀팥밥(63),두부새우젓국,(저염)닭가슴살단호박조림,참치애호박볶음,콜라비나박김치,...,False,True,True,True,True,True,True,True,True,13
3,B생선죽,B고구마쉐이크,B오이스틱,S블루베리(50g),S복숭아(황도)-60g,새우카레볶음밥,콩나물냉국,소고기찹쌀구이,비트무초절임,배추김치,...,True,True,True,True,True,True,True,True,True,13
4,B새우치즈죽,B고구마쉐이크,B배(50g),S복숭아(천도)-80g,S멜론(50g),현미밥(55),대구지리,(저염)갈치조림,오이샐러드,나박김치,...,True,True,True,True,True,True,True,True,True,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,B단호박스프,B고구마쉐이크,B복숭아(백도)-80g,S사과(35g),S복숭아(황도)-80g,잡곡밥(55),실파장국,소고기토마토조림,사과미나리무침,오이소박이김치,...,True,True,True,True,True,True,True,True,True,14
540,B단호박샐러드,B두유(100ml),B멜론(100g),S사과(35g),S복숭아(60g),찹쌀밥(40),해물탕,감자치즈전,양배추오이샐러드,열무물김치,...,True,True,True,True,True,True,True,True,True,14
541,B꿀떡,B두유(100ml),B멜론(50g),S멜론(50g),S참외(50g),찰현미밥(55),팽이장국,매콤낙지채소볶음,과일샐러드(요거트드레싱),열무물김치,...,True,False,True,True,True,True,True,True,True,13
542,B옥수수크림스프,B우유크림스프,B블루베리고구마샐러드,S복숭아(60g),S멜론(50g),잡곡밥(55),실파장국,매콤오징어볶음,진미채초무침,나박김치,...,True,True,True,True,True,True,True,True,True,15
543,B당근치즈스프,B검은콩두유(150ml),B참외(50g),S사과(35g),S복숭아(황도)-80g,완두콩밥(55),달걀국,삼치튀김,상추쌈,열무물김치,...,True,True,True,True,True,True,True,True,True,13

In [470]:
total_sum = []
for i in range(len(new_diet)):
    total_sum.append(np.mean(new_diet[i]['Total_sum']))

In [477]:
total_sum

[13.711397058823529,
 12.286764705882353,
 13.143382352941176,
 13.323529411764707,
 13.238970588235293,
 12.891544117647058,
 13.653979238754324,
 12.622837370242214,
 13.494809688581315,
 13.480968858131488,
 13.328719723183392,
 13.055363321799309]

In [472]:
np.mean(total_sum)

13.186022202998847

In [392]:
new_diet.to_excel('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(캠프)/가식단 0614/0614가식단_소아(6~8세,남)_morning.xlsx', encoding = 'utf-8-sig')

In [473]:
import os

file_path='C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(캠프)/Allergy Free식단 0621/6to8/girl/'

files = os.listdir(file_path)
files

['new_diet_6to8_girl_아침간편식_2302.xlsx',
 'new_diet_6to8_girl_아침간편식_2306.xlsx',
 'new_diet_6to8_girl_아침간편식_2338.xlsx',
 'new_diet_6to8_girl_아침간편식_2339.xlsx',
 'new_diet_6to8_girl_아침간편식_2340.xlsx',
 'new_diet_6to8_girl_아침간편식_2341.xlsx',
 'new_diet_6to8_girl_아침간편식_2344.xlsx',
 'new_diet_6to8_girl_아침일반식_2302.xlsx',
 'new_diet_6to8_girl_아침일반식_2306.xlsx',
 'new_diet_6to8_girl_아침일반식_2338.xlsx',
 'new_diet_6to8_girl_아침일반식_2339.xlsx',
 'new_diet_6to8_girl_아침일반식_2340.xlsx',
 'new_diet_6to8_girl_아침일반식_2341.xlsx',
 'new_diet_6to8_girl_아침일반식_2344.xlsx']

In [474]:
diets = []
for i in files:
    diets.append(pd.read_excel(file_path+i, index_col = 0))

In [475]:
def nutrition_calculte_68_girl(db, df):   
    total_sum = pd.DataFrame()

    cat = ['Energy', 'Protein', 'Fat', 'Carbohydrate', 'Total Dietary', 'Calcium',
       'Iron', 'Sodium', 'Vitamin A', 'Vitamin B1 (Thiamine)',
       'Vitamin B2 (Rivoflavin)', 'Vitamin C', 'Linoleic Acid',
       'Alpha-Linolenic Acid']

    for j in range(len(df)):

        menu_sum = pd.DataFrame(columns = cat)
        count = 0

        for i in range(len(df.columns)):
            menu_sum = menu_sum.append(db[db.name == df[i][j]][cat].iloc[0])

        menu_sum = pd.DataFrame([menu_sum.sum(axis = 0)], columns = cat)
        menu_sum['Carbohydrate_ratio'] = menu_sum['Carbohydrate'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Protein_ratio'] = menu_sum['Protein'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Fat_ratio'] = menu_sum['Fat'].values[0]*9/menu_sum['Energy'].values[0]

        if menu_sum['Energy'][0] >= 1350 and menu_sum['Energy'][0] <= 1650:  # Energy
            menu_sum['Energy_'] = True
            count += 1
        else: 
            menu_sum['Energy_'] = False

        if menu_sum['Protein'][0] >= 26.25:  # Protein
            menu_sum['Protein_'] = True
            count += 1
        else: 
            menu_sum['Protein_'] = False

        if menu_sum['Total Dietary'][0] >= 13 and menu_sum['Total Dietary'][0] <= 20:  # 식이섬유
            menu_sum['Total Dietary_'] = True
            count += 1
        else: 
            menu_sum['Total Dietary_'] = False

        if menu_sum['Vitamin A'][0] >= 300 and menu_sum['Vitamin A'][0] <= 500: # 비타민 A
            menu_sum['Vitamin A_'] = True
            count += 1
        else: 
            menu_sum['Vitamin A_'] = False

        if menu_sum['Vitamin C'][0] >= 37.5 and menu_sum['Vitamin C'][0] <= 62.5: # 비타민 C
            menu_sum['Vitamin C_'] = True
            count += 1
        else: 
            menu_sum['Vitamin C_'] = False

        if menu_sum['Vitamin B1 (Thiamine)'][0] >= 0.525 and menu_sum['Vitamin B1 (Thiamine)'][0] <= 0.875: # 비타민 B1
            menu_sum['Vitamin B1 (Thiamine)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B1 (Thiamine)_'] = False

        if menu_sum['Vitamin B2 (Rivoflavin)'][0] >= 0.6 and menu_sum['Vitamin B2 (Rivoflavin)'][0] <= 1: # 비타민 B2
            menu_sum['Vitamin B2 (Rivoflavin)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B2 (Rivoflavin)_'] = False

        if menu_sum['Calcium'][0] >= 525 and menu_sum['Calcium'][0] <= 875: # 칼슘
            menu_sum['Calcium_'] = True
            count += 1
        else: 
            menu_sum['Calcium_'] = False

        if menu_sum['Iron'][0] >= 6.75 and menu_sum['Iron'][0] <= 11.16: # 철
            menu_sum['Iron_'] = True
            count += 1
        else: 
            menu_sum['Iron_'] = False

        if menu_sum['Sodium'][0] < 1900: # 나트륨
            menu_sum['Sodium_'] = True
            count += 1
        else: 
            menu_sum['Sodium_'] = False

        if menu_sum['Linoleic Acid'][0] <= 8750: # 리놀레산
            menu_sum['Linoleic Acid_'] = True
            count += 1
        else: 
            menu_sum['Linoleic Acid_'] = False

        if menu_sum['Alpha-Linolenic Acid'][0] <= 1000: # 알파 리놀레산
            menu_sum['Alpha-Linolenic Acid_'] = True
            count += 1
        else: 
            menu_sum['Alpha-Linolenic Acid_'] = False

        if menu_sum['Carbohydrate_ratio'][0] >= 0.55 and menu_sum['Carbohydrate_ratio'][0] <= 0.65: # Carbohydrate ratio
            menu_sum['Carbohydrate_ratio_'] = True
            count += 1
        else: 
            menu_sum['Carbohydrate_ratio_'] = False

        if menu_sum['Protein_ratio'][0] >= 0.07 and menu_sum['Protein_ratio'][0] <= 0.20: # Protein ratio
            menu_sum['Protein_ratio_'] = True
            count += 1
        else: 
            menu_sum['Protein_ratio_'] = False

        if menu_sum['Fat_ratio'][0] >= 0.15 and menu_sum['Fat_ratio'][0] <= 0.30: # Fat ratio
            menu_sum['Fat_ratio_'] = True
            count += 1
        else: 
            menu_sum['Fat_ratio_'] = False
        

        menu_sum['Total_sum'] = count


        total_sum = total_sum.append(menu_sum)
        
    total_sum = total_sum.reset_index(drop = True)

    return pd.concat([df, total_sum], axis = 1)

In [476]:
new_diet = []
for i in range(len(diets)):
    print(i)
    new_diet.append(nutrition_calculte_68_girl(db_68, diets[i]))

0
1
2
3
4
5
6
7
8
9
10
11
12
13

In [478]:
total_sum = []
for i in range(len(new_diet)):
    total_sum.append(np.mean(new_diet[i]['Total_sum']))

In [479]:
total_sum

[12.879310344827585,
 12.593103448275862,
 13.617241379310345,
 13.562068965517241,
 12.344827586206897,
 12.862068965517242,
 13.455172413793104,
 12.460405156537753,
 12.694290976058932,
 13.359116022099448,
 13.342541436464089,
 12.00184162062615,
 12.642725598526704,
 13.121546961325967]

In [480]:
np.mean(total_sum)

12.924018633934809

In [397]:
new_diet = nutrition_calculte_68_girl(db_68, diet_68_girl_mor)
new_diet

,0,1,2,3,4,5,6,7,8,9,...,Vitamin B2 (Rivoflavin)_,Calcium_,Iron_,Sodium_,Linoleic Acid_,Alpha-Linolenic Acid_,Carbohydrate_ratio_,Protein_ratio_,Fat_ratio_,Total_sum
0,B으깬견과류고구마샐러드(요거트),B(우유제외)두유미숫가루,B복숭아(60g),S당근스틱,S복숭아(천도)-80g,잡곡밥(63),유부쑥갓맑은국,(저염)갈치조림,애호박볶음,오이소박이김치,...,True,True,True,True,True,True,True,True,True,15
1,B브로콜리소고기죽,B검은콩두유(100ml),B멜론(50g),S사과(35g),S복숭아(천도)-60g,알리오올리오스파게티,얼갈이맑은국,소고기채소조림,청경채된장무침,파김치,...,True,True,True,True,True,True,True,True,True,15
2,B소고기미역죽,B고구마쉐이크,B복숭아(천도)-60g,S멜론(50g),S수박(100g),수수밥(55),팽이장국,어묵고구마조림,파래무침,석박지,...,True,True,True,True,True,True,True,True,True,15
3,B당근죽,B두유(100ml),B사과(75g),S복숭아(천도)-60g,S자두(50g),새우크림스파게티,안매운김치국,닭가슴살고구마볶음,건새우애호박볶음,비트초절이,...,True,True,True,True,True,True,True,True,True,15
4,B양파치즈스프,B과일연두부스무디,B복숭아(황도)-60g,S멜론(100g),S블루베리(50g),보리밥(55),오징어숙주국,갈치감자조림,우엉볶음,갓김치,...,True,True,True,True,True,True,True,True,True,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,B가래떡구이,B우유(200ml),B복숭아(60g),S사과(35g),S복숭아(황도)-80g,양배추소시지덮밥,안매운김치국,웨지감자,애호박볶음,배추김치,...,True,True,True,True,True,True,True,True,True,15
196,B으깬견과류고구마샐러드(요거트),B(우유제외)수제바나나두유,B참외(50g),S복숭아(60g),S복숭아(천도)-60g,파프리카유부초밥,얼갈이배추국,칠리새우,진미채초무침,열무물김치,...,True,True,True,True,True,True,True,True,True,15
197,B감자죽,B복숭아호두스무디,B복숭아(80g),S과일샐러드(요거트드레싱),S견과류,수수밥(55),다슬기된장국,참치어묵조림,무몰무침,비트초절이,...,True,True,True,True,True,True,True,True,True,15
198,B미역죽,B두유(100ml),B멜론(50g),S복숭아(천도)-60g,S복숭아(60g),찹쌀밥(40),닭고기채소찌개,(저염)갈치조림,동초무침,열무물김치,...,True,True,True,True,True,True,True,True,True,15
199,B새우크림소스볶음,B고구마쉐이크,B복숭아(60g),S멜론(100g),S멜론(50g),흑미밥(63),매콤애호박국,삼치무조림,애호박볶음,배추김치,...,True,True,True,True,True,True,True,True,True,15

In [398]:
np.mean(new_diet['Total_sum'])

15.0

In [399]:
new_diet.to_excel('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(캠프)/가식단 0614/0614가식단_소아(6~8세,여)_morning.xlsx', encoding = 'utf-8-sig')

In [423]:
def nutrition_calculte_912_boy(db, df):   
    total_sum = pd.DataFrame()

    cat = ['Energy', 'Protein', 'Fat', 'Carbohydrate', 'Total Dietary', 'Calcium',
       'Iron', 'Sodium', 'Vitamin A', 'Vitamin B1 (Thiamine)',
       'Vitamin B2 (Rivoflavin)', 'Vitamin C', 'Linoleic Acid',
       'Alpha-Linolenic Acid']

    for j in range(len(df)):

        menu_sum = pd.DataFrame(columns = cat)
        count = 0

        for i in range(len(df.columns)):
            menu_sum = menu_sum.append(db[db.name == df[i][j]][cat].iloc[0])

        menu_sum = pd.DataFrame([menu_sum.sum(axis = 0)], columns = cat)
        menu_sum['Carbohydrate_ratio'] = menu_sum['Carbohydrate'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Protein_ratio'] = menu_sum['Protein'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Fat_ratio'] = menu_sum['Fat'].values[0]*9/menu_sum['Energy'].values[0]

        if menu_sum['Energy'][0] >= 1800 and menu_sum['Energy'][0] <= 2200:  # Energy
            menu_sum['Energy_'] = True
            count += 1
        else: 
            menu_sum['Energy_'] = False

        if menu_sum['Protein'][0] >= 37.5:  # Protein
            menu_sum['Protein_'] = True
            count += 1
        else: 
            menu_sum['Protein_'] = False

        if menu_sum['Total Dietary'][0] >= 16 and menu_sum['Total Dietary'][0] <= 25:  # 식이섬유
            menu_sum['Total Dietary_'] = True
            count += 1
        else: 
            menu_sum['Total Dietary_'] = False

        if menu_sum['Vitamin A'][0] >= 450 and menu_sum['Vitamin A'][0] <= 750: # 비타민 A
            menu_sum['Vitamin A_'] = True
            count += 1
        else: 
            menu_sum['Vitamin A_'] = False

        if menu_sum['Vitamin C'][0] >= 52.5 and menu_sum['Vitamin C'][0] <= 87.5: # 비타민 C
            menu_sum['Vitamin C_'] = True
            count += 1
        else: 
            menu_sum['Vitamin C_'] = False

        if menu_sum['Vitamin B1 (Thiamine)'][0] >= 0.675 and menu_sum['Vitamin B1 (Thiamine)'][0] <= 1.125: # 비타민 B1
            menu_sum['Vitamin B1 (Thiamine)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B1 (Thiamine)_'] = False

        if menu_sum['Vitamin B2 (Rivoflavin)'][0] >= 0.825 and menu_sum['Vitamin B2 (Rivoflavin)'][0] <= 1.375: # 비타민 B2
            menu_sum['Vitamin B2 (Rivoflavin)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B2 (Rivoflavin)_'] = False

        if menu_sum['Calcium'][0] >= 600 and menu_sum['Calcium'][0] <= 1000: # 칼슘
            menu_sum['Calcium_'] = True
            count += 1
        else: 
            menu_sum['Calcium_'] = False

        if menu_sum['Iron'][0] >= 8.25 and menu_sum['Iron'][0] <= 13.75: # 철
            menu_sum['Iron_'] = True
            count += 1
        else: 
            menu_sum['Iron_'] = False

        if menu_sum['Sodium'][0] < 2300: # 나트륨
            menu_sum['Sodium_'] = True
            count += 1
        else: 
            menu_sum['Sodium_'] = False

        if menu_sum['Linoleic Acid'][0] <= 11875: # 리놀레산
            menu_sum['Linoleic Acid_'] = True
            count += 1
        else: 
            menu_sum['Linoleic Acid_'] = False

        if  menu_sum['Alpha-Linolenic Acid'][0] <= 1625: # 알파 리놀레산
            menu_sum['Alpha-Linolenic Acid_'] = True
            count += 1
        else: 
            menu_sum['Alpha-Linolenic Acid_'] = False

        if menu_sum['Carbohydrate_ratio'][0] >= 0.55 and menu_sum['Carbohydrate_ratio'][0] <= 0.65: # Carbohydrate ratio
            menu_sum['Carbohydrate_ratio_'] = True
            count += 1
        else: 
            menu_sum['Carbohydrate_ratio_'] = False

        if menu_sum['Protein_ratio'][0] >= 0.07 and menu_sum['Protein_ratio'][0] <= 0.20: # Protein ratio
            menu_sum['Protein_ratio_'] = True
            count += 1
        else: 
            menu_sum['Protein_ratio_'] = False

        if menu_sum['Fat_ratio'][0] >= 0.15 and menu_sum['Fat_ratio'][0] <= 0.30: # Fat ratio
            menu_sum['Fat_ratio_'] = True
            count += 1
        else: 
            menu_sum['Fat_ratio_'] = False
        

        menu_sum['Total_sum'] = count


        total_sum = total_sum.append(menu_sum)
        
    total_sum = total_sum.reset_index(drop = True)

    return pd.concat([df, total_sum], axis = 1)

In [425]:
new_diet = nutrition_calculte_912_boy(db_912, diet_912_boy)
new_diet

,0,1,2,3,4,5,6,7,8,9,...,Vitamin B2 (Rivoflavin)_,Calcium_,Iron_,Sodium_,Linoleic Acid_,Alpha-Linolenic Acid_,Carbohydrate_ratio_,Protein_ratio_,Fat_ratio_,Total_sum
0,기장밥(75),실파장국,건취나물간장볶음,S과일화채,S복숭아(천도)-60g,기장밥(75),늙은호박국,돼지고기청경채볶음,참치양파볶음,비트초절이,...,True,True,True,True,True,True,True,True,True,15
1,흑미밥(75),어묵국수,당근스틱,S복숭아(천도)-80g,S사과(35g),흑미밥(75),순한백짬뽕국,닭가슴살고구마볶음,맛살볶음,나박김치,...,True,True,True,True,True,True,True,True,True,15
2,참치주먹밥,팽이장국,더덕사과무침,S복숭아(80g),S멜론(50g),수수밥(75),실파장국,두부채소전,매쉬드포테이토,얼갈이배추김치,...,True,True,True,True,True,True,True,True,True,15
3,잡곡밥(75),우동국물,맛살볶음,S사과(35g),S사과(50g),잡곡밥(75),매콤애호박국,깻잎감자전,건새우애호박볶음,나박김치,...,True,True,True,True,True,True,True,True,True,15
4,해물우동볶음,동태살무국,건취나물간장볶음,S멜론(50g),S멜론(75g),고구마밥(75),호박감자수제비국,레몬소스탕수육,진미채초무침,배추김치,...,True,True,True,True,True,True,True,True,True,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,밤밥(75),쑥갓어묵국,요거트과일샐러드,S복숭아(80g),S복숭아(천도)-80g,밤밥(75),팽이장국,제육짜장볶음,매쉬드포테이토,배추김치,...,True,True,True,True,True,True,True,True,True,15
196,수수밥(75),늙은호박국,맛살볶음,S멜론(50g),S오이스틱,새우크림스파게티,호박감자수제비국,닭감자조림,상추오이무침,나박김치,...,True,True,True,True,True,True,True,True,True,15
197,쌀밥(75),오징어찌개,콘샐러드,S복숭아(80g),S복숭아(천도)-80g,쌀밥(75),새우젓국찌개,가자미구이,요거트과일샐러드,단배추물김치,...,True,True,True,True,True,True,True,True,True,15
198,새우크림스파게티,감자된장국,매쉬드포테이토,S사과(50g),S멜론(50g),율무밥(75),모듬버섯찌개,수제비샐러드,건새우애호박볶음,나박김치,...,True,True,True,True,True,True,True,True,True,15
199,율무밥(75),팽이장국,(우유제외)고구마두유조림,S복숭아(80g),S복숭아(천도)-80g,율무밥(75),실파장국,닭가슴살채소말이조림,땅콩우엉조림,깻잎김치,...,True,True,True,True,True,True,True,True,True,15

In [427]:
np.mean(new_diet['Total_sum'])

15.0

In [428]:
new_diet.to_excel('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(캠프)/가식단 0614/0614가식단_소아(9~12세,남).xlsx', encoding = 'utf-8-sig')

In [429]:
def nutrition_calculte_912_girl(db, df):   
    total_sum = pd.DataFrame()

    cat = ['Energy', 'Protein', 'Fat', 'Carbohydrate', 'Total Dietary', 'Calcium',
       'Iron', 'Sodium', 'Vitamin A', 'Vitamin B1 (Thiamine)',
       'Vitamin B2 (Rivoflavin)', 'Vitamin C', 'Linoleic Acid',
       'Alpha-Linolenic Acid']

    for j in range(len(df)):

        menu_sum = pd.DataFrame(columns = cat)
        count = 0

        for i in range(len(df.columns)):
            menu_sum = menu_sum.append(db[db.name == df[i][j]][cat].iloc[0])

        menu_sum = pd.DataFrame([menu_sum.sum(axis = 0)], columns = cat)
        menu_sum['Carbohydrate_ratio'] = menu_sum['Carbohydrate'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Protein_ratio'] = menu_sum['Protein'].values[0]*4/menu_sum['Energy'].values[0]
        menu_sum['Fat_ratio'] = menu_sum['Fat'].values[0]*9/menu_sum['Energy'].values[0]

        if menu_sum['Energy'][0] >= 1620 and menu_sum['Energy'][0] <= 1980:  # Energy
            menu_sum['Energy_'] = True
            count += 1
        else: 
            menu_sum['Energy_'] = False

        if menu_sum['Protein'][0] >= 33.75:  # Protein
            menu_sum['Protein_'] = True
            count += 1
        else: 
            menu_sum['Protein_'] = False

        if menu_sum['Total Dietary'][0] >= 16 and menu_sum['Total Dietary'][0] <= 25:  # 식이섬유
            menu_sum['Total Dietary_'] = True
            count += 1
        else: 
            menu_sum['Total Dietary_'] = False

        if menu_sum['Vitamin A'][0] >= 412.5 and menu_sum['Vitamin A'][0] <= 687.5: # 비타민 A
            menu_sum['Vitamin A_'] = True
            count += 1
        else: 
            menu_sum['Vitamin A_'] = False

        if menu_sum['Vitamin C'][0] >= 52.5 and menu_sum['Vitamin C'][0] <= 87.5: # 비타민 C
            menu_sum['Vitamin C_'] = True
            count += 1
        else: 
            menu_sum['Vitamin C_'] = False

        if menu_sum['Vitamin B1 (Thiamine)'][0] >= 0.675 and menu_sum['Vitamin B1 (Thiamine)'][0] <= 1.125: # 비타민 B1
            menu_sum['Vitamin B1 (Thiamine)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B1 (Thiamine)_'] = False

        if menu_sum['Vitamin B2 (Rivoflavin)'][0] >= 0.75 and menu_sum['Vitamin B2 (Rivoflavin)'][0] <= 1.25: # 비타민 B2
            menu_sum['Vitamin B2 (Rivoflavin)_'] = True
            count += 1
        else: 
            menu_sum['Vitamin B2 (Rivoflavin)_'] = False

        if menu_sum['Calcium'][0] >= 600 and menu_sum['Calcium'][0] <= 1000: # 칼슘
            menu_sum['Calcium_'] = True
            count += 1
        else: 
            menu_sum['Calcium_'] = False

        if menu_sum['Iron'][0] >= 7.5 and menu_sum['Iron'][0] <= 12.5: # 철
            menu_sum['Iron_'] = True
            count += 1
        else: 
            menu_sum['Iron_'] = False

        if menu_sum['Sodium'][0] < 2300: # 나트륨
            menu_sum['Sodium_'] = True
            count += 1
        else: 
            menu_sum['Sodium_'] = False

        if menu_sum['Linoleic Acid'][0] <= 11250: # 리놀레산
            menu_sum['Linoleic Acid_'] = True
            count += 1
        else: 
            menu_sum['Linoleic Acid_'] = False

        if  menu_sum['Alpha-Linolenic Acid'][0] <= 1375: # 알파 리놀레산
            menu_sum['Alpha-Linolenic Acid_'] = True
            count += 1
        else: 
            menu_sum['Alpha-Linolenic Acid_'] = False

        if menu_sum['Carbohydrate_ratio'][0] >= 0.55 and menu_sum['Carbohydrate_ratio'][0] <= 0.65: # Carbohydrate ratio
            menu_sum['Carbohydrate_ratio_'] = True
            count += 1
        else: 
            menu_sum['Carbohydrate_ratio_'] = False

        if menu_sum['Protein_ratio'][0] >= 0.07 and menu_sum['Protein_ratio'][0] <= 0.20: # Protein ratio
            menu_sum['Protein_ratio_'] = True
            count += 1
        else: 
            menu_sum['Protein_ratio_'] = False

        if menu_sum['Fat_ratio'][0] >= 0.15 and menu_sum['Fat_ratio'][0] <= 0.30: # Fat ratio
            menu_sum['Fat_ratio_'] = True
            count += 1
        else: 
            menu_sum['Fat_ratio_'] = False
        

        menu_sum['Total_sum'] = count


        total_sum = total_sum.append(menu_sum)
        
    total_sum = total_sum.reset_index(drop = True)

    return pd.concat([df, total_sum], axis = 1)

In [430]:
new_diet = nutrition_calculte_912_girl(db_912, diet_912_girl)
new_diet

,0,1,2,3,4,5,6,7,8,9,...,Vitamin B2 (Rivoflavin)_,Calcium_,Iron_,Sodium_,Linoleic Acid_,Alpha-Linolenic Acid_,Carbohydrate_ratio_,Protein_ratio_,Fat_ratio_,Total_sum
0,잡곡밥(75),새우젓국찌개,동초무침,S멜론(50g),S사과(35g),잡곡밥(75),실파장국,뿌리채소맛탕,숙주당근나물,비트초절이,...,True,True,True,True,True,True,True,True,True,15
1,수수밥(75),청국장국,파래무채무침,S복숭아(천도)-60g,S복숭아(60g),새우크림스파게티,모듬버섯찌개,오징어청경채볶음,미역초무침,나박김치,...,True,True,True,True,True,True,True,True,True,15
2,잡곡밥(75),가지냉국,미역줄기채소볶음,S사과(35g),S멜론(50g),잡곡밥(75),도토리묵냉국,카레닭가슴살볶음,요거트과일샐러드,비트초절이,...,True,True,True,True,True,True,True,True,True,15
3,잡곡밥(75),청국장국,고구마줄기볶음,S사과(50g),S배(50g),잡곡밥(75),모듬버섯찌개,감자그라탕,파래무채무침,깻잎김치,...,True,True,True,True,True,True,True,True,True,15
4,잡곡밥(75),늙은호박국,당근스틱,S멜론(50g),S사과(35g),우동,매콤애호박국,닭가슴살고구마볶음,동초무침,비트초절이,...,True,True,True,True,True,True,True,True,True,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,찹쌀팥밥(75),맑은가쓰오부시장국,땅콩우엉조림,S멜론(50g),S복숭아(황도)-80g,찹쌀팥밥(75),애호박국,삼겹살구이,견과류멸치볶음,열무김치,...,True,True,True,True,True,True,True,True,True,15
196,브로콜리채소볶음밥,유부쑥갓맑은국,상추오이무침,S사과(35g),S사과(50g),찹쌀현미밥(75),우동국물,오징어청경채볶음,매콤숙주미나리무침,콜라비나박김치,...,True,True,True,True,True,True,True,True,True,15
197,찹쌀팥밥(75),청국장국,맛살볶음,S멜론(50g),S당근스틱,크림소스스파게티,늙은호박국,오징어볶음,애호박새우젓볶음,비트초절이,...,True,True,True,True,True,True,True,True,True,15
198,소고기하이라이스,새우젓국찌개,동초무침,S복숭아(80g),S복숭아(천도)-80g,찹쌀밥(75),애호박새우젓국,치즈닭갈비,새우살호박볶음,깻잎김치,...,True,True,True,True,True,True,True,True,True,15
199,찰현미밥(75),늙은호박국,애호박볶음,S사과(35g),S사과(50g),참치주먹밥,오징어찌개,삼치무조림,가지양념무침,비트초절이,...,True,True,True,True,True,True,True,True,True,15

In [431]:
np.mean(new_diet['Total_sum'])

15.0

In [432]:
new_diet.to_excel('C:/Users/unist/Desktop/Service Lab/2023 고신대/식단 생성(캠프)/가식단 0614/0614가식단_소아(9~12세,여).xlsx', encoding = 'utf-8-sig')

In [10]:
diet_35_2020_mor = index_to_food(diet_35_2020_mor)
diet_35_2020 = index_to_food(diet_35_2020)
diet_35_2023_mor = index_to_food(diet_35_2023_mor)
diet_35_2023 = index_to_food(diet_35_2023)

diet_68_2020_mor = index_to_food(diet_68_2020_mor)
diet_68_2020 = index_to_food(diet_68_2020)
diet_b_68_2023_mor = index_to_food(diet_b_68_2023_mor)
diet_b_68_2023 = index_to_food(diet_b_68_2023)
diet_g_68_2023_mor = index_to_food(diet_g_68_2023_mor)
diet_g_68_2023 = index_to_food(diet_g_68_2023)

In [99]:
### 일주일 식단 작성 ###

def month_diet(db, db_mor):
    
    month_diet = pd.DataFrame()
    for i in range(4):
        week_diet = []
        for i in range(7):
            if i < 4:
                week_diet.append(db_mor.loc[np.random.choice(db_mor.index)])
            else:
                week_diet.append(db.loc[np.random.choice(db.index)])

        month_diet = pd.concat([month_diet, pd.DataFrame(week_diet)])


    return month_diet.reset_index(drop=True)

In [12]:
diet_35_month_diet2020 = month_diet(diet_35_2020, diet_35_2020_mor)
diet_35_month_diet2023 = month_diet(diet_35_2023, diet_35_2023_mor)
diet_68_month_diet2020 = month_diet(diet_68_2020, diet_68_2020_mor)
diet_b_68_month_diet2023 = month_diet(diet_b_68_2023, diet_b_68_2023_mor)
diet_g_68_month_diet2023 = month_diet(diet_g_68_2023, diet_g_68_2023_mor)

In [13]:
diet_35_month_diet2020.to_csv('0509가식단_유아(3~5세)_2020.csv', encoding = 'utf-8-sig')
diet_35_month_diet2023.to_csv('0509가식단_유아(3~5세)_2023.csv', encoding = 'utf-8-sig')
diet_68_month_diet2020.to_csv('0509가식단_소아(6~8세)_2020.csv', encoding = 'utf-8-sig')
diet_b_68_month_diet2023.to_csv('0509가식단_소아(6~8세, 남아)_2023.csv', encoding = 'utf-8-sig')
diet_g_68_month_diet2023.to_csv('0509가식단_소아(6~8세, 여아)_2023.csv', encoding = 'utf-8-sig')

In [24]:
diet_35_2023_mor

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,고구마순들깨나물,견과류고구마범벅,S보리떡(40g),맑은짬뽕국,단무지,B검은깨두유(150ml),찹쌀현미밥(40),실파콩나물국,B오이당근스틱,S쑥떡,S메밀국수,(고춧가루제외)상추겉절이,토마토새우볶음밥,배추김치,B매실젤리,감자전,S망고주스
1,실곤약채소무침,S오미자차,S온메밀국수,B복숭아(천도)-80g,S매실젤리,새우맛연근튀김,머윗대들깨나물,오이피클,표고버섯콩나물밥,쪽파무채국,씻은김치볶음밥,그린샐러드,B수정과,깻잎김치,B우유(100ml),미역장국,S수정과
2,B약식,버섯무국,동치미,도라지들깨나물,B참외(100g),S메밀국수,건파래전,콘샐러드(올리브유드레싱),마늘쫑무침,토마토새우볶음밥,양배추된장국,단무지,S오렌지주스,B바나나쉐이크,흑미밥,S쿠키,S쑥떡
3,소고기카레라이스,S미숫가루,석박지,B크로와상(30g),B두유(100ml),S매실쥬스,보리밥(40),달래김무침,청경채초무침,S망고주스,애호박새우젓볶음,B멜론(75g),맑은짬뽕국,오이소박이김치,S버터감자구이,애호박버섯볶음,실파콩나물국
4,양상추샐러드(오리엔탈드레싱),맛살당근볶음,양배추된장국,B복숭아(천도)-80g,S케이크,미니칼국수,단무지,S매실젤리,건새우애호박채소볶음,깻잎김치,B우유(100ml),B아몬드,호박나물,고구마밥(30),S메밀국수,S새송이버섯죽,토마토새우볶음밥
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,실파콩나물국,깻잎김치,오징어채볶음,S노란시루떡,S꿀호떡,B치즈스크램블에그,밥새우주먹밥,B달걀당근죽,S배(50g),고로케,애호박당근볶음,일본식소고기덮밥(규동),새우맛연근튀김,B키위(100g),다시마채국,비트초절이,S레몬주스
96,B사과(50g),소고기굴소스덮밥,오이피클,S충무김밥,김구이,S쑥떡,들깨열무볶음,실파무채국,버섯덮밥,콩나물간장무침,단무지무침,S망고주스,B토마토주스,S케이크,애호박새우젓국찌개,김구이+달래양념장,B검은깨두유(150ml)
97,감자전,고구마순들깨나물,감자부추국,단무지,오이소박이김치,모듬어묵국,S사과(50g),오이부추무침,B우유(100ml),S수정과,B참외(100g),S메밀국수,토마토새우볶음밥,소고기콩나물밥+양념장,B백설기(80g),고로케,S참깨타락죽
98,S망고주스,소보로덮밥,S매실젤리,새우맛연근튀김,다시마양파국,표고버섯콩나물밥,검정콩조림,S레몬주스,실파콩나물국,B복숭아(백도)-60g,고구마연근맛탕,깻잎김치,B타락죽,동치미,콘샐러드(올리브유드레싱),B우유(150ml),S복숭아(황도)-80g
99,S쑥떡,S연두부게살스프,들깨탕,소고기카레라이스,B쿠키,S메밀국수,배추김치,조미김,브로콜리초고추장무침,고구마순들깨나물,도라지배무침,단무지,B바나나쉐이크,S단호박죽,오징어감자국,B으깬견과류고구마샐러드(요거트),찹쌀팥밥(30)

In [25]:
diet_35_2023_mor.to_csv('0515sample.csv', encoding = 'utf-8-sig')